Version: 17.2.2
Installer:
- InstallerUrl: https://download.wondershare.com/cbs_down/uniconverter_64bit_17.2.2_full14204.exe
  ProductCode: UniConverter 17_is1
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    1. Image Converter: Customize output quality when converting images in batches.
    2. DVD Burner: 10 brand-new graduation season DVD menu templates added.
    3. Video Compressor: Minor user experience improvements.
- Key: PackageName
  Value: Wondershare UniConverter 17
RealVersion: 17.2.2.505
