Version: 261.22158.49
Installer:
- Architecture: x64
  InstallerUrl: https://download.jetbrains.com/rustrover/RustRover-261.22158.49.exe
  ProductCode: RustRover 261.22158.49
  InstallerSha256: 9805ECD8389D4F5A967AE383052BD00E11F3E3D058C1CA7AFCAF5CC3F19253A3
- Architecture: arm64
  InstallerUrl: https://download.jetbrains.com/rustrover/RustRover-261.22158.49-aarch64.exe
  ProductCode: RustRover 261.22158.49
  InstallerSha256: 683458C0525CC09F29061C85E70D0D4BE71C13910F5DFA329F726A3DE4B9647C
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    The RustRover 2026.1 EAP 7 build is now available!
    Here are full release notes.
- Key: ReleaseNotesUrl
  Value: https://youtrack.jetbrains.com/articles/RUST-A-333
ReleaseTime: 2026-03-06
