Version: 262.7132.24
Installer:
- Architecture: x64
  InstallerUrl: https://download.jetbrains.com/rustrover/RustRover-262.7132.24.exe
  ProductCode: RustRover 262.7132.24
  InstallerSha256: B4AB6285F8AF8C7F1C758E14ED4F301BBD235B26202BF0E195468D1C8B6526A4
- Architecture: arm64
  InstallerUrl: https://download.jetbrains.com/rustrover/RustRover-262.7132.24-aarch64.exe
  ProductCode: RustRover 262.7132.24
  InstallerSha256: 571D0756240CA31EEAF0BF1E689C89A8530AC4A183FF48BFB1A5BD805F0196DD
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    The RustRover 2026.2 EAP 5 build is now available!
    Here are full release notes.
- Key: ReleaseNotesUrl
  Value: https://youtrack.jetbrains.com/articles/RUST-A-376
ReleaseTime: 2026-06-05
