Version: 263.4732.29
Installer:
- Architecture: x64
  InstallerUrl: https://download.jetbrains.com/rustrover/RustRover-263.4732.29.exe
  ProductCode: RustRover 263.4732.29
  InstallerSha256: 6FC80FD8D28B16CC90387437D04951EB04436DB87E5650E35365204B69058CEC
- Architecture: arm64
  InstallerUrl: https://download.jetbrains.com/rustrover/RustRover-263.4732.29-aarch64.exe
  ProductCode: RustRover 263.4732.29
  InstallerSha256: 153668D9CE20FFD62CCD6F4599A85DED093200825EF7DFA4FB9FDFA00106F70E
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    RustRover 2026.3 EAP 2 build is now available!
    Here are full release notes.
- Key: ReleaseNotesUrl
  Value: https://youtrack.jetbrains.com/articles/RUST-A-413
ReleaseTime: 2026-09-11
