Version: "2.29"
Installer:
- Architecture: x86
  InstallerUrl: https://tools.audiocodes.com/install/syslogViewer/syslogViewer-setup-32.exe
  AppsAndFeaturesEntries:
  - DisplayVersion: 2.29 (32 bit)
- Architecture: x64
  InstallerUrl: https://tools.audiocodes.com/install/syslogViewer/syslogViewer-setup.exe
  AppsAndFeaturesEntries:
  - DisplayVersion: "2.29"
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - Fix zero timestamp regression in SIP Flow Diagram.
    - New "Subscribes" option in SIP Flow Diagram filter.
    - Show stream for Voice.AI Connect logs.
ReleaseTime: 2026-03-08
