Version: 2026.2.1
Installer:
- InstallerUrl: https://download.jetbrains.com/resharper/dotUltimate.2026.2.1/JetBrains.dotUltimate.2026.2.1.exe
  InstallerSha256: 736DB70059BE09BC70C5A398906B715EC46D226A84BA4366BBEACD2480999600
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    ReSharper 2026.2.1 comes with:
    - Out-of-Process (OOP) mode enabled by default, unless you explicitly disabled it before.
    - OOP mode support in dotCover, which now runs OOP by default instead of forcing ReSharper to run in-process when installed.
    - Visual dependency analysis diagramming support in OOP mode.
    - An update to Junie that adds support for Claude Opus 5 as a model.
    For the full list of updates included in this release, see the What's New page.
- Key: ReleaseNotesUrl
  Value: https://youtrack.jetbrains.com/articles/DOTNET-A-386/ReSharper-Tools-2026.2.1-release-notes
ReleaseTime: 2026-08-19
