Version: 0.0.93
Installer:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/AQBot-Desktop/AQBot/releases/download/v0.0.93/AQBot_0.0.93_x64-setup.exe
- Architecture: arm64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/AQBot-Desktop/AQBot/releases/download/v0.0.93/AQBot_0.0.93_arm64-setup.exe
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://github.com/AQBot-Desktop/AQBot/releases/download/v0.0.93/AQBot_0.0.93_x64_en-US.msi
- Architecture: arm64
  InstallerType: wix
  InstallerUrl: https://github.com/AQBot-Desktop/AQBot/releases/download/v0.0.93/AQBot_0.0.93_arm64_en-US.msi
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    🐛 Bug 修复
    - drawing: 修复历史区底部空白 (#04222eb)
    - drawing: 支持历史滚动和图片粘贴 (#5daef4d)
    - drawing: 合并参考图编辑请求修复 (#c64d0c7)
    - drawing: 修复参考图编辑请求 (#9c8b7c8)
    - chat: stabilize stream completion (#874d23e)
    🚀 新功能
    - gateway: 添加修复可见性工具的图标 (#87a0d82)
- Locale: zh-CN
  Key: ReleaseNotesUrl
  Value: https://github.com/AQBot-Desktop/AQBot/releases/tag/v0.0.93
ReleaseTime: 2026-06-13T16:24:40.0000000Z
