Version: 1.14.0
Installer:
- Architecture: x64
  InstallerUrl: https://dl.google.com/release2/Google%20DeepMind/aduwcapstkzvhnjcpawakc5hjfkq_1.14.0/GeminiSetup-1.14.0_uncompressed.exe
- Architecture: arm64
  InstallerUrl: https://dl.google.com/release2/Google%20DeepMind/kh2q2zpownuw5ywnxniprzis2q_1.14.0/GeminiSetup-1.14.0_uncompressed.exe
Locale: []
