Version: 1.0.0.beta.2
Installer:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/DrizzleTime/Skiff/releases/download/v1.0.0.beta.2/skiff_1.0.0_x64-setup.exe
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    修复 windows 保存设置失败的问题
    优化 AI 空间分析体验
- Locale: zh-CN
  Key: ReleaseNotesUrl
  Value: https://github.com/DrizzleTime/Skiff/releases/tag/v1.0.0.beta.2
ReleaseTime: 2026-06-27T12:30:35.0000000Z
RealVersion: 1.0.0
