Version: 4.0.0.37
Installer:
- Architecture: x86
  InstallerUrl: https://codesector.nyc3.cdn.digitaloceanspaces.com/teracopy4.0.0.37.exe
  ProductCode: '{D23F90D9-4A27-4FD1-8078-DC879FAF2E28}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{591EBD44-A7B6-491E-BE02-6A863257EFE1}'
    InstallerType: msi
- Architecture: x64
  InstallerUrl: https://codesector.nyc3.cdn.digitaloceanspaces.com/teracopy4.0.0.37.exe
  ProductCode: '{D23F90D9-4A27-4FD1-8078-DC879FAF2E28}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{591EBD44-A7B6-491E-BE02-6A863257EFE1}'
    InstallerType: msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    New Features
    - New multi-threaded copy engine.
    - Enhanced speed graph.
    - New multi-threaded copy engine.
    - Support for copying to multiple targets.
    - Queue system for managing multiple copy operations.
    - Support for receiving files via the LocalSend protocol.

    Enhancements
    - Improved database operations.

    Fixed Bugs
    - Removed the confirmation prompt when merging folders during a move operation.
    - When moving a folder within the same drive, it no longer retries the folder in the second pass.
    - Fixed rare crashes that could occur during concurrent file operations.
    - Fixed issues when copying or moving files to a large number of destinations.
    - Fixed a crash when a LocalSend transfer was cancelled before being accepted.
    - Minor UI fixes.
RealVersion: 4.0.0.37
ReleaseTime: 2026-07-06
