Version: "7.53"
Installer:
- Architecture: x86
  InstallerUrl: https://www.softwareok.com/Download/DirPrintOK_Installer.zip
- Architecture: x64
  InstallerUrl: https://www.softwareok.com/Download/DirPrintOK_Installer_x64.zip
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - Further improvements: for smartphones, iPhones, etc., connections via USB cable
    - Minor refinements in Dir-Print-OK for all Windows operating systems
ReleaseTime: 2026-03-05
