Version: 0.36.5
Installer:
- Architecture: x64
  InstallerUrl: https://download.todesktop.com/2108257l5oobyoe/ToDesktop Builder Setup 0.36.5 - Build 260616pykxs1i6s-x64.exe
Locale:
- Key: ReleaseNotesUrl
  Value: https://www.todesktop.com/changelog
ReleaseTime: 2026-06-16T12:21:01.0000000Z
