Version: 3.3.5.7
Installer:
- Architecture: x64
  InstallerUrl: https://download.pixpinapp.com/PixPin_win_3.3.5.7.exe
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    【修复】某些场景下程序会崩溃
    【修复】在 windows7 上启动失败
- Locale: zh-CN
  Key: ReleaseNotesUrl
  Value: https://pixpin.cn/docs/change-log/3.3.5.7
ReleaseTime: 2026-06-14T14:22:48.0000000Z
