Version: 46.7.0.35381
Installer:
- Architecture: x64
  InstallerUrl: https://binaries.webex.com/WebexDesktop-Win-64-Gold/20260710041447/Webex.msi
- Architecture: arm64
  InstallerUrl: https://binaries.webex.com/webexdesktop-win-arm-64-gold/20260710041008/Webex.msi
Locale: []
