Version: 4.2.1165
Installer:
- InstallerLocale: en
  InstallerUrl: https://storage.googleapis.com/images.abasky.net/119676df089a90ab3c3004398806433938052586dcd9a6bcacfb0e3e4024f339/4.2.1165/abaclient-4.2.1165-en.msi
- InstallerLocale: de
  InstallerUrl: https://storage.googleapis.com/images.abasky.net/119676df089a90ab3c3004398806433938052586dcd9a6bcacfb0e3e4024f339/4.2.1165/abaclient-4.2.1165-de.msi
- InstallerLocale: fr
  InstallerUrl: https://storage.googleapis.com/images.abasky.net/119676df089a90ab3c3004398806433938052586dcd9a6bcacfb0e3e4024f339/4.2.1165/abaclient-4.2.1165-fr.msi
- InstallerLocale: it
  InstallerUrl: https://storage.googleapis.com/images.abasky.net/119676df089a90ab3c3004398806433938052586dcd9a6bcacfb0e3e4024f339/4.2.1165/abaclient-4.2.1165-it.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Release Notes:

    - Removal of the ability to import AbaStart links
    - Removal of the AbaClient setting 'Clear browser cache at start'. This option is no longer required due to improvements in the background.
    - Update of Java versions to 17 and 21
    - Automatic deletion of the .abalink file from the Downloads directory
- Locale: de-DE
  Key: ReleaseNotes
  Value: |-
    Release Notes:

    - Entfernung der Möglichkeit AbaStart Verknüpfungen zu importieren
    - Entfernung der AbaClient Settings Option 'Browser Cache nach Start löschen'. Durch Verbesserungen im Hintergrund ist diese Option nicht mehr erforderlich.
    - Update der Java Versionen auf 17 und 21
    - Automatisches Löschen der .abalink Datei aus dem Downloads Verzeichnis
- Locale: fr-FR
  Key: ReleaseNotes
  Value: |-
    Release Notes:

    - Suppression de la possibilité d'importer des liens AbaStart
    - Suppression de l'option des paramètres AbaClient 'Effacer le cache du navigateur au démarrage'. Cette option n'est plus nécessaire grâce aux améliorations en arrière-plan.
    - Mise à jour des versions Java vers 17 et 21
    - Suppression automatique du fichier .abalink du dossier Téléchargements
- Locale: it-IT
  Key: ReleaseNotes
  Value: |-
    Release Notes:

    - Rimozione della possibilità di importare collegamenti AbaStart
    - Rimozione dell'opzione AbaClient 'Cancella cache del browser all'avvio'. Grazie a miglioramenti in background, questa opzione non è più necessaria.
    - Aggiornamento delle versioni Java a 17 e 21
    - Eliminazione automatica del file .abalink dal Downloads
