Version: 2.1.0
Installer:
- InstallerType: nullsoft
  InstallerUrl: https://download.creativeforce.io/released-files.042024/prod/luma/win/Luma-2.1.0-win.exe
- InstallerType: wix
  InstallerUrl: https://download.creativeforce.io/released-files.042024/prod/luma/win/Luma-2.1.0-win.msi
Locale: []
ReleaseTime: 2026-04-20T05:18:46.7830000Z
