Version: 3.16.4
Installer:
- InstallerUrl: https://github.com/HMCL-dev/HMCL/releases/download/v3.16.4/HMCL-3.16.4.exe
Locale:
- Locale: zh-CN
  Key: ReleaseNotesUrl
  Value: https://docs.hmcl.net/changelog/stable.html#HMCL-3.16.4
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    启动器
    - GP-6871: 支持在 FreeBSD x86-64、Linux Arm64、Linux LoongArch64 和 Linux RISC-V64 平台上启动 Minecraft 26.3-snapshot-10 及更高版本 (by Glavo)
    - GP-6879: 补充 Minecraft 26.3 快照版、预发布版、候选发布版和正式版的版本信息 (by Glavo)
    实例管理
    GP-6878: 优化模组列表的加载性能 (by Glavo)
    外观
    GP-6873: 改进 SVG 图像的识别与加载 (by Glavo)
    下载
    GP-6872: 更新模组数据（2026-07-21） (by Glavo)
    错误修复
    - GP-6874: 修复 Legacy Fabric 实例图标异常的问题 (by Glavo)
    - GP-6875: 修复无法读取以 .zip 为扩展名的模组的问题 (by Glavo, ToobLac)
    - GP-6876: 修复导出包含大型文件的 Modrinth 整合包时可能内存不足的问题 (by Glavo, Apostrophe)
ReleaseTime: 2026-09-17T04:30:46.0000000Z
