Version: 26.04-12063
Installer:
- Architecture: x64
  InstallerUrl: https://cdn.kde.org/ci-builds/utilities/kate/release-26.04/windows/kate-release_26.04-12063-windows-cl-msvc2022-x86_64-sideload.appx
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  InstallerUrl: https://cdn.kde.org/ci-builds/utilities/kate/release-26.04/windows/kate-release_26.04-12063-windows-cl-msvc2022-x86_64-sideload.appx?_
Locale: []
RealVersion: 26.403.12063.0
