Version: 1.3.56
Installer:
- InstallerUrl: https://aibot-install-cdn.easyclaw.com/public/package/easyclawsetup.exe
  InstallerSha256: 3DEA728E7CB40B7CD21E7F4041320CFBDF2F06FC719919F383F49ED1BF7CA6AF
Locale: []
ETag:
- '"15e4e763de473a0fea60b90bfc1a58ea-29"'
