Version: 1.3.39
Installer:
- InstallerUrl: https://aibot-install-cdn.easyclaw.com/public/package/easyclawsetup.exe
  InstallerSha256: 4EFACDA05BFF9F55CB91A64DE5EE4975216A17811EF71D2C4600F326B7F9470E
Locale: []
ETag:
- '"71acb3533f6fcb30f40ddee0691db96b-27"'
