Version: 2.3.0
Installer:
- Architecture: x86
  InstallerUrl: https://github.com/sailpoint-oss/sailpoint-cli/releases/download/2.3.0/sail_2.3.0_windows_386.zip
- Architecture: x64
  InstallerUrl: https://github.com/sailpoint-oss/sailpoint-cli/releases/download/2.3.0/sail_2.3.0_windows_amd64.zip
- Architecture: arm64
  InstallerUrl: https://github.com/sailpoint-oss/sailpoint-cli/releases/download/2.3.0/sail_2.3.0_windows_arm64.zip
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Changelog
    - ccf8f7ac20230175f44f35f44345f7e5ae953be5 Bump version to 2.3.0
    - 3877ab4397617253e923f62f86423e1053e0fef9 Merge pull request #242 from sailpoint-oss/devrel-3005-connector-sdk-migration
    - cf99815f3b6ca573d0b1f246e348c3b252637556 Migrate remaining connector customizer commands to golang-sdk v3
    - 5b1a97b316287345e56a3f5a434f1eea56ebb6cb Migrate connector customizer commands to golang-sdk v3
    - 9946bc0182c6f08c4d5692dd7e60ecb55bec0d09 Merge pull request #236 from sailpoint-oss/devrel-3005
    - e049366e77585ed056c3d6a3247b20465ad9b14f update node version to pass tests
    - f2d453373b5354c5be132df34b7b1eb629c41e55 Migrate to golang-sdk v3 (DEVREL-3005)
    - 6d6484582c3f8adc330091efce356dca675087ea Refactor MSI output handling in GitHub workflows
    - 6e5ea32c1f9b96614876ca9484e31426fb5d6bf1 Update GitHub workflows for MSI build and release process
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/sailpoint-oss/sailpoint-cli/releases/tag/2.3.0
ReleaseTime: 2026-08-20T20:50:38.0000000Z
