Version: 0.0.0.48
Installer:
- InstallerUrl: https://ardisk.cn/download/windows/ardisk-setup.msi
  InstallerSha256: 9B6AAFC17E24193E52E87D09D246D6B0243C4475B803CFE7962C66DEEF8D5536
  ProductCode: '{B57261BD-DA7D-4AEE-BAA2-4BBBFE0781DD}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{82BFF3F8-C379-4DCD-AB22-9A125BCA89E7}'
Locale: []
ContentLength: "29687808"
