Version: 2.11.0164
Installer:
- InstallerUrl: https://abvisual.blob.core.windows.net/visual-lighting/2.11.0164/VisualLighting2020r2Setup.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: 1. Bug 992394 Re-Aim luminaires causes program crash
ReleaseTime: 2025-01-13
