Version: 0.27.4
Installer:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/codexu/note-gen/releases/download/note-gen-v0.27.4/NoteGen_0.27.4_x64-setup.exe
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://github.com/codexu/note-gen/releases/download/note-gen-v0.27.4/NoteGen_0.27.4_x64_en-US.msi
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    - feat(#974): AI 支持跨域请求
    - feat: 移动端历史提交记录改为抽屉组件
    - feat: 优化翻译功能，保持与其他 AI 功能交互逻辑一致
    - feat: 优化润色等工具输出时，避免将思考内容写入到笔记中
    - feat: SM.MS 图床替换为 S.EE
    - refactor: 重构移动端记录页面顶部布局
    - fix(#1020): 修复移动端无法使用大纲的问题
    - fix(#1012): 修复大纲与编辑器布局冲突
    - fix(#1006): 修复远端文件存在空格时无法正确删除的问题
    - fix(#1019): 修复可能由 slash 命令导致回车被劫持的问题
    - fix(#1018): 修复写作资源路径无效的问题
    - fix(#1017): 修复编辑器图片上传未正确保存路径
    - fix(#1016): 文件夹同步未正确读取用户自定义仓库名称
- Key: ReleaseNotesUrl
  Value: https://github.com/codexu/note-gen/releases/tag/note-gen-v0.27.4
ReleaseTime: 2026-03-27T13:51:01.0000000Z
