Version: 0.27.3
Installer:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/codexu/note-gen/releases/download/note-gen-v0.27.3/NoteGen_0.27.3_x64-setup.exe
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://github.com/codexu/note-gen/releases/download/note-gen-v0.27.3/NoteGen_0.27.3_x64_en-US.msi
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    - feat: 增加网络获取配置供应商模板
    - feat(#1004): 添加对 LaTeX 数学公式的支持 (#1010)
    - feat(#1011): 切换文件后，恢复滚动和光标位置
    - fix(#1013): 修复代码块换行问题
    - fix(#1014): 修复文件、文件夹新建会加载远程文件导致卡顿
- Key: ReleaseNotesUrl
  Value: https://github.com/codexu/note-gen/releases/tag/note-gen-v0.27.3
ReleaseTime: 2026-03-26T09:57:19.0000000Z
