Version: 1.1.3
Installer:
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://github.com/morning-start/silk/releases/download/v1.1.3/silk_1.1.3_x64_en-US.msi
Locale:
- Locale: zh-CN
  Key: ReleaseNotesUrl
  Value: https://github.com/morning-start/silk/releases/tag/v1.1.3
- Locale: zh-CN
  Key: ReleaseNotesUrl
  Value: https://github.com/morning-start/silk/blob/HEAD/CHANGELOG.md
ReleaseTime: 2026-09-14T07:03:04.0000000Z
