Version: 26.2.4
Installer:
- Architecture: x64
  InstallerUrl: https://www.dbvis.com/product_download/dbvis-26.2.4/media/dbvis_windows-x64_26_2_4_jre.exe
  InstallerSha256: 002186EC6905E574DCDC7D2F5445F6EB9D663D92602B9AAA3D5E9B526D7CB85C
- Architecture: arm64
  InstallerUrl: https://www.dbvis.com/product_download/dbvis-26.2.4/media/dbvis_windows-arm64_26_2_4_jre.exe
  InstallerSha256: 5E9AC0A43F67477899298237309D7F4BC4010751B243B4B5B6FFB76EEC78A11A
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Improvements
    Command Line Support (dbviscmd)
    Support reading passwords from a file or environment variable in dbviscmd
    DB Support: Amazon Athena
    Add authentication options to the connection setup for Amazon Athena
    DB Support: MariaDB
    Add support for roles in MariaDB
    Bugs Fixed
    AI
    AI Assistant permissions may override stricter SQL Commander permissions
    Command Line Support (dbviscmd)
    Changing a password with dbviscmd leaves the old password in the password store
    DB Support: Azure SQL
    DB Support: SQL Server
    Can't connect to Azure SQL or SQL Server using an IPv6 address
    DB Support: DynamoDB
    Data tab doesn't show the current row range when paging through DynamoDB results
    DB Support: Informix
    Source code may not be available for some procedures and functions in Informix
    DB Support: Oracle
    Clone User omits grant options and Java permissions in Oracle
    Database Objects Tree
    Error when reloading a mounted connection folder
    Grid Component
    Quick search field shows too little of the search text
    Quick search highlights matches in columns excluded from the search
    Notifications
    Error during application shutdown
    Notifications triggered using @notify may appear in the wrong window
    OS Support: macOS
    Double-clicking the title bar ignores the macOS system setting
    Performance/Stability
    Error dialog can't be closed
    Procedure Editor
    Procedure editor may display incorrect source code when it contains international characters
    Procedure Editor
    SQL Commander
    Error after undo in the editor
    SQL Commander
    Error when closing a SQL Commander tab
    Tab groups in floating windows may appear empty after restart
    SSH
    Can't connect through an SSH tunnel when IPv6 is used
    SSH jump server is ignored when using SSHJ
ReleaseTime: 2026-10-08
