Version: 0.4.20-1
Installer:
- Architecture: x64
  InstallerUrl: https://installers.lmstudio.ai/win32/x64/0.4.20-1/LM-Studio-0.4.20-1-x64.exe
- Architecture: arm64
  InstallerUrl: https://installers.lmstudio.ai/win32/arm64/0.4.20-1/LM-Studio-0.4.20-1-arm64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - Support for enterprise internal network model endpoint
    - Added support for using this device’s models in Bionic over LM Link
    - [LM Studio Engine Protocol] Added a developer setting to control the Llama.cpp engine log level
RealVersion: 0.4.20+1
