Version: 0.6.7
Installer:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/zhukunpenglinyutong/desktop-cc-gui/releases/download/v0.6.7/ccgui_0.6.7_x64-setup.exe
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    New Features
    - streamline workspace file and diff controls
    Fixes
    - 保持聊天末尾定位和窗口拖拽跟手
- Locale: zh-CN
  Key: ReleaseNotesUrl
  Value: https://github.com/zhukunpenglinyutong/desktop-cc-gui/releases/tag/v0.6.7
ReleaseTime: 2026-07-07T02:08:38.0000000Z
