Version: 8.1.4.48838
Installer:
- InstallerUrl: https://www.pvsyst.com/download/bin/PVsyst-8.1.4.48838-setup.exe
  ProductCode: PVsyst 8.1.4
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    ** New features

    - Weather data, known format import: integration of ANE-NEDO web API weather data for Japan.

    ** Improvements

    - P50-P90 estimation: the default annual GHI variability model was updated to a linear model based on a larger measurement dataset.

    ** Corrections

    - 3D scene: orientation averaging during 3D import now uses a geometrically correct method that properly handles fields with varying tilt, azimuth, and terrain slope
    - Batch mode: the batch simulations now work also for sub-hourly simulation steps (already fixed in version 8.1.1)
    - Power Factor: fixed issue with reactive and apparent energy values when grid limitation losses are accounted for separately and EGrdLim is not saved
    - Power Factor: fixed issue with apparent energy accumulation for monthly power factors, it is now correctly recognized as the norm of the vector (E_Grid, E_ReGrid)
    - Results: fixed issue with generating user-defined plots
    - Results: after viewing the tables with hourly averages, there is no more error in the irradiance balance check
    - System: increase/decrease arrows for the number of inverters and MPPT inputs now correctly update the values
    - System: fixed an issue where the inverter nominal power distribution to individual MPPT was not always correct with shared inverters
    - Weather data, custom file: importing custom weather data now computes global irradiance when missing from the source data.
- Key: ReleaseNotesUrl
  Value: https://www.pvsyst.com/help/release-notes/index.html#8.1.4
RealVersion: 8.1.4
ReleaseTime: 2026-07-01
