Version: 12.8.1
Installer:
- Architecture: x64
  InstallerUrl: https://lf6-cdn-tos.douyinstatic.com/obj/venus/StreamingTool-12.8.1-x64.exe
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    【抖音】聊天室支持互动工具直播插件玩法
    【抖音】语音聊天室支持飞麦礼物渲染特效
    【抖音】语音自定义模式支持导入导出中控台配置
    【抖音】电商场景新增宠物伴播能力（灰度中）
    【全平台】修复已知问题，提高应用稳定性
