Version: 11.7.2
Installer:
- Architecture: x64
  InstallerUrl: https://lf6-cdn-tos.douyinstatic.com/obj/venus/StreamingTool-11.7.2-x64.exe
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    【抖音】嘉宾模式支持新视频连线玩法
    【抖音】丰富场景转场特效，增加素材转场特效能力
    【抖音】优化 XR 直播光照自适应交互
    【全平台】修复已知问题，提高应用稳定性
