Version: 9.3.16
Installer:
- Architecture: x64
  InstallerUrl: https://github.com/PBH-BTN/PeerBanHelper/releases/download/v9.3.16/PeerBanHelper_windows-x64_9.3.16.exe
- Architecture: arm64
  InstallerUrl: https://github.com/PBH-BTN/PeerBanHelper/releases/download/v9.3.16/PeerBanHelper_windows-arm64_9.3.16.exe
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    下载器兼容
    - 更新适配器以兼容 BitComet v2.21 @Ghost-chu
    Docker
    DockerHub: ghostchu/peerbanhelper:v9.3.16
    阿里云国内镜像加速：registry.cn-hangzhou.aliyuncs.com/ghostchu/peerbanhelper:v9.3.16

    部署教程 | 常见问题 | 如何设置下载器 | PBH-BTN 论坛
- Locale: zh-CN
  Key: ReleaseNotesUrl
  Value: https://github.com/PBH-BTN/PeerBanHelper/releases/tag/v9.3.16
ReleaseTime: 2026-07-04T13:37:50.0000000Z
