Version: 26.0518.2212
Installer:
- InstallerUrl: https://downloads.eligian.com/piicrawler-cli-windows-signed.zip
  InstallerSha256: F4B9F84DA1F364FF6973400E69CB3FFBD83E1D615E98C87225C62532B3CEE19C
Locale: []
ETag:
- '"dim5ipxogx1jilo5x"'
