Version: 26.0601.0147
Installer:
- InstallerUrl: https://downloads.eligian.com/piicrawler-cli-windows-signed.zip
  InstallerSha256: F830518E936176635D5C25279CDAB3D8D6C4E6396F250FD73DD747E41C3F14AE
Locale: []
ETag:
- '"dixcbaptkx2v13bcyt"'
