Version: 26.0701.2031
Installer:
- InstallerUrl: https://downloads.eligian.com/piicrawler-cli-windows-signed.zip
  InstallerSha256: 925E1AA68350951CBAF16BF8C6BD1B8253C75C75F2D558CBB77A208BDAF5DEC9
Locale: []
ETag:
- '"djnj0hees2jw14o7x2"'
