Version: 26.0607.0512
Installer:
- InstallerUrl: https://downloads.eligian.com/piicrawler-cli-windows-signed.zip
  InstallerSha256: D6E54CACEAA743F742177E9DFB72F2CE3AC7C9B2362F95DEFAECCD0FB985D5F4
Locale: []
ETag:
- '"dj2kg43sr6zt132sf4"'
