Version: 1.8.0
Installer:
- InstallerUrl: https://typeless-static.com/desktop-release/Typeless-1.8.0-x64-Setup.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Translate, perfected for your everyday communication

    Communicate across languages exactly like a local.
    Translate now turns your words into a ready-to-send message, email, or post, providing an even closer match to your energy and tone in your target language while adapting to the purpose of your communication.
    Thank you for using Typeless. We hope this update makes your cross-language communication seamless and authentic.
ReleaseTime: 2026-06-16
