Version: 2.3.7
Installer:
- Architecture: x86
  InstallerUrl: https://www.mediahuman.com/files/MHAudioConverter.exe
  InstallerSha256: D00DA691C341EC136C9E20F019CE5E6508A2A7D6979F18DF1CFF14FB28C41B8E
- Architecture: x64
  InstallerUrl: https://www.mediahuman.com/files/MHAudioConverter-x64.exe
Locale: []
LastModified: Wed, 20 May 2026 15:13:18 GMT
LastModifiedX64: Wed, 20 May 2026 15:13:17 GMT
