Version: 2.3.8
Installer:
- Architecture: x86
  InstallerUrl: https://www.mediahuman.com/files/MHAudioConverter.exe
  InstallerSha256: 3BDDE7B88F1D86F863D704136E5362B282AD6708E61BB439D22C95AC12F86CCB
- Architecture: x64
  InstallerUrl: https://www.mediahuman.com/files/MHAudioConverter-x64.exe
Locale: []
LastModified: Wed, 26 Aug 2026 10:32:54 GMT
LastModifiedX64: Wed, 26 Aug 2026 10:32:55 GMT
