Version: 14.6.0.10070
Installer:
- InstallerUrl: https://cdndata.video.iqiyi.com/cdn/pca/20260610/14.6.0.10070/upgrade/x64/1781085477908/IQIYIsetup_update_202606101635.exe
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    更新信息：
    1.《家业》《种地吧 4》《超燃青春的合唱》热播中
    2. 优化一些功能体验，修复一些已知问题
