Version: 5.4.27.5427
Installer:
- Scope: user
  InstallerUrl: https://www.techhit.com/download/SimplyFile5_setup.exe
  InstallerSha256: D4CE0F5EFE6B2100899FCF29AE69D45F56AE4988F7FFD877DA63E18AB5FA3CFA
- Scope: machine
  InstallerUrl: https://www.techhit.com/download/SimplyFile5_admin_setup.exe
Locale: []
ETag:
- '"304d20-653ea6121bf77"'
ETagMachine:
- '"305560-653ea61ce3bc9"'
