Version: v1.3.2-20260414-c1394db
Installer:
- InstallerUrl: https://github.com/kunkundi/crossdesk/releases/download/v1.3.2-20260414-c1394db/crossdesk-win-x64-v1.3.2-20260414-c1394db.exe
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    更新内容
    1. 修复键鼠映射异常的问题。
    2. 修复被控端鼠标不显示的问题。
    3. 修复焦点离开窗口后按键不能正常释放的问题。
    4. 修复 Linux 平台屏幕采集异常黑屏的问题。
    5. 修复 Linux 平台字体显示异常的问题。
    6. 键鼠控制信号传输机制调整为可靠模式。
    7. Linux 平台新增 DRM/Wayland 屏幕采集支持。
- Locale: zh-CN
  Key: ReleaseNotesUrl
  Value: https://github.com/kunkundi/crossdesk/releases/tag/v1.3.2-20260414-c1394db
ReleaseTime: 2026-04-13T16:49:28.0000000Z
