Version: 26.2.0715
Installer:
- InstallerUrl: https://www.thunderheadeng.net/releases/PyroSim-2026-2-0715-x64-en.msi
Locale:
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://www.thunderheadeng.com/docs/2026-2/pyrosim/
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    This release of PyroSim has some powerful new features and improvements to existing capabilities. Download the new version to work more efficiently with CAD geometry and Mesh Refinement Zones!
    CAD Quality Adjustment
    For many years, PyroSim has supported importing CAD geometry. However, users do not always have access to concise models with relevant geometry. Often, there are many CAD objects that complicate and slow down PyroSim.
    PyroSim 2026.2 delivers CAD adjustment features that enable more efficient modeling workflows:
    - On import, you can specify Object Quality (See the Creating Geometry from CAD page). This reduces the number of triangles used to represent imported geometry.
    - After import, you can perform a similar operation upon any selected imported geometry. The new context-menu action allows users to Simplify Imported Geometry.

      Figure 1. Simplifying Imported Geometry
    - Best of all, you can set imported geometry to be ignored in an FDS simulation.

      Figure 2. Display Only
      Use this action to set an object in the model to Display Only and it will not be used in the FDS simulation. Generic Geometry is not converted to OBST or GEOM entries, but are available in Results (when PyroSim Geometry is active).
    Mesh Refinement Zone Enhancements
    PyroSim 2026.2 enhances the Mesh Refinement Zones workflow.
    - This update adds a filter to preview the meshes resulting from refinement zones in the Model View, called Show Mesh Refinement Preview. This adds two new filters to the Mesh filter toolbar.

      Figure 3. Using Show Mesh Refinement Preview
    - Expanded support for nested Mesh Refinement Zones makes them easier to use on building models with floor geometry.

      Figure 4. Nested Mesh Refinement Zones
    - Also, Meshes in the Object Tree now display the optimal level of information about effects of mesh refinement.

      Figure 5. Nested Mesh Refinement Zones with tree info
      When put all together, these changes make it easier to complete your individual workflow and work efficiently with Meshes in PyroSim 2026.2.
    Complete the updated example to experience these changes.
    Control Value Devices
    Users can now cleanly use math controls as inputs to other activation control logic, a long sought after feature.

    Figure 6. Editing Activation Controls
    - Now, Math Control output values can be written to a CSV file and also may be used as numeric inputs for other Mathematical and Custom Controls.
    - This will also help users work with Statistics Devices.
    HVAC 3D Modeling with Waypoints
    Prior to this release, HVAC Waypoints did not have a graphical representation (they were only supported as text entries in a table). Now, Waypoints and the duct paths are visible in the Model View.

    Figure 7. HVAC Waypoints in 2D Top View
    Door Activation Changes
    Behind the scenes changes to controlled activation of openings in PyroSim allow users to more seamlessly build models with doors opening during the simulation.

    Figure 8. Models with holes controlled by Activation work more seamlessly
    (Door closing controls still suffer from the initial state bug.)
    Results Integration with Pathfinder
    Results handling has improved the compatibility of PyroSim (FDS) results with Pathfinder in Results. Read more about the changes to Results in the Results Documentation.
