Version: 2.4.13
Installer:
- InstallerUrl: https://kensingtonsoftware.azureedge.net/software/version/konnect/TrueHueSetup.msi
Locale:
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://www.kensington.com/software/kensington-konnect/
ReleaseTime: 2026-09-30T10:12:38.0800000Z
