Version: "1.8"
Installer:
- InstallerUrl: https://cdn.altstore.io/file/altstore/altserver-windows/1_8.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - Enables support for Remote AltServers (see AltStore FAQ for more info)
    - Adds support for Windows on ARM
ReleaseTime: 2026-09-14T13:04:00.0000000Z
RealVersion: 1.8.00
