Version: 0.2.4
Installer:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/0xsline/OpenChatCut/releases/download/v0.2.4/OpenChatCut-0.2.4-x64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    What's Changed
    - test(external-agent): cover direct-touch lease refresh by @Lenouw in https://github.com/0xsline/OpenChatCut/pull/79
    New Contributors
    - @Lenouw made their first contribution in https://github.com/0xsline/OpenChatCut/pull/79
    Full Changelog: https://github.com/0xsline/OpenChatCut/compare/v0.2.3...v0.2.4
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/0xsline/OpenChatCut/releases/tag/v0.2.4
ReleaseTime: 2026-08-17T03:45:19.0000000Z
