Version: 3.4.0
Installer:
- Architecture: x64
  InstallerUrl: https://github.com/aliyun/aliyun-cli/releases/download/v3.4.0/aliyun-cli-windows-3.4.0-amd64.zip
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    What's Changed
    - feat(acrutil): extract shared binary manager and add diagnosis subcommand by @copyrightpoiiiii in https://github.com/aliyun/aliyun-cli/pull/1349
    - [feature] add rostran sub command by @xiao201208 in https://github.com/aliyun/aliyun-cli/pull/1350
    - Add --cli-dry-run-json by @AllyW in https://github.com/aliyun/aliyun-cli/pull/1306
    - Fix plugin three layer cmd help by @AllyW in https://github.com/aliyun/aliyun-cli/pull/1343
    - Feature/support anonymous by @yuexiu94 in https://github.com/aliyun/aliyun-cli/pull/1354
    - feat: support retry-after policy for throttling error by @yndu13 in https://github.com/aliyun/aliyun-cli/pull/1355
    New Contributors
    - @yuexiu94 made their first contribution in https://github.com/aliyun/aliyun-cli/pull/1354
    - @yndu13 made their first contribution in https://github.com/aliyun/aliyun-cli/pull/1355
    Full Changelog: https://github.com/aliyun/aliyun-cli/compare/v3.3.23...v3.4.0
- Key: ReleaseNotesUrl
  Value: https://github.com/aliyun/aliyun-cli/releases/tag/v3.4.0
ReleaseTime: 2026-06-23T10:07:51.0000000Z
