Version: 3.3.8
Installer:
- Architecture: x64
  InstallerUrl: https://github.com/aliyun/aliyun-cli/releases/download/v3.3.8/aliyun-cli-windows-3.3.8-amd64.zip
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    What's Changed
    - Add plugin install --package and plugin show by @AllyW in https://github.com/aliyun/aliyun-cli/pull/1301
    Full Changelog: https://github.com/aliyun/aliyun-cli/compare/v3.3.7...v3.3.8
- Key: ReleaseNotesUrl
  Value: https://github.com/aliyun/aliyun-cli/releases/tag/v3.3.8
ReleaseTime: 2026-04-17T09:15:19.0000000Z
