Version: 3.5.0
Installer:
- Architecture: x64
  InstallerUrl: https://github.com/aliyun/aliyun-cli/releases/download/v3.5.0/aliyun-cli-windows-3.5.0-amd64.zip
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    What's Changed
    - docs: add StsToken credential mode to README by @yndu13 in https://github.com/aliyun/aliyun-cli/pull/1403
    - Built-in plugin and AI MODE enhancement by @yndu13 in https://github.com/aliyun/aliyun-cli/pull/1411
    Full Changelog: https://github.com/aliyun/aliyun-cli/compare/v3.4.11...v3.5.0
- Key: ReleaseNotesUrl
  Value: https://github.com/aliyun/aliyun-cli/releases/tag/v3.5.0
ReleaseTime: 2026-09-07T04:03:52.0000000Z
