Version: 1.0.4.0
Installer:
- InstallerUrl: https://file.netpas.net/ftp/NetpasMessageSetup.exe
  InstallerSha256: 89D219C8026EFB9BED92511BBB5CA734EC5133EC2EC7A4EA4248B9E580D97913
Locale: []
RealVersion: "1.0"
ETag:
- '"6d9e8e8-6555b62ff7cb3"'
