Version: 1.0.4.8
Installer:
- InstallerUrl: https://file.netpas.net/ftp/NetpasMessageSetup.exe
  InstallerSha256: 37A4C80D812EAABE1D2DB2B1A0CEAB8F81D744C7AC26DA8DF8D57A89A36C90DB
Locale: []
RealVersion: "1.0"
ETag:
- '"701c900-65af51a790828"'
