Version: 3.9.24
Installer:
- Architecture: x86
  InstallerUrl: https://www.mediahuman.com/files/YouTubeDownloader.exe
  InstallerSha256: 68BA9DB383A369A604901B3D9B0EC15ADEA579078A2D4640D6255A012AD4E5BE
- Architecture: x64
  InstallerUrl: https://www.mediahuman.com/files/YouTubeDownloader-x64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - added support for W.tv
    - added support for Jamendo
    - added support for Zoom clips
    - fixed download from Audiomack
    - fixed download from TikTok, Instagram, Reddit and Bandcamp
    - fixed download from Apple Podcasts
    - fixed download of Twitch clips
    - fixed 2K and 4K quality for Vimeo
    - fixed a bug when only 480p was available for Bilibili videos
    - fixed download of large SoundCloud playlists
    - fixed YouTube playlists disappearing from the list without a message
    - fixed download of YouTube live streams that have just ended
    - fixed audio description being chosen instead of the original audio track
    - fixed 'Remove completed' removing videos that were not downloaded
    - fixed the sample rate setting not being saved
    - fixed downloads that slowed down and never recovered
    - fixed high memory usage and freezing with many parallel downloads
    - [win] fixed settings not being saved for users with a long download history
    - lots of improvements for YouTube
    - minor improvements for stability
LastModified: Fri, 09 Oct 2026 13:37:57 GMT
LastModifiedX64: Fri, 09 Oct 2026 13:37:44 GMT
ReleaseTime: 2026-10-02
