Version: 3.9.21
Installer:
- Architecture: x86
  InstallerUrl: https://www.mediahuman.com/files/YouTubeDownloader.exe
  InstallerSha256: 4875FACE409E60D08C539FE2AA6B1560E59632C7FDFE5765538BB7E528D65E0A
- Architecture: x64
  InstallerUrl: https://www.mediahuman.com/files/YouTubeDownloader-x64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - fixed extra unrelated videos being added from YouTube playlists
    - fixed download of large YouTube playlists (some stopped at 100 videos)
    - fixed download of Twitter/X GIFs
    - fixed 256 kbps audio for YouTube Music Premium
    - improved YouTube parsing speed for videos with many audio tracks
    - lots of improvements for YouTube
    - fixed download from VK (stays logged in, user and group pages)
    - fixed download from Twitch
    - fixed password-protected videos from Vimeo
    - fixed single-track downloads from Bandcamp
    - fixed download from SoundCloud
    - fixed audio quality for Bilibili (FLAC)
    - thumbnails are now saved in their original format
    - [win] fixed startup on systems with missing graphics libraries
    - fixed several crashes and improved download history reliability
    - minor improvements for stability
LastModified: Mon, 22 Jun 2026 17:05:17 GMT
LastModifiedX64: Mon, 22 Jun 2026 17:04:40 GMT
ReleaseTime: 2026-06-16
