Version: 3.9.24
Installer:
- Architecture: x86
  InstallerUrl: https://www.mediahuman.com/files/YouTubeDownloader.exe
  InstallerSha256: E9D674DC095D829AA4855647DC9CB067499782B13472E2A7C2CA66A3EE21A183
- Architecture: x64
  InstallerUrl: https://www.mediahuman.com/files/YouTubeDownloader-x64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - added support for W.tv
    - added support for Jamendo
    - added support for Zoom clips
    - fixed download from Audiomack
    - fixed download from TikTok, Instagram, Reddit and Bandcamp
    - fixed download from Apple Podcasts
    - fixed download of Twitch clips
    - fixed 2K and 4K quality for Vimeo
    - fixed a bug when only 480p was available for Bilibili videos
    - fixed download of large SoundCloud playlists
    - fixed YouTube playlists disappearing from the list without a message
    - fixed download of YouTube live streams that have just ended
    - fixed audio description being chosen instead of the original audio track
    - fixed 'Remove completed' removing videos that were not downloaded
    - fixed the sample rate setting not being saved
    - fixed downloads that slowed down and never recovered
    - fixed high memory usage and freezing with many parallel downloads
    - [win] fixed settings not being saved for users with a long download history
    - lots of improvements for YouTube
    - minor improvements for stability
LastModified: Sat, 03 Oct 2026 09:10:13 GMT
LastModifiedX64: Sat, 03 Oct 2026 09:10:01 GMT
ReleaseTime: 2026-10-02
