Version: 0.21.0
Installer:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/kawayiYokami/P-ai/releases/download/v0.21.0/P-ai_0.21.0_x64-setup.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: 'Full Changelog: https://github.com/kawayiYokami/P-ai/compare/v0.20.0...v0.21.0'
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/kawayiYokami/P-ai/releases/tag/v0.21.0
ReleaseTime: 2026-07-09T13:17:17.0000000Z
