Version: 0.18.8
Installer:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/kawayiYokami/P-ai/releases/download/v0.18.8/P-ai_0.18.8_x64-setup.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: 'Full Changelog: https://github.com/kawayiYokami/P-ai/compare/v0.18.6...v0.18.8'
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/kawayiYokami/P-ai/releases/tag/v0.18.8
ReleaseTime: 2026-07-06T12:23:44.0000000Z
