Version: 9.25.2
Installer:
- InstallerType: inno
  InstallerUrl: https://assets.alfaview.com/stable/win/alfaview-setup-win-production-9.25.2.exe
- InstallerType: wix
  InstallerUrl: https://assets.alfaview.com/stable/win/alfaview-setup-win-production-9.25.2.msi
Locale: []
ReleaseTime: 2026-03-06T15:19:34.0000000Z
