Version: 4.3.2606041540
Installer:
- InstallerUrl: https://github.com/workflowy/desktop/releases/download/v4.3.2606041540/WorkFlowy-Installer-4.3.2606041540.exe
Locale:
- Key: ReleaseNotesUrl
  Value: https://github.com/workflowy/desktop/releases/tag/v4.3.2606041540
ReleaseTime: 2026-06-04T16:49:22.0000000Z
