Version: 4.3.2607151451
Installer:
- InstallerUrl: https://github.com/workflowy/desktop/releases/download/v4.3.2607151451/WorkFlowy-Installer-4.3.2607151451.exe
Locale:
- Key: ReleaseNotesUrl
  Value: https://github.com/workflowy/desktop/releases/tag/v4.3.2607151451
ReleaseTime: 2026-07-15T16:39:38.0000000Z
