Version: 2.2.7
Installer:
- InstallerUrl: https://github.com/executordk/executor-community/releases/download/v2.2.7/ExecutorSetup_v2.2.7.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: Release v2.2.7 of Executor, check https://executor.dk/updates for release notes.
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/executordk/executor-community/releases/tag/v2.2.7
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Improvements
    - Added -skin list opens the list appearance wizard that sets list row properties (single/double, font, number of rows) and -skin of will open the folder of the current skin.
    - Added $PP$, $PPE$, $PP[x]$, $PPE[x]$, they are just like $PS$, $PSE$, $PS[x]$, $PSE[x]$ but will paste the text instead of typing it. Because these are using the clipboard to send text, they will only preserve the old clipboard if old clipboard contains text.
    - Now using a better visual algorithm for stretching background pictures.
    Fixes
    - Fixed a bug where a skin zip would not download properly resulting in an annoying error state.
    - Fixed that setting listtilepictureposition to cover or coverlist would not stretch properly when using High DPI.
    - Fixed $SENDTEXT2$ would sometimes paste the current clipboard text instead.
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://executor.dk/updates#v2207
ReleaseTime: 2026-03-16T21:20:06.0000000Z
