Version: 149.1.91.172
Installer:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.91.172/BraveBrowserStandaloneSilentSetup32.exe
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.91.172/BraveBrowserStandaloneSetup32.exe
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.91.172/BraveBrowserStandaloneSilentSetup.exe
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.91.172/BraveBrowserStandaloneSetup.exe
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.91.172/BraveBrowserStandaloneSilentSetupArm64.exe
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.91.172/BraveBrowserStandaloneSetupArm64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: '- Upgraded Chromium to 149.0.7827.115. (#56299) (Changelog for 149.0.7827.115)'
