Version: 8.2.6.16
Installer: []
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    优化升级
    「低熟练度地图 BUFF」优化与调整
    当玩家地图熟练度＞6 的地图数≥3 时，在排位中游玩熟练度≤6 的地图时，会获得「低熟练地图 BUFF」；
    *「低熟练地图 BUFF」调整为：胜利时获得 25%额外加分，失利时获得 50%扣分减免；
    玩家可以通过【房间内-选图界面-地图熟练度等级】旁的紫色闪电图标来确定 BUFF 是否生效。
