Version: 8.2.6.19
Installer: []
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    5E 新鲜事
    图池轮换
    优先排位的图池即将迎来轮换
    投票选图&地图 BP：Cache 将取代 Overpass；
    自由选图：Overpass 下线。

    优化升级
    反作弊优化
    优化了反作弊进程的处理器占用，提升整体稳定性与流畅度。
    针对市面上出现的新型外挂，新增检测类目，包括但不限于透视、自瞄类作弊程序。
