Version: 8.2.7.3
Installer: []
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    5E 新鲜事
    实战身法训练地图上线
    5E 最新一站式身法训练地图，提供 3 种不同模式的跳跃练习。
    方便玩家提高实战身法，熟练地图跳跃点位。

    福利回馈
    饰品驿站消费礼赠
    即日起，在饰品驿站实付到达 10 元即可领取专属装扮～
