Version: "12.55"
Installer:
- Architecture: x86
  InstallerUrl: https://www.softwareok.com/Download/Q-Dir_Installer.zip
- Architecture: x64
  InstallerUrl: https://www.softwareok.com/Download/Q-Dir_Installer_x64.zip
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - General improvements to Quad File Explorer for all Windows operating systems
    - Optimized usability and improved operation for greater convenience.
    - New option: Close button for tabs
    - Tabs can now be closed directly using a visible close button.
    - Activate under: Menu - Tools - Tabs - Show Close Button
ReleaseTime: 2026-03-28
