Version: 2.2.7
Installer:
- InstallerUrl: https://pixso-pub-prod.obs.cn-east-3.myhuaweicloud.com/cms/download/package/app/bosyun/2.2.7/Pixso_win_v2_2_7.exe
Locale: []
ReleaseTime: 2026-05-07T02:49:27.5930000Z
