Version: 1.14.0.3
Installer:
- InstallerUrl: https://github.com/leezer3/OpenBVE/releases/download/1.14.0.3/openBVE-1.14.0.3-setup.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Significant Changes:
    - Fix: Build failing to launch on non-windows platforms- It appears that there has been a change with Azure pipelines, causing a required file to not be copied into the build correctly.
    - Fix: A file with the timetable override texture set did not preserve this when cloned.
    - Change: Support for several more animations in MSTS cabs.
- Key: ReleaseNotesUrl
  Value: https://github.com/leezer3/OpenBVE/releases/tag/1.14.0.3
ReleaseTime: 2026-08-10T16:01:17.0000000Z
