Version: 19.6.0
Installer:
- InstallerUrl: https://files2.codecguide.com/K-Lite_Codec_Pack_1960_Mega.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - Updated MPC-HC to version 2.6.4.0
    - Updated LAV Filters to version 0.81-7-g8c4ee
    - Updated GraphStudioNext to version 0.7.3.12
ReleaseTime: 2026-03-19
