Version: 2026.4.24
Installer:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/netease-youdao/LobsterAI/releases/download/2026.4.24/LobsterAI--win-x64.exe
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    What's Changed
    - feat(providers): add deepseek-v4-flash and deepseek-v4-pro model by @liuzhq1986 in https://github.com/netease-youdao/LobsterAI/pull/1812
    -  - fix(skills,mcp): trim and normalize search query whitespace, add clear button by @liuzhq1986 in https://github.com/netease-youdao/LobsterAI/pull/1811
    Full Changelog: https://github.com/netease-youdao/LobsterAI/compare/2026.4.23...2026.4.24
- Locale: zh-CN
  Key: ReleaseNotesUrl
  Value: https://github.com/netease-youdao/LobsterAI/releases/tag/2026.4.24
ReleaseTime: 2026-04-24T13:32:26.0000000Z
