Version: 0.2.4
Installer:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/netease-youdao/LobsterAI/releases/download/v0.2.4/LobsterAI--win-x64.exe
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    What's Changed
    - fix: 修复 IM 渠道连接性测试引起的 bug by @fisherdaddy in https://github.com/netease-youdao/LobsterAI/pull/393
    - fix：修复应用启动时一直处于加载状态的问题 by @fisherdaddy in https://github.com/netease-youdao/LobsterAI/pull/396
    Full Changelog: https://github.com/netease-youdao/LobsterAI/compare/v0.2.3...v0.2.4
- Locale: zh-CN
  Key: ReleaseNotesUrl
  Value: https://github.com/netease-youdao/LobsterAI/releases/tag/v0.2.4
ReleaseTime: 2026-03-12T17:01:48.0000000Z
