Version: 1.17.20
Installer:
- Architecture: x64
  InstallerUrl: https://github.com/anomalyco/opencode/releases/download/v1.17.20/opencode-windows-x64.zip
- Architecture: arm64
  InstallerUrl: https://github.com/anomalyco/opencode/releases/download/v1.17.20/opencode-windows-arm64.zip
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Core
    Bugfixes
    - Removed an obsolete Codex workaround that could interfere with OpenAI Luna Responses Lite requests.
    Improvements
    - Updated Azure AI support for GPT-5.6.
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/anomalyco/opencode/releases/tag/v1.17.20
ReleaseTime: 2026-07-13T21:09:56.0000000Z
