Version: 1.57.1
Installer:
- Architecture: x86
  InstallerUrl: https://macc.max-c.com/chat/pc/chat_installer_new_1.57.1.1538.exe
- Architecture: x64
  InstallerUrl: https://macc.max-c.com/chat/pc/chat_installer_x64_new_1.57.1.1537.exe
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: '- 修复已知问题'
ReleaseTime: 2026-09-11T10:23:58.0000000Z
