Version: 0.8.36
Installer:
- Architecture: x64
  InstallerType: portable
  InstallerUrl: https://github.com/Hmbown/DeepSeek-TUI/releases/download/v0.8.36/deepseek-tui-windows-x64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/Hmbown/DeepSeek-TUI/releases/tag/v0.8.36
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/Hmbown/DeepSeek-TUI/blob/HEAD/CHANGELOG.md
ReleaseTime: 2026-05-14T06:10:17.0000000Z
