Version: 0.5.2
Installer:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://downloads.withcapsule.app/v0.5.2/Capsule_0.5.2_x64-setup.exe
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://downloads.withcapsule.app/v0.5.2/Capsule_0.5.2_x64_en-US.msi
Locale: []
ReleaseTime: 2026-09-15T22:05:01.3480000Z
