Version: 6.0.1.6847
Installer:
- Architecture: x64
  InstallerType: burn
  InstallerUrl: https://updates.ilok.com/iloklicensemanager/LicenseSupportInstallerWinUpdate.exe
Locale:
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://updates.ilok.com/iloklicensemanager/LicenseSupportInstallerWinReleaseNotes.html
- Locale: en-US
  Key: ReleaseNotes
  Value: '[Fixed] iLok License Manager properly restores window sizing when relaunched.'
ReleaseTime: 2026-08-25T17:25:05.0000000Z
