Version: 2026.3.5.0
Installer:
- InstallerUrl: https://cdn.devolutions.net/download/Setup.DVLS.Console.2026.3.5.0.exe
Locale:
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://devolutions.net/server/release-notes/console/
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Fixes
    - Fixed a "Could not apply least permissions" error when updating a server instance
    - Fixed an error when editing and saving a Kestrel instance in maintenance mode
    - Fixed an upgrade removing the scheduler account's permissions on the encryption configuration file
    - Fixed duplicate Light and Dark theme options under Support > Options > Theme
    - Fixed server instance changes made from the Console not being saved
    - Fixed the command-line interface crashing when upgrading a server instance
    - Fixed upgrades removing the scheduler account's permission to access the encryption configuration file
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://devolutions.net/server/release-notes/console/#v2026.3.5
ReleaseTime: 2026-09-15
