Version: 7.10.3
Installer:
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://prod-sup-5683567dcbd60804cb34.s3.amazonaws.com/Frame+App/7.10.3/win32/x64/Frame.msi
  ProductCode: '{793EB0F7-3A74-4EC2-8609-2F1D19088165}.msq'
Locale: []
