Version: 153.0.4234.32
Installer:
- Architecture: x86
  InstallerUrl: https://msedgedriver.microsoft.com/153.0.4234.32/edgedriver_win32.zip
- Architecture: x64
  InstallerUrl: https://msedgedriver.microsoft.com/153.0.4234.32/edgedriver_win64.zip
- Architecture: arm64
  InstallerUrl: https://msedgedriver.microsoft.com/153.0.4234.32/edgedriver_arm64.zip
Locale: []
