Version: 1.12.29
Installer:
- Architecture: x64
  InstallerUrl: https://packages.element.io/desktop/install/win32/x64/Element Setup 1.12.29.exe
- Architecture: arm64
  InstallerUrl: https://packages.element.io/desktop/install/win32/arm64/Element Setup 1.12.29.exe
Locale:
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/element-hq/element-web/releases
- Locale: en-US
  Key: ReleaseNotes
  Value: Update modules in element-web modules Docker image
- Key: ReleaseNotesUrl
  Value: https://github.com/element-hq/element-web/releases/tag/v1.12.29
ReleaseTime: 2026-09-22T12:51:06.0000000Z
