Version: 9.1.2
Installer:
- InstallerUrl: https://builds.opentrons.com/app/Opentrons-v9.1.2-win-b72984.exe
Locale:
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/Opentrons/opentrons/blob/HEAD/app-shell/build/release-notes.md
- Locale: en-US
  Key: ReleaseNotes
  Value: Welcome to the v9.1.2 release of the Opentrons App! This release resolves a bug to prevent the Flex touchscreen from freezing while selecting runtime parameters for a protocol run.
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/Opentrons/opentrons/blob/HEAD/app-shell/build/release-notes.md#opentrons-app-changes-in-912
ReleaseTime: 2026-08-10T18:53:41.2790000Z
