Version: 1.25.16
Installer:
- InstallerType: nullsoft
  InstallerUrl: https://github.com/codedev-david/termpolis/releases/download/v1.25.16/Termpolis.Setup.1.25.16.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Full Changelog: https://github.com/codedev-david/termpolis/compare/v1.25.15...v1.25.16
    Full Changelog: https://github.com/codedev-david/termpolis/compare/v1.25.15...v1.25.16
    Full Changelog: https://github.com/codedev-david/termpolis/compare/v1.25.15...v1.25.16
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/codedev-david/termpolis/releases/tag/v1.25.16
ReleaseTime: 2026-07-14T06:01:41.0000000Z
