Version: 1.29.0
Installer:
- InstallerType: nullsoft
  InstallerUrl: https://github.com/codedev-david/termpolis/releases/download/v1.29.0/Termpolis.Setup.1.29.0.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Full Changelog: https://github.com/codedev-david/termpolis/compare/v1.28.1...v1.29.0
    Full Changelog: https://github.com/codedev-david/termpolis/compare/v1.28.1...v1.29.0
    Full Changelog: https://github.com/codedev-david/termpolis/compare/v1.28.1...v1.29.0
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/codedev-david/termpolis/releases/tag/v1.29.0
ReleaseTime: 2026-07-20T04:57:19.0000000Z
