Version: 1.12.1
Installer:
- InstallerType: nullsoft
  InstallerUrl: https://github.com/codedev-david/termpolis/releases/download/v1.12.1/Termpolis.Setup.1.12.1.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Full Changelog: https://github.com/codedev-david/termpolis/compare/v1.12.0...v1.12.1
    Full Changelog: https://github.com/codedev-david/termpolis/compare/v1.12.0...v1.12.1
    Full Changelog: https://github.com/codedev-david/termpolis/compare/v1.12.0...v1.12.1
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/codedev-david/termpolis/releases/tag/v1.12.1
ReleaseTime: 2026-06-12T00:30:16.0000000Z
