Version: 1.48.0
Installer:
- InstallerType: nullsoft
  InstallerUrl: https://github.com/codedev-david/termpolis/releases/download/v1.48.0/Termpolis.Setup.1.48.0.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: 'Full Changelog: https://github.com/codedev-david/termpolis/compare/v1.47.4...v1.48.0'
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/codedev-david/termpolis/releases/tag/v1.48.0
ReleaseTime: 2026-09-26T09:48:00.0000000Z
