Version: 15.3.20
Installer:
- InstallerUrl: https://cc-download.wondershare.cc/cbs_down/filmora_15.3.20_full13770.exe
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: 修复软件错误，改善用户体验。
RealVersion: 15.3.20.18661
