Version: 2026-03-13
Installer:
- Architecture: x64
  InstallerUrl: https://github.com/servo/servo-nightly-builds/releases/download/2026-03-13/servo-x86_64-windows-msvc.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: Nightly build based on servo/servo@1a88675636ea0e7f44eed9b88032b71f45ed9691
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/servo/servo-nightly-builds/releases/tag/2026-03-13
ReleaseTime: 2026-03-13T23:20:08.0000000Z
RealVersion: "1.0"
