Version: 2026-04-30
Installer:
- Architecture: x64
  InstallerUrl: https://github.com/servo/servo-nightly-builds/releases/download/2026-04-30/servo-x86_64-windows-msvc.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: Nightly build based on servo/servo@dfd588563f58b02e4ae33cd04f038aa8df91820c
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/servo/servo-nightly-builds/releases/tag/2026-04-30
ReleaseTime: 2026-04-30T23:26:34.0000000Z
RealVersion: "1.0"
