Version: 2026-09-03
Installer:
- Architecture: x64
  InstallerUrl: https://github.com/servo/servo-nightly-builds/releases/download/2026-09-03/servo-x86_64-windows-msvc.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: Nightly build based on servo/servo@00fefedadac0b206720fbad8f48271b38605e269
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/servo/servo-nightly-builds/releases/tag/2026-09-03
ReleaseTime: 2026-09-03T23:23:13.0000000Z
RealVersion: "1.0"
