Version: 2026-07-07
Installer:
- Architecture: x64
  InstallerUrl: https://github.com/servo/servo-nightly-builds/releases/download/2026-07-07/servo-x86_64-windows-msvc.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: Nightly build based on servo/servo@b69c4c286b3e1b1944fb0d03ecd557d26a67db7f
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/servo/servo-nightly-builds/releases/tag/2026-07-07
ReleaseTime: 2026-07-07T23:49:03.0000000Z
RealVersion: "1.0"
