Version: 2.11.1
Installer:
- Architecture: x64
  InstallerUrl: https://github.com/viarotel-org/escrcpy/releases/download/v2.11.1/Escrcpy-2.11.1-win-setup-x64.exe
- Architecture: arm64
  InstallerUrl: https://github.com/viarotel-org/escrcpy/releases/download/v2.11.1/Escrcpy-2.11.1-win-setup-arm64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Features
    - ⚡️ Optimizations for enabling device application interaction include adding display presets
    - 🚀 Update to scrcpy 4.0
    Bug Fixes
    - keyboard: align click hold behavior and improve view control
    - 🐛 Fixed the issue where mouse mapping cannot be triggered simultaneously when multiple components exist
    Performance Improvements
    - 🚀 Solve the problem that binary dependency caching may cause program anomalies after version upgrades
    Code Refactoring
    - ➖ Remove redundant code
    - 👷 Optimize the preference interactive experience
    - 🚀 Reconstruct the keyboard mapping module lifecycle skeleton to improve scalability
    - ➖ Removed redundant option for keyboard mapping perspective control
    - 🚀 Keyboard mapping and viewing angle control function reconstruction and optimization
    - 🚀 Update the sorting of dependency imports
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/viarotel-org/escrcpy/releases/tag/v2.11.1
ReleaseTime: 2026-05-19T07:48:59.0000000Z
