Version: 2.7.3
Installer:
- Architecture: x64
  InstallerUrl: https://github.com/viarotel-org/escrcpy/releases/download/v2.7.3/Escrcpy-2.7.3-win-setup-x64.exe
- Architecture: arm64
  InstallerUrl: https://github.com/viarotel-org/escrcpy/releases/download/v2.7.3/Escrcpy-2.7.3-win-setup-arm64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Bug Fixes
    - 🐛 Fixed an issue where embedded mirroring could not be input due to external activation elements. (058b982)
    Performance Improvements
    - 🚀 Optimize the embedded image to open the application list display (7f6b18a)
    Code Refactoring
    - 🔊 Optimize the wscrcpy audio cleaning logic (a29cd85)
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/viarotel-org/escrcpy/releases/tag/v2.7.3
ReleaseTime: 2026-04-02T06:38:04.0000000Z
