Version: 1.0.151
Installer:
- Architecture: x64
  InstallerType: portable
  InstallerUrl: https://github.com/iOfficeAI/OfficeCLI/releases/download/v1.0.151/officecli-win-x64.exe
- Architecture: arm64
  InstallerType: portable
  InstallerUrl: https://github.com/iOfficeAI/OfficeCLI/releases/download/v1.0.151/officecli-win-arm64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: 'Full Changelog: https://github.com/iOfficeAI/OfficeCLI/compare/v1.0.150...v1.0.151'
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/iOfficeAI/OfficeCLI/releases/tag/v1.0.151
ReleaseTime: 2026-09-16T18:19:55.0000000Z
