Version: 1.0.112
Installer:
- Architecture: x64
  InstallerType: portable
  InstallerUrl: https://github.com/iOfficeAI/OfficeCLI/releases/download/v1.0.112/officecli-win-x64.exe
- Architecture: arm64
  InstallerType: portable
  InstallerUrl: https://github.com/iOfficeAI/OfficeCLI/releases/download/v1.0.112/officecli-win-arm64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: 'Full Changelog: https://github.com/iOfficeAI/OfficeCLI/compare/v1.0.111...v1.0.112'
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/iOfficeAI/OfficeCLI/releases/tag/v1.0.112
ReleaseTime: 2026-06-13T14:56:01.0000000Z
