Version: 1.0.136
Installer:
- Architecture: x64
  InstallerType: portable
  InstallerUrl: https://github.com/iOfficeAI/OfficeCLI/releases/download/v1.0.136/officecli-win-x64.exe
- Architecture: arm64
  InstallerType: portable
  InstallerUrl: https://github.com/iOfficeAI/OfficeCLI/releases/download/v1.0.136/officecli-win-arm64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    What's Changed
    - fix(xlsx) Caching of formats, fonts, fills and borders on Excel rendering by @andulv in https://github.com/iOfficeAI/OfficeCLI/pull/190
    - 修正 DOCX skill 的分页和 TOC 指引 by @eric8810 in https://github.com/iOfficeAI/OfficeCLI/pull/193
    New Contributors
    - @andulv made their first contribution in https://github.com/iOfficeAI/OfficeCLI/pull/190
    - @eric8810 made their first contribution in https://github.com/iOfficeAI/OfficeCLI/pull/193
    Full Changelog: https://github.com/iOfficeAI/OfficeCLI/compare/v1.0.135...v1.0.136
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/iOfficeAI/OfficeCLI/releases/tag/v1.0.136
ReleaseTime: 2026-07-14T04:02:28.0000000Z
