Version: 2.0.7
Installer:
- Architecture: x64
  InstallerUrl: https://github.com/raspberrypi/rpi-imager/releases/download/v2.0.7/imager-v2.0.7.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    What's Changed
    - chore(release): v2.0.6 by @tdewey-rpi in https://github.com/raspberrypi/rpi-imager/pull/1477
    - feat(installer): Add windows installer dark mode support in rpi-imager.iss.in by @rc-chuah in https://github.com/raspberrypi/rpi-imager/pull/1480
    - fix(main): Add warning for log paths that are too long by @Ferdinaelectro1 in https://github.com/raspberrypi/rpi-imager/pull/1481
    - Add pt-br translation by @eduardoaddad in https://github.com/raspberrypi/rpi-imager/pull/1490
    - Update Turkish translations by @Sype0 in https://github.com/raspberrypi/rpi-imager/pull/1488
    - Added documentation clarifying the interaction between old versions of Imager and new versions of RPi OS by @lurch in https://github.com/raspberrypi/rpi-imager/pull/1497
    - Fix malformed rpi-imager_pt-BR.ts by @lurch in https://github.com/raspberrypi/rpi-imager/pull/1499
    - Move the development instructions to a separate CONTRIBUTING.md file by @lurch in https://github.com/raspberrypi/rpi-imager/pull/1508
    - QML: fix property name mismatch in ImFileDialog by @wallentx in https://github.com/raspberrypi/rpi-imager/pull/1505
    - 2.0.7: Remove legacy mountutils/drivelist, bugfixes by @tdewey-rpi in https://github.com/raspberrypi/rpi-imager/pull/1513
    - fix(debian): Add missing GUI library dependencies by @tdewey-rpi in https://github.com/raspberrypi/rpi-imager/pull/1517
    - 2.0.7: Improved combobox search, HK & Macau added, don't store experimental options by @tdewey-rpi in https://github.com/raspberrypi/rpi-imager/pull/1525
    - 2.0.7: Remove BLKDISCARD, gzip progress bars by @tdewey-rpi in https://github.com/raspberrypi/rpi-imager/pull/1528
    - Add "Clear saved customisation" button to App Options by @4RH1T3CT0R7 in https://github.com/raspberrypi/rpi-imager/pull/1501
    - fix(cloud-init): Make instance-id durable across reboots by @tdewey-rpi in https://github.com/raspberrypi/rpi-imager/pull/1529
    - fix(capital-cities): Update capital city entries and handling for Hong Kong by @tdewey-rpi in https://github.com/raspberrypi/rpi-imager/pull/1531
    - fix(ImFileDialog): allow typing/pasting full file paths in open mode by @4RH1T3CT0R7 in https://github.com/raspberrypi/rpi-imager/pull/1530
    - fix(ImComboBox): use PlatformHelper for scroll direction in closed ComboBox by @4RH1T3CT0R7 in https://github.com/raspberrypi/rpi-imager/pull/1534
    - Fix compile erorr in platformquirks_linux.cpp by @lurch in https://github.com/raspberrypi/rpi-imager/pull/1537
    - fix(beep): bundle fallback chime for Linux distros without freedesktop sounds by @4RH1T3CT0R7 in https://github.com/raspberrypi/rpi-imager/pull/1535
    - fix(polkit): use /etc/polkit-1/actions for policy on immutable distros by @4RH1T3CT0R7 in https://github.com/raspberrypi/rpi-imager/pull/1536
    - fix(wifi): prevent stale WiFi settings from being applied after Skip by @4RH1T3CT0R7 in https://github.com/raspberrypi/rpi-imager/pull/1540
    - 2.0.7 rollup 2: Fastboot, rpiboot, compute modules, text scaling, proxy support by @tdewey-rpi in https://github.com/raspberrypi/rpi-imager/pull/1548
    - fix(i18n): add missing French translations for saved customisation settings by @Ferdinaelectro1 in https://github.com/raspberrypi/rpi-imager/pull/1555
    - chore(.gitignore) : add .idea to .gitignore by @Ferdinaelectro1 in https://github.com/raspberrypi/rpi-imager/pull/1552
    - i18n: complete zh-CN translation by @ykla in https://github.com/raspberrypi/rpi-imager/pull/1554
    New Contributors
    - @rc-chuah made their first contribution in https://github.com/raspberrypi/rpi-imager/pull/1480
    - @Ferdinaelectro1 made their first contribution in https://github.com/raspberrypi/rpi-imager/pull/1481
    - @eduardoaddad made their first contribution in https://github.com/raspberrypi/rpi-imager/pull/1490
    - @Sype0 made their first contribution in https://github.com/raspberrypi/rpi-imager/pull/1488
    - @wallentx made their first contribution in https://github.com/raspberrypi/rpi-imager/pull/1505
    - @4RH1T3CT0R7 made their first contribution in https://github.com/raspberrypi/rpi-imager/pull/1501
    Full Changelog: https://github.com/raspberrypi/rpi-imager/compare/v2.0.6...v2.0.7
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/raspberrypi/rpi-imager/releases/tag/v2.0.7
ReleaseTime: 2026-03-26T12:06:00.0000000Z
