Version: 0.10.2
Installer:
- Architecture: x64
  InstallerUrl: https://github.com/devmatteini/dra/releases/download/0.10.2/dra-0.10.2-x86_64-pc-windows-msvc.zip
  NestedInstallerFiles:
  - RelativeFilePath: dra-0.10.2-x86_64-pc-windows-msvc\dra.exe
    PortableCommandAlias: dra
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Fixed
    - Install feature detects macOS specific executables properly when they are released as
      assets without an archive (#351)
    Updated dependencies
    - bump uuid from 1.18.1 to 1.19.0
    - bump clap_complete from 4.5.61 to 4.5.64
- Key: ReleaseNotesUrl
  Value: https://github.com/devmatteini/dra/releases/tag/0.10.2
ReleaseTime: 2026-05-28T21:55:28.0000000Z
