Version: 7.64.6
Installer:
- Architecture: x86
  InstallerUrl: https://sf3-cn.feishucdn.com/obj/hera-cn/download/Feishu-win32_ia32-7.64.6-signed.msi
- Architecture: x64
  InstallerUrl: https://sf3-cn.feishucdn.com/obj/hera-cn/download/Feishu-win32_x64-7.64.6-signed.msi
Locale:
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://www.feishu.cn/hc/en-US/articles/360043073734
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Base
    - If chart interactions are configured, you can select a data point in one chart to dynamically filter linked charts within the same dashboard for deeper, real-time analysis directly from the mobile app.
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://www.feishu.cn/hc/en-US/articles/898397785592
- Locale: zh-CN
  Key: ReleaseNotesUrl
  Value: https://www.feishu.cn/hc/zh-CN/articles/360043073734
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    多维表格
    - 飞书移动端也可以使用仪表盘图表联动功能了。如果仪表盘已配置图表联动，在移动端，你可以在一个图表上选择数据范围，动态筛选同一仪表盘上关联图表中的数据，实现多图表联动分析。
- Locale: zh-CN
  Key: ReleaseNotesUrl
  Value: https://www.feishu.cn/hc/zh-CN/articles/898397785592
RealVersion: 7.64.0.0
