Version: 8.2.0
Installer:
- InstallerUrl: https://downloads.getfiddler.com/win/Fiddler Everywhere 8.2.0.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    New
    - Added scripting functionality.
    - Added host remapping functionality.

    Fixed
    - Warning for unsaved filter appears in Snapshots when closing the application.
    - Fixed CVE-2026-86158: Missing Authentication in the local .NET backend of Progress Telerik Fiddler Everywhere.
    - Fixed CVE-2026-86157: Exposure of Privileged IPC Functionality in Progress Telerik Fiddler Everywhere.
    - Updated third-party dependencies to address potential security vulnerabilities.
ReleaseTime: 2026-09-25T06:36:54.8610000Z
