Version: 2.5.0
Installer:
- InstallerUrl: https://github.com/dev47apps/droidcam-obs-plugin/releases/download/2.5.0/DroidCamOBS.Setup.2.5.0.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - Added the HEVC/H.265 video format.
      - Unlocks 60fps at 4K.
      - Option to capture 10-bit HDR video, if supported by phone.
      - Requires the latest phone apps (v9.0 or above).
    - Added an option to disable "unbuffered" mode.
      - Allows for smoother video, at the cost of some latency.
      - Can be useful if WiFi signal is not perfect or when router/phone/PC are further apart.
      - Until now, DroidCam was hard-coded in unbuffered mode for near zero latency, which could sometimes result in jittery output.
    Home page: droidcam.app/obs
    HDR Guide: https://droidcam.app/obs/hdr
    Tip: click [Watch] on this GitHub repository to get notified about new releases.
    DroidCamOBS.Setup.2.5.0.exe (Windows 10+ (x64, arm64), OBS v32+)
    DroidCamOBS_2.5.0_macos.pkg (macOS 10.13+ (x64, arm64), OBS v32+)
    droidcam_obs_2.5.0_linux_x86_64.zip (Linux systems with FFmpeg7/libavcodec61 (x64))
- Key: ReleaseNotesUrl
  Value: https://github.com/dev47apps/droidcam-obs-plugin/releases/tag/2.5.0
ReleaseTime: 2026-04-27T22:24:32.0000000Z
