Version: "8.66"
Installer:
- Architecture: x86
  InstallerUrl: https://www.softwareok.com/Download/MeinPlatz_Installer.zip
- Architecture: x64
  InstallerUrl: https://www.softwareok.com/Download/MeinPlatz_Installer_x64.zip
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - New: Right-click option to open file properties and the target file path for shortcuts.
    - Updated MeinPlatz language files.
ReleaseTime: 2026-05-22
