Version: "9.0"
Installer:
- InstallerUrl: https://www.arixcel.com/download/Arixcel_Explorer_v9.0.9623.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - Enhanced support for array formulas - exploring individual array cells
    - Minor fixes
RealVersion: 9.0.9623.19616
