Version: "2026.1"
Installer:
- Architecture: x64
  InstallerUrl: https://download.jetbrains.com/mps/2026.1/MPS-2026.1.exe
  ProductCode: JetBrains MPS 2026.1
  AppsAndFeaturesEntries:
  - DisplayVersion: MPS-261.25134.779
  InstallerSha256: CD6BB9CCF515B031606309BA305FDD3FF152EA288F0E4711CC49CD7B26CEB785
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: If you want to learn more, please check our issue tracker.
- Key: ReleaseNotesUrl
  Value: https://www.jetbrains.com/mps/whatsnew/
ReleaseTime: 2026-07-14
