Version: 6.1.2
Installer:
- InstallerType: nullsoft
  InstallerUrl: https://github.com/beekeeper-studio/beekeeper-studio/releases/download/v6.1.2/Beekeeper-Studio-Setup-6.1.2.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    fix: read only mode is not saved by @andreasarf in https://github.com/beekeeper-studio/beekeeper-studio/pull/4769
    Full Changelog: https://github.com/beekeeper-studio/beekeeper-studio/compare/v6.1.1...v6.1.2
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/beekeeper-studio/beekeeper-studio/releases/tag/v6.1.2
ReleaseTime: 2026-09-17T23:10:01.0000000Z
