Version: 1.2.21.2402
Installer:
- InstallerUrl: https://github.com/KaringX/karing/releases/download/v1.2.21.2402/karing_1.2.21.2402_windows_x64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    1. Fixes some WebDAV 405 connection failure issues. #1670
    IOS/TvOS AppStore: (Search Keywords: karing vpn) https://apps.apple.com/us/app/karing/id6472431552
- Key: ReleaseNotesUrl
  Value: https://github.com/KaringX/karing/releases/tag/v1.2.21.2402
RealVersion: 1.2.21+2402
ReleaseTime: 2026-06-28T03:47:32.0000000Z
