Version: 0.4.5-runtime.725eb2f40749
Installer:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/wecode-ai/Wegent/releases/download/wework-v0.4.5-runtime.725eb2f40749/WeWorkHostUpdate_0.4.5_windows_x64-setup.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: '- Revert "feat(wework): reuse TaskToken for plugin remote MCP identity (#3433)" by @qdaxb in #3451'
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/wecode-ai/Wegent/releases/tag/wework-v0.4.5-runtime.725eb2f40749
ReleaseTime: 2026-09-11T15:17:04.0000000Z
