Version: 0.5.34
Installer:
- Architecture: x86
  InstallerType: nullsoft
  InstallerUrl: https://github.com/KangLin/SerialPortAssistant/releases/download/v0.5.34/SerialPortAssistant_v0.5.34_win32_msvc2019_qt5.15.2_Setup.exe
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/KangLin/SerialPortAssistant/releases/download/v0.5.34/SerialPortAssistant_v0.5.34_win64_msvc2022_64_qt6.10.3_Setup.exe
- Architecture: arm64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/KangLin/SerialPortAssistant/releases/download/v0.5.34/SerialPortAssistant_v0.5.34_win64_msvc2022_arm64_qt6.10.3_Setup.exe
Locale:
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/KangLin/SerialPortAssistant/blob/HEAD/ChangeLog.md
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - CI:
      - add snap
      - add rpm
      - add flatpak
    - Android:
      - add menu to toolbar
      - Fix language bug
      - Use cmake to generate AndroidManifest.xml, remove AndroidManifest.xml
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/KangLin/SerialPortAssistant/blob/HEAD/ChangeLog.md#version-v0534-dev
- Locale: zh-CN
  Key: ReleaseNotesUrl
  Value: https://github.com/KangLin/SerialPortAssistant/blob/HEAD/ChangeLog_zh_CN.md
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    - CI:
      - 增加 snap
      - 增加 rpm
      - 增加 flatpak
    - Android
      - 增加菜单到工具栏上
      - 修改多语言错误
      - 使用 cmake 生成 AndroidManifest.xml， 移除 AndroidManifest.xml
- Locale: zh-CN
  Key: ReleaseNotesUrl
  Value: https://github.com/KangLin/SerialPortAssistant/blob/HEAD/ChangeLog.md#-v0534-dev
ReleaseTime: 2026-08-10T02:57:27.0000000Z
