Version: 20.2.0
Installer:
- InstallerUrl: https://github.com/ShareX/ShareX/releases/download/v20.2.0/ShareX-20.2.0-setup-x64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - Image editor improvements:
      - Added "I Image" annotation tool.
      - Added new arrow styles:
        - Double
        - Basic
        - Line
      - Added previews for arrow styles.
      - Added "Starting number" option to "Step" annotation tool.
      - Added "Ctrl + Shift + P Print image" button to the bottom toolbar.
      - Drawing can now start outside the canvas and continue inside it.
      - Added "Options" button to "File" menu with the following settings:
        - Follow system theme
        - Theme
        - Follow system accent color
        - Accent color
        - Remember window state
        - Show exit confirmation
        - Zoom to fit on open
        - Quick crop
        - Auto close editor on task
        - Auto copy image to clipboard
        - Show insert image dialog
      - Removed "Task settings -> Tools -> Image editor" tab, since these options are now available directly inside the image editor.
      - Moved "Use legacy image editor" option to "Task settings -> Tools" tab.
      - Added support for panning the canvas with Middle click while drawing or cropping, making it easier to work with areas larger than the screen.
      - The insert image dialog now places images at the center of the currently visible area instead of the center of the canvas.
    - Update FFmpeg to 8.1.
ReleaseTime: 2026-05-22T05:03:33.0000000Z
