Version: 26.3.2012
Installer:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://app.ringcentral.com/download/RingCentral-26.3.2012.exe
- Architecture: arm64
  InstallerType: nullsoft
  InstallerUrl: https://app.ringcentral.com/download/RingCentral-26.3.2012-arm64.exe
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://app.ringcentral.com/download/RingCentral-26.3.2012-x64.msi
- Architecture: arm64
  InstallerType: wix
  InstallerUrl: https://app.ringcentral.com/download/RingCentral-26.3.2012-arm64.msi
Locale: []
ReleaseTime: 2026-08-24T15:18:13.9490000Z
