Version: 1.22.8.0
Installer:
- Architecture: x86
  InstallerUrl: https://julialang-s3.julialang.org/juliaup/winappinstaller/Julia-x86-1.22.8.0.appx
- Architecture: x64
  InstallerUrl: https://julialang-s3.julialang.org/juliaup/winappinstaller/Julia-x64-1.22.8.0.appx
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    What's Changed
    - ci: run FreeBSD steps through the cpa.sh custom shell by @IanButterworth in https://github.com/JuliaLang/juliaup/pull/1598
    - juliaupgui: route gc and other status output into the GUI log by @IanButterworth in https://github.com/JuliaLang/juliaup/pull/1602
    - chore(deps): bump the cargo-dependencies group with 5 updates by @dependabot[bot] in https://github.com/JuliaLang/juliaup/pull/1606
    Full Changelog: https://github.com/JuliaLang/juliaup/compare/v1.22.7...v1.22.8
- Key: ReleaseNotesUrl
  Value: https://github.com/JuliaLang/juliaup/releases/tag/v1.22.8
ReleaseTime: 2026-09-19T03:24:28.0000000Z
