Version: 1.22.6.0
Installer:
- Architecture: x86
  InstallerUrl: https://julialang-s3.julialang.org/juliaup/winappinstaller/Julia-x86-1.22.6.0.appx
- Architecture: x64
  InstallerUrl: https://julialang-s3.julialang.org/juliaup/winappinstaller/Julia-x64-1.22.6.0.appx
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    What's Changed
    - avoid updating nightly and PR channels on self update by @KristofferC in https://github.com/JuliaLang/juliaup/pull/1585
    - Download a version only once when several channels update to it by @KristofferC in https://github.com/JuliaLang/juliaup/pull/1589
    - chore(deps): bump the github-actions group across 1 directory with 3 updates by @dependabot[bot] in https://github.com/JuliaLang/juliaup/pull/1586
    - chore(deps): bump the cargo-dependencies group across 1 directory with 3 updates by @dependabot[bot] in https://github.com/JuliaLang/juliaup/pull/1587
    - [AUTO] Update version db by @github-actions[bot] in https://github.com/JuliaLang/juliaup/pull/1588
    - ci: cross-compile i686-pc-windows-gnu from the x86_64 host toolchain by @IanButterworth in https://github.com/JuliaLang/juliaup/pull/1590
    - Add startmenu items for Juliaup GUI to Windows installers by @davidanthoff in https://github.com/JuliaLang/juliaup/pull/1591
    Full Changelog: https://github.com/JuliaLang/juliaup/compare/v1.22.5...v1.22.6
- Key: ReleaseNotesUrl
  Value: https://github.com/JuliaLang/juliaup/releases/tag/v1.22.6
ReleaseTime: 2026-09-10T21:26:32.0000000Z
