Version: 3.0.2.2553
Installer:
- Architecture: x64
  InstallerUrl: https://edge.elgato.com/egc/windows/ewlw/3.0.2/Elgato.WaveLink_3.0.2.2553_x64.msix
- Architecture: arm64
  InstallerUrl: https://edge.elgato.com/egc/windows/ewlw/3.0.2/Elgato.WaveLink_3.0.2.2553_arm64.msix
Locale: []
