Version: 26058.601.4447.1224
Installer:
- Architecture: x86
  InstallerUrl: https://statics.teams.cdn.live.net/production-windows-x86/26058.601.4447.1224/MicrosoftTeams-x86.msix
- Architecture: x64
  InstallerUrl: https://statics.teams.cdn.live.net/production-windows-x64/26058.601.4447.1224/MicrosoftTeams-x64.msix
- Architecture: arm64
  InstallerUrl: https://statics.teams.cdn.live.net/production-windows-arm64/26058.601.4447.1224/MicrosoftTeams-arm64.msix
Locale: []
