Version: 0.1.55
Installer:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/changexbc/workbuddy-switch/releases/download/v0.1.55/workbuddy-switch_0.1.55_x64-setup.exe
Locale:
- Locale: zh-CN
  Key: ReleaseNotesUrl
  Value: https://github.com/changexbc/workbuddy-switch/releases/tag/v0.1.55
ReleaseTime: 2026-09-29T15:59:08.0000000Z
