Version: 0.1.18
Installer:
- Architecture: x86
  InstallerUrl: https://github.com/nashaofu/shell360/releases/download/v0.1.18/Shell360_0.1.18_x86-setup.exe
- Architecture: x64
  InstallerUrl: https://github.com/nashaofu/shell360/releases/download/v0.1.18/Shell360_0.1.18_x64-setup.exe
- Architecture: arm64
  InstallerUrl: https://github.com/nashaofu/shell360/releases/download/v0.1.18/Shell360_0.1.18_arm64-setup.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: 'Full Changelog: https://github.com/nashaofu/shell360/compare/v0.1.17...v0.1.18'
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/nashaofu/shell360/releases/tag/v0.1.18
ReleaseTime: 2026-03-09T03:00:03.0000000Z
