Version: 2.8.0-0
Installer:
- Architecture: x64
  InstallerUrl: https://github.com/mamba-org/micromamba-releases/releases/download/2.8.0-0/micromamba-win-64
Locale:
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/mamba-org/mamba/releases
ReleaseTime: 2026-06-04T18:45:32.0000000Z
