Version: 0.11.6.1
Installer:
- Architecture: x64
  InstallerUrl: https://github.com/imputnet/helium-windows/releases/download/0.11.6.1/helium_0.11.6.1_x64-installer.exe
  AppsAndFeaturesEntries:
  - DisplayVersion: ""
- Architecture: arm64
  InstallerUrl: https://github.com/imputnet/helium-windows/releases/download/0.11.6.1/helium_0.11.6.1_arm64-installer.exe
  AppsAndFeaturesEntries:
  - DisplayVersion: ""
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Changes since last build:
    helium-windows
    c1b5369 update: helium 0.11.6.1 (#232)
    helium-chromium
    f8de630e revision: bump to 6 (#1508)
    d8f9af28 helium/ui/zen: enable zen mode option by default (#1507)
    ce44c743 helium/ui: fix dark mode colors & refactor related patches (#1504)
    5eea50a9 helium/ui: use darker colors in dark mode
    257efc82 helium/ui/frame-background: remove useless header include & format
    1ae83afc i18n: add new strings, update owners, fix notify script (#1448)
    a2a555ec i18n: update owners file
    0540940f ci: fix i18n notify pipeline
    7bd090f5 i18n: add new strings

    See this GitHub Actions Run for the Workflow file used as well as the build logs and artifacts
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/imputnet/helium-windows/releases/tag/0.11.6.1
ReleaseTime: 2026-04-28T21:19:32.0000000Z
