Version: 0.14.4.1
Installer:
- Architecture: x64
  InstallerUrl: https://github.com/imputnet/helium-windows/releases/download/0.14.4.1/helium_0.14.4.1_x64-installer.exe
  AppsAndFeaturesEntries:
  - DisplayVersion: ""
- Architecture: arm64
  InstallerUrl: https://github.com/imputnet/helium-windows/releases/download/0.14.4.1/helium_0.14.4.1_arm64-installer.exe
  AppsAndFeaturesEntries:
  - DisplayVersion: ""
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Changes since last build:
    helium-windows
    747509c update: helium 0.14.4.1 (#315)
    helium-chromium
    36aa5e34 revision: bump to 4 (#2076)
    3b87cfd2 merge: update to chromium 150.0.7871.100 (#2075)
    6d652dee merge: update ungoogled-chromium to 150.0.7871.100
    4167eda8 Update to Chromium 150.0.7871.100
    1c614653 helium/ui: add experimental native frame materials for macOS (#2056)
    ecb00222 i18n/de: fix incorrect conjugation and adjust another translation (#2074)
    389fe06c helium/zen: don't force floating VTS to expand when not attached (#2068)
    320bccb7 helium/core/search: add url for reverse image search with google (#2065)
    33ac2286 i18n/zh-CN: update "Copy URL(s)" translation (#2048)
    1c072920 helium/settings: fix v8 page being empty (#2055)
    2420c7b5 helium/ui/separators: remove rounded corner on attached side (#2054)

    See this GitHub Actions Run for the Workflow file used as well as the build logs and artifacts
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/imputnet/helium-windows/releases/tag/0.14.4.1
ReleaseTime: 2026-07-08T00:03:12.0000000Z
