Version: 0.16.8
Installer:
- Architecture: x64
  InstallerUrl: https://cdn.proma.cool/releases/win-x64/Proma-0.16.8-setup.exe
Locale:
- Locale: zh-CN
  Key: ReleaseNotesUrl
  Value: https://github.com/proma-ai/Proma/releases
ReleaseTime: 2026-08-03T05:16:29.2550000Z
