Version: 2.7.8
Installer:
- InstallerType: msix
  InstallerUrl: https://github.com/microsoft/WSL/releases/download/2.7.8/Microsoft.WSL_2.7.8.0_x64_ARM64.msixbundle
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://github.com/microsoft/WSL/releases/download/2.7.8/wsl.2.7.8.0.x64.msi
- Architecture: arm64
  InstallerType: wix
  InstallerUrl: https://github.com/microsoft/WSL/releases/download/2.7.8/wsl.2.7.8.0.arm64.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    What's Changed
    - Fix CreateInstance failure when Windows hosts file exceeds message size cap (2.7 backport) by @benhillis in https://github.com/microsoft/WSL/pull/40726
    - Update kernel to 6.18.33.1-1 by @chessturo in https://github.com/microsoft/WSL/pull/40728
    Full Changelog: https://github.com/microsoft/WSL/compare/2.7.7...2.7.8
- Key: ReleaseNotesUrl
  Value: https://github.com/microsoft/WSL/releases/tag/2.7.8
ReleaseTime: 2026-06-06T16:27:02.0000000Z
