Version: 2.7.11
Installer:
- InstallerType: msix
  InstallerUrl: https://github.com/microsoft/WSL/releases/download/2.7.11/Microsoft.WSL_2.7.11.0_x64_ARM64.msixbundle
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://github.com/microsoft/WSL/releases/download/2.7.11/wsl.2.7.11.0.x64.msi
- Architecture: arm64
  InstallerType: wix
  InstallerUrl: https://github.com/microsoft/WSL/releases/download/2.7.11/wsl.2.7.11.0.arm64.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    What's Changed
    - Fix MoveDistribution VHD ownership restore to reuse the resolved file handle (backport to release/2.7) by @benhillis in https://github.com/microsoft/WSL/pull/41147
    - Backport security fixes to release/2.7 by @benhillis in https://github.com/microsoft/WSL/pull/41155
    Full Changelog: https://github.com/microsoft/WSL/compare/2.7.10...2.7.11
- Key: ReleaseNotesUrl
  Value: https://github.com/microsoft/WSL/releases/tag/2.7.11
ReleaseTime: 2026-07-24T16:59:19.0000000Z
