Version: 2.7.13
Installer:
- InstallerType: msix
  InstallerUrl: https://github.com/microsoft/WSL/releases/download/2.7.13/Microsoft.WSL_2.7.13.0_x64_ARM64.msixbundle
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://github.com/microsoft/WSL/releases/download/2.7.13/wsl.2.7.13.0.x64.msi
- Architecture: arm64
  InstallerType: wix
  InstallerUrl: https://github.com/microsoft/WSL/releases/download/2.7.13/wsl.2.7.13.0.arm64.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    What's Changed
    - Resolve an issue preventing WSL from starting due to an MDE Plugin error
    Full Changelog: https://github.com/microsoft/WSL/compare/2.7.12...2.7.13
- Key: ReleaseNotesUrl
  Value: https://github.com/microsoft/WSL/releases/tag/2.7.13
ReleaseTime: 2026-09-04T15:41:02.0000000Z
