Version: 1.12.0
Installer:
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: portable
  InstallerUrl: https://github.com/anthropics/anthropic-cli/releases/download/v1.12.0/ant_1.12.0_windows_386.zip
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  InstallerUrl: https://github.com/anthropics/anthropic-cli/releases/download/v1.12.0/ant_1.12.0_windows_amd64.zip
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  InstallerUrl: https://github.com/anthropics/anthropic-cli/releases/download/v1.12.0/ant_1.12.0_windows_arm64.zip
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    1.12.0 (2026-06-09)
    Full Changelog: v1.11.0...v1.12.0
    Features
    - api: add support for Managed Agents deployments and environment variable credentials (b36672a)
    - api: manual updates (d94edec)
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/anthropics/anthropic-cli/releases/tag/v1.12.0
ReleaseTime: 2026-06-09T20:14:01.0000000Z
