Version: 0.5.2
Installer:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/Austin-Patrician/Wordless/releases/download/v0.5.2/Wordless-0.5.2-win-x64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: 'Full Changelog: https://github.com/Austin-Patrician/Wordless/compare/v0.5.1...v0.5.2'
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/Austin-Patrician/Wordless/releases/tag/v0.5.2
ReleaseTime: 2026-09-07T14:32:48.0000000Z
