Version: 8.12.5
Installer:
- Architecture: x64
  InstallerUrl: https://s3-eu-west-1.amazonaws.com/hackolade/previous/v8.12.5/Hackolade-win64-setup-signed.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - DBML: added shortcut on each line of grid to jump to object in respective ERD or diagram view
    - DBML: added reverse-engineering of attributes with enums
    - DBML: added reverse-engineering of table-level check constraints
    - DBML: added reverse-engineering of note keyword for projects and tables, whether inline or out-of-line blocks
    - DBML: added to Command-Line Interface new argument --source=dbml
    - Excel: added entity Height and Width properties to export/import
    - Grid View: added inline editing of numeric values
    - Grid View: added persistence of default grid configuration in data model file
    - Grid View: added configurations to Tools > Options > Backup & Restore
    - Naming conventions: changed from asynchronous to synchronous process plus stored snapshot in order to make undo/redo more predictable
    - PowerDesigner: added using table name from query clause as a fallback when no tables are specified in the view definition
    - PowerDesigner: enhanced parsing of SELECT statements using the Code/Technical Name of related table columns
    - Properties Pane: added height and width value properties to Options tab of entities, when respectively auto-height and auto-width are disabled
    - Properties Pane: enhanced display of entity boxes in ERD when enabling auto-height and auto-width checkboxes
    - Properties Pane: improved performance when changing subtype property
ReleaseTime: 2026-07-24
