Version: 8.9.8
Installer:
- Architecture: x64
  InstallerUrl: https://s3-eu-west-1.amazonaws.com/hackolade/previous/v8.9.8/Hackolade-win64-setup-signed.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: '- Documentation: enhanced robustness of PNG image generation for large model ERDs'
ReleaseTime: 2026-03-16
