Version: 15.0.23
Installer:
- Architecture: x64
  InstallerUrl: https://github.com/mullvad/mullvad-browser/releases/download/15.0.23/mullvad-browser-windows-x86_64-15.0.23.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - All Platforms
      - Updated Firefox to 140.16.0esr
      - Updated NoScript to 13.6.33.1984
      - Bug 577: Rebase Mullvad Browser stable onto 140.16.0esr [mullvad-browser]
      - Bug 45296: (H1) SharedWorker Identity Mismatch allows WebAssembly execution at Safer [tor-browser]
      - Bug 45297: (H1) Missing setHTMLUnsafe hook leaves a permanent WebAssembly-capable child realm at Safer [tor-browser]
      - Bug 45299: Backport Security Fixes from Firefox 156 [tor-browser]
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/mullvad/mullvad-browser/releases/tag/15.0.23
ReleaseTime: 2026-09-21T11:29:13.0000000Z
