Version: 0.1.5
Installer:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/AnkioTomas/penna-markdown-desktop/releases/download/v0.1.5/Penna.Markdown_0.1.5_x64-setup.exe
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://github.com/AnkioTomas/penna-markdown-desktop/releases/download/v0.1.5/Penna.Markdown_0.1.5_x64_en-US.msi
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    更新日志
    对比：v0.1.4 → v0.1.5
    - ✨ (app): 添加应用版本号显示功能 (11d714f)
    - ⬆️ (build): 更新版本号从 0.1.4 到 0.1.5 (2f07520)
    - 🔧 update dependencies in Cargo.lock (8d190fb)
    - ✨ (ui): 添加编辑器快捷键开关设置 (229da45)
    - 🔧 (build): 添加 HTTP 插件以支持网络请求 (e260e10)
    - ♻️ (app): 优化导出功能的文件名生成和标题处理 (d461ded)
- Locale: zh-CN
  Key: ReleaseNotesUrl
  Value: https://github.com/AnkioTomas/penna-markdown-desktop/releases/tag/v0.1.5
ReleaseTime: 2026-09-16T05:49:34.0000000Z
