Version: 18.10.3
Installer:
- Architecture: x64
  InstallerUrl: https://cdn.teleport.dev/Teleport Connect Setup-18.10.3.exe
  InstallerSha256: 1CEEDC11200B90BE6428E51939E0FE82C57BA74F65A2D50200F7AAC76AE203AC
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: Teleport 18.10.3
