Version: 2.2.0.242
Installer:
- Architecture: x86
  InstallerUrl: https://www.benthicsoftware.com/apps/goldsqall2setup242_32bit.exe
  ProductCode: Golden232_is1
- Architecture: x64
  InstallerUrl: https://www.benthicsoftware.com/apps/goldsqall2setup242_64bit.exe
  ProductCode: Golden264_is1
Locale: []
ReleaseTime: 2026-03-26
