Version: 0.12.0
Installer:
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  InstallerUrl: https://github.com/bestruirui/octopus/releases/download/v0.12.0/octopus-windows-amd64.zip
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    🚀 Features
    - ✨ 允许自定义 key 的值 - by @bestruirui (33d6a)
    🐞 Bug Fixes
    - 🐛 流式响应 context canceled - by @bestruirui (10f02)
    - 🐛 Windows 更新 - by @bestruirui (0771c)
    - 🐛 超时参数 - by @bestruirui (bbcce)
    🏎 Performance
    - ⚡️ 将渠道模型拆分为单独的数据库表 - by @bestruirui (77b37)
    View changes on GitHub
- Locale: zh-CN
  Key: ReleaseNotesUrl
  Value: https://github.com/bestruirui/octopus/releases/tag/v0.12.0
ReleaseTime: 2026-08-24T07:32:28.0000000Z
