Version: 0.12.1
Installer:
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  InstallerUrl: https://github.com/bestruirui/octopus/releases/download/v0.12.1/octopus-windows-amd64.zip
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    🚀 Features
    - ✨ 增加分享功能 - by @bestruirui (d7ca3)
    🐞 Bug Fixes
    - 🐛 lint - by @bestruirui (8f23f)
    🏎 Performance
    - ⚡️ 重新设计渠道统计，新增分享功能 - by @bestruirui (b2e4f)
    View changes on GitHub
- Locale: zh-CN
  Key: ReleaseNotesUrl
  Value: https://github.com/bestruirui/octopus/releases/tag/v0.12.1
ReleaseTime: 2026-08-25T14:35:36.0000000Z
