Version: "26.10"
Installer:
- InstallerUrl: https://www.sysinfotools.com/demo-version/SysInfo-MBOX-Exporter-Demo.exe
  InstallerSha256: 2F08C5B157094E1F8453420F014773F410D5FCCC3B7686B219C6C9C203C812BB
Locale: []
LastModified: Fri, 09 Oct 2026 05:50:45 GMT
