Version: 3.5.0
Installer:
- Architecture: x86
  InstallerUrl: https://lf-luna-release.qishui.com/obj/luna-release/3.5.0/402440756/SodaMusic-v3.5.0-official-win32_ia32.exe
  InstallerSha256: 75465e4cec1dbe1be7e2a3aaa975aa10a9b3410bc418329409c5695f36b702ea
- Architecture: x64
  InstallerUrl: https://lf-luna-release.qishui.com/obj/luna-release/3.5.0/402440756/SodaMusic-v3.5.0-official-win32_x64.exe
  InstallerSha256: f2fe07d4ddff20726cef7af04687863f39f973cab77374d558e51ed49cc346f4
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: 优化了用户体验，修复了一些已知问题
