Version: 2.2.1
Installer:
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://github.com/Jerry-Z07/WindBoard/releases/download/v2.2.1/WindBoardSetup-2.2.1-win-x86.exe
- Architecture: x64
  InstallerType: inno
  InstallerUrl: https://github.com/Jerry-Z07/WindBoard/releases/download/v2.2.1/WindBoardSetup-2.2.1-win-x64.exe
- Architecture: arm64
  InstallerType: inno
  InstallerUrl: https://github.com/Jerry-Z07/WindBoard/releases/download/v2.2.1/WindBoardSetup-2.2.1-win-arm64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: (English changelog not provided for v2.2.1. Please refer to the Chinese section.)
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    - feat(installer): 添加卸载时可选删除用户数据功能
    - chore
- Key: ReleaseNotesUrl
  Value: https://github.com/Jerry-Z07/WindBoard/releases/tag/v2.2.1
ReleaseTime: 2026-03-06T16:53:21.0000000Z
