Version: 26.9.15
Installer:
- InstallerUrl: https://sk-data.special-k.info/repository/SpecialK_26.9.15.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    + Added configurable framerate limiter energy efficiency presets.
     + Fixed deadlock in do_win_verify_trust in the latest MSVC toolchain.
     + Added support for Deep Learned Slop Shading 5.
     + Added support for DLSS Ray Reconstruction (310.7.128+) Preset F.
     + Stop displaying HDR preset change notifications when HDR is inactive.
     + Restore basic Windows 7 compatibility.
     + Fixed Genshin Impact crashing at login screen.
