Version: 262.6228.35
Installer:
- Architecture: x64
  InstallerUrl: https://download.jetbrains.com/go/goland-262.6228.35.exe
  ProductCode: GoLand 262.6228.35
  InstallerSha256: 9082D9A62C4DCEF0564125C752E9DC0C84B24B549BEFA052136919EA1FD22B96
- Architecture: arm64
  InstallerUrl: https://download.jetbrains.com/go/goland-262.6228.35-aarch64.exe
  ProductCode: GoLand 262.6228.35
  InstallerSha256: C91D5D55AC98741FB6C306E8AEDAED12B14FBB39FB6A8A2E2393E29C6C7BD591
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    GoLand 2026.2 EAP 3 is now available!
    In this EAP, we’ve introduced a bunch of minor updates and bug fixes. Please see the release notes for the complete list of fixes and improvements.
- Key: ReleaseNotesUrl
  Value: https://youtrack.jetbrains.com/articles/GO-A-231736061/GoLand-2026.2-EAP-3-262.6228.35-build-Release-Notes
ReleaseTime: 2026-05-21
