Version: "12.21"
Installer:
- InstallerUrl: https://github.com/RandomEngy/VidCoder/releases/download/v12.21/VidCoder-12.21.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - Added the crash exception to the logs as well, if possible.
    - Added additional logging for a GetDefaultMixdown issue
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/RandomEngy/VidCoder/releases/tag/v12.21
RealVersion: 12.21.0
ReleaseTime: 2026-07-11T16:13:41.0000000Z
