Version: "12.17"
Installer:
- InstallerUrl: https://github.com/RandomEngy/VidCoder/releases/download/v12.17/VidCoder-12.17.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - Updated HandBrake core to 1.11.
    - Updated framework to .NET 10.
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/RandomEngy/VidCoder/releases/tag/v12.17
RealVersion: 12.17.0
ReleaseTime: 2026-03-12T04:04:33.0000000Z
