Version: 261.22158.44
Installer:
- Architecture: x64
  InstallerUrl: https://download.jetbrains.com/ruby/RubyMine-261.22158.44.exe
  ProductCode: RubyMine 261.22158.44
  InstallerSha256: 875AA5F2711C10ACADDB818E756B54FCAAAA390DA9CC0BC1F6289F345EAC2026
- Architecture: arm64
  InstallerUrl: https://download.jetbrains.com/ruby/RubyMine-261.22158.44-aarch64.exe
  ProductCode: RubyMine 261.22158.44
  InstallerSha256: 8B44612A47F552EC4DE465A8CD5224B380AA989FB0F86B7C53FBB8DC0562B28E
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    RubyMine 2026.1 EAP 7 Is Out!
    Fixes and improvements:
    - Fixed navigation from a controller action to its view via the gutter icon after the view file is renamed: RUBY-35303
    - Fixed navigation and completion for inline constants declared inside array expressions when using beta code insight: RUBY-35278
    - Fixed incorrect rendering and copying of large multiline strings in the debugger: RUBY-33628
    - Fixed incorrect navigation from the No Ruby interpreter selected notification: RUBY-35314
    - Added clickable relative file paths in the Terminal for faster navigation to project sources: IJPL-232564
    For the full list of closed issues, refer to the release notes.
- Key: ReleaseNotesUrl
  Value: https://youtrack.jetbrains.com/articles/RUBY-A-220365332/RubyMine-2026.1-EAP-7-261.22158.44-build-Release-Notes
ReleaseTime: 2026-03-06
