Version: 4.0.0
Installer:
- Architecture: x64
  InstallerUrl: https://github.com/pawelsalawa/letos/releases/download/4.0.0/Letos-4.0.0-windows-x64-setup.exe
- Architecture: arm64
  InstallerUrl: https://github.com/pawelsalawa/letos/releases/download/4.0.0/Letos-4.0.0-windows-arm64-setup.exe
Locale:
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/pawelsalawa/letos/blob/HEAD/ChangeLog.md
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - ADDED: #2865 ERD editor - a diagram viewer and editor for database schema.
    - ADDED: #5206 Windows ARM64 binaries provided.
    - ADDED: #5241 Linux ARM64 binaries provided.
    - ADDED: #4899 MacOS ARM64 (M1, M2, ...) binaries provided as Universal Binary (both x86_64 and ARM64 architectures supported by a single binary).
    - ADDED: #3886 Added image rendering for image data in the Grid View (plugin-based, so more renderers can be added in future).
    - ADDED: #4027 Added data editor plugin for JSON - with syntax validation and highlighting for editing table data. Contributed by @calumk!
    - ADDED: #5445 Added AUTOINCR option directly to column dialog, reducing clicks needed to create the INTEGER PRIMARY KEY AUTOINCREMENT column.
    - ADDED: #3930 Added support for defining user-defined Aggregate Window Functions in the Functions Editor.
    - ADDED: #4269 Double-clicking on a cell that clearly contains a value to be edited in the Value Editor dialog will immediately open it in the editor dialog.
    - ADDED: #4271 Value Editor dialog (and Form View editor) allow now loading/saving value from/into a file by dedicated buttons.
    - ADDED: #4599 Added Command Palette (Ctrl+Shift+P by default) for quick search & execution of common actions, searching configuration options, etc.
    - ADDED: #5165 Database List can be now synced/linked with active MDI window using the toggle button on top of the database list.
    - ADDED: #5212 Objects on Database List (databases, tables, columns, indexes, triggers, views) can be now renamed quickly inline.
    - ADDED: #5212 Dragging table/view/columns from Database List to SQL Editor will now generate SELECT/UPDATE/INSERT depending on the keyboard modifier during the drop.
    - ADDED: #4662 ScriptingPython plugin now allow selecting Python installed in your system and it's compatible with all recent (and not so recent) Python versions. Big thanks to @tuffnatty for this!
    - ADDED: #4117 Syntax highlighting now supports bold/italic settings.
    - ADDED: #3365 Added Tcl syntax highlighter plugin.
    - ADDED: #3283 Added Tip of the Day plugin.
    - ADDED: #5449 User can now change size of icons on toolbars.
    - ADDED: #5493 Password input (for example in database dialog for encrypted files) has now icon to show/hide the password.
    - ADDED: #4677 Search function for Form View text fields (with Ctrl+f/Cmd+f hotkey).
    - ADDED: #4598 Ctrl+f/Cmd+f hotkey in Grid View now moves focus to filter input.
    - ADDED: #5212 F2 hotkey in SQL editor opens database object being currently at the cursor position (if any).
    - ADDED: #5150 Added the Disable Blinkinig Cursor (for SQL Editor) option in the configuration dialog.
    - ADDED: #4232 Application will warn in status field if the open database was recently edited by a higher version of SQLite and that it may potentially cause some issues.
    - ADDED: #5552 Support for new syntax variants of ALTER TABLE.
    - ADDED: #5383 Double-click on column separator in data view now supports resizing all selected columns at once.
    - ADDED: #5566 Added Columns node to Views in Database List.
    - ADDED: #5284 Column widths and Row Height Adjusting in Grid View is now stored in the session and restored upon next application strt.
    - ADDED: #5578 Much better suppport for dropping various files (databases, SQL files, ...) onto the application Window.
    - ADDED: #5570 In Configuration dialog the Reset To Defaults button was added for hotkeys page.
    - ADDED: #3934 Windows executables in the official release are now signed thanks to the SignPath.io.
    - ADDED: #3932 MacOS executables in the official release are now signed with Apple Developer ID.
    - ADDED: #3539 Export Dialog now has option to export View(s) together with their triggers and data. View Window now has icon on the toolbar to export the View.
    - ADDED: #4417 Html Export plugin produces now HTML tables that are sortable by clicking on their headers.
    - ADDED: #4286 SQL History tab has now function to export executed queries history (or selected subset) to a SQL file.
    - ADDED: #5369 The Format SQL action added to context menus everywhere where SQL is being being edited. Also the hotkey for actions works for it.
    - ADDED: #4401 Custom footer and header can be configured for PDF and HTML export.
    - ADDED: #4401 PDF export now includes query used for the data being exported (when exporting Query Results or a View).
    - ADDED: #5106 Tools menu entries to export/import application configuration, such as defined functions, collation sequences, code snippets and SQLite extensions.
    - ADDED: #4502 When selecting multiple cells, sum of all numerical values will be shown in the toolbar, next to numer of loaded rows.
    - ADDED: #5345 Column data types are now displayed as labels for column on database list. It can be switched off in configuration.
    - ADDED: #4724 Columns in Data Grid View can now be pinned from header's context menu.
    - ADDED: #4623 Form View row number is now an editable input, allowing to jump to arbitraty row number within currently loaded page of data.
    - ADDED: #4539 Added the Open In Editor button to DDL preview dialog.
    - ADDED: #5290 Execute From File Dialog now supports 3 execution modes, allowing SQLite CLI dot commands in the executed file.
    - ADDED: #4873 Execute From File Dialog remembers its settings for another use.
    - ADDED: #5611 Query results in SQL Editor can be arranged on the right side of the query, apart from the options available so far (below query or on separate tab). The layout is saved in the session and restored upon next start.
    - ADDED: #4225 Foreign Key constraint configuration dialogs now warns about using foreign column that is neither PRIMARY KEY nor UNIQUE.
    - ADDED: #3035 The INSTEAD OF triggers on Views are now honored when present. Add/Delete row in the View Window now appears if respective INSTEAD OF trigger is present for the View.
    - ADDED: #5085 Added 'Cut' entry to context menu of data Grid View.
    - ADDED: #5684 Added debug(msg) SQL function to print messages to Status Field, for example from TRIGGER body.
    - ADDED: #4709 Added option in configuration to sort data by single-click on a header. Ehnanced data header tooltips to include this information there.
    - ADDED: #3566 Added option in configuration to make the Enter key move to the next row, if it was used to finish data editing in Grid View. The option is also available from the Grid's context menu.
    - ADDED: #5574 Application was fully translated with AI LLM to new languages: Afrikaans, Arabic, Belarusian, Catalan, Czech, Danish, Dutch, Greek, Hugarian, Japanese, Korean, Norwegian, Portuguese (both European and Brazilian), Romanian, Serbian, Slovak, Swedish, Turkish.
    - CHANGE: #5441 Project has been renamed to Letos. Together with the name, also domain/homepage has changed to letos.org.
    - CHANGE: #4553 Application has moved to Qt 6 (dropping Qt 5 support). This solves several technical issues (for example accented characters on MacOS, better UI scaling for high DPI displays, better dark theme support and more).
    - CHANGE: #5102 All raster icons are replaced with vector icons (SVG). This makes them scalable and work well with high DPI displays.
    - CHANGE: #5701 SQLite3 version updated to 3.53.2.
    - CHANGE: #4271 Value Editor (and Form View) got small visual lifting to be more convenient to use (bigger column labels, etc).
    - CHANGE: #4862 SQL Editor is now tied to a file whenever loads or saves to that file and that tie is restored upon next application session. It also renames editor window to that file name.
    - CHANGE: #4762 Colors configuration for syntax highlighting now allows defining also bold/italic attributes.
    - CHANGE: #5541 Plugins Page in Configuration Dialog uses now a material-design-like toggle for loading/unloading plugins + each plugin has more vertical padding and is clickable as a whole row, not just a small box.
    - CHANGE: #5212 Configuration Dialog filter marks matched widgets with red outline.
    - CHANGE: #5597 Configuration Dialog items on the categoris list are now a bit taller, icons a bit bigger.
    - CHANGE: #5561 Database actions on main toolbar simplified, partially moved to Database List panel.
    - CHANGE: #5060 Application connects to the database that was just added to the list.
    - CHANGE: #5374 Ctrl+O (Cmd+O on macOS) now always asks for a file to open and if it's a database, it's added to the list. If it's SQL file, the SQL editor opens for it.
    - CHANGE: #5374 Ctrl+N (Cmd+N on macOS) now always asks for a file to create and adds the new database to the list.
    - CHANGE: #5477 WxSQLite plugin was renamed to its proper name, the SQLite3MC (SQLite 3 Multiple Ciphers).
    - CHANGE: #5456 Table Modifier optimization, so at most only single copying data can happen, instead of two. Also views/triggers support got improved for cases with subselects.
    - CHANGE: #5496 Code Assistant improved to suggest appropriate JOIN conditions when asked at the ON keyword of joining tables. Currently supports only plain table data sources (not subselects).
    - CHANGE: #5509 Foreign Key editor in Form View and dedicated editor dialog now shows preview of currently selected value of foreign table.
    - CHANGE: #5580 Column Dialog now shows Composite constraints that affect edited column as read-only checked options, to make it clear why this column has particular constraint icon on it in Table Window.
    - CHANGE: #5562 Several toolbars cleaned up, simplified.
    - CHANGE: #5591 Enhanced support for DEFAULT/AUTOINCR/GENERATED columns, so that it's the default value is distinct from NULL and user can always reset new cell value to its default value.
    - CHANGE: #5212 Database list now expands columns, indexes and triggers whenever the table is expanded.
    - CHANGE: #5212 Middle-click on an open database closes it. Middle-click on tables/views (in Database List) closes respective Table and View windows.
    - CHANGE: #5164 Added option to prefer sqlite_master table name over sqlite_schema on the Database List.
    - CHANGE: #5497 Boundled SQLite extensions now use path relative to the running application.
    - CHANGE: #5212 Table Window and View Window does not ask for closing confirmation when they were open for creation of new object and not yet modified.
    - CHANGE: #5212 New Table and New View actions are now disabled if selected item in the Database List does not have open database, as it may be misleading to start designing new table/view and miss the fact that it's still not aimed towards the database.
    - CHANGE: #4849 The setting to show per-column filters in Grid View is now remembered.
    - CHANGE: #5269 Default hotkey for Configuration Dialog changed to Ctrl+, on all platforms.
    - CHANGE: #5212 Config Dialog now remembers the last used page and restores it when its open next time.
    - CHANGE: #5477 SQLCipher for SQLite3MultipleCiphers plugin now provides small initial pragmas configuration proposal.
    - CHANGE: #4475 Using RETURNING clause for INSERTing data to optimize the operation.
    - CHANGE: #3539 File extension in Export Dialog file input is now updated whenever export format is changed.
    - CHANGE: #4554 Added Select All and Deselect All buttons to Populate Dialog.
    - CHANGE: #5321 Reported query execution time now shows more decimal places and removes trailing zeros. The precision is now also configurable.
    - CHANGE: #5209 Default Code Snippet list extended and now they are preferred in the Code Assist when SQL Editor is empty.
    - CHANGE: #5642 Bind Param Dialog now starts in simplified layout (unless complex values were remembered), which is much cleaner for simple input.
    - CHANGE: #5092 Functions, Collations, Code Snippets and Extensions windows now show more info on their list (number of databases in which they are registered, etc). Additionally their splitter position is now remembered.
    - CHANGE: #5158 Status panel now dims older messages, when new messages appear, so they stand up. User can also configure to use older behavior (no dimming), or to remove older messages entirely from the panel and keep only the new one.
    - CHANGE: #4688 Added metadata to Windows executables.
    - CHANGE: #2956 Export Dialog respects hotkeys for changing database in the dropdown, using the same hotkey as SQL Editor.
    - CHANGE: #4964 Import Dialog has now inverted order of pages - the imported file first and then the target table, for which the name is concluded from imported file name. Also filter for CSV import is now extended with tsv files.
    - CHANGE: #3522 EXPLAIN button in SQL Editor now has dropdown menu with selection between EXPLAIN and EXPLAIN QUERY PLAN modes.
    - CHANGE: #5612 With hotkeys being reset to defaults in version 4.0.0, the relevant notification message is now printed upon the reset.
    - CHANGE: #5634 Execute SQL From File dialog no whas a database selector and the action appears in all database list context menus + in the Tools menu of main menubar.
    - CHANGE: Windows x86 (32-bit) binaries will no longer by provided in official builds.
    - CHANGE: #5657 The command line application (letoscli) was deprecated and removed from the current code branch. Please use official SQLite3 CLI as a command line app, as it improved a lot in recent versions.
    - CHANGE: #5574 Application translations were updated with missing translations using AI LLM for languages: Chinese (Simplified and Traditional), French, Italian, Slovak, Spanish
    - CHANGE: #5574 Application translations were updated with missing translations for lanuages: Polish
    - BUGFIX: #3079 Enterprise Formatter now handles comments much better than before.
    - BUGFIX: #4986 Unique indexes are allowed for expressions, as they should be.
    - BUGFIX: #5498 Empty/null cells resulting from LEFT JOINs are not editable anymore.
    - BUGFIX: #3995 Fixed blank MDI window buttons when using 150% interface scaling under Windows.
    - BUGFIX: #3146 Fixed accent characters support under MacOS.
    - BUGFIX: #5212 Grid columns do not shrink when unwanted while refreshing data, or entering new values to cells.
    - BUGFIX: Improved Code Assistant suggestions when SQL editor contains more than one query.
    - BUGFIX: #5089 User-defined functions now follow database renaming in case the function was explicitly registered for the database.
    - BUGFIX: #5584 Fixed user-defined collations.
    - BUGFIX: #5583 Fixed table labels on Database List to enforce the lazy-loaded table schemas to be loaded at once when this option is enabled.
    - BUGFIX: #5609 Fixed SQL syntax highlighter for multi-line comments with empty linies inside.
    - BUGFIX: #5628 Fixed PDF export bugs (first page size too small, occasional table overlapping, page numbers cut off).
    - BUGFIX: #5691 Fixed tooltip in Database Dialog with Wayland under Linux.
    - BUGFIX: #5692 Select first inserted row after inserting multiple rows in Grid View.
    - BUGFIX: #5713 MultiEditor now keeps original line separators from the value loaded, while new separators inserted are alwas \n. Also optimized performance for very long text lines in the editor.
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/pawelsalawa/letos/blob/HEAD/ChangeLog.md#400
ReleaseTime: 2026-06-23T19:05:25.0000000Z
