Version: 3.0.1
Installer:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/WSJTX/wsjtx/releases/download/v3.0.1/wsjtx-3.0.1-win64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/WSJTX/wsjtx/releases/tag/v3.0.1
- Key: Documentations
  Value:
  - DocumentLabel: User Guide
    DocumentUrl: https://wsjt.sourceforge.io/wsjtx-doc/wsjtx-main-3.0.1.html
  - DocumentLabel: Q65 Mode Quick-Start Guide
    DocumentUrl: https://wsjt.sourceforge.io/Q65_Quick_Start.pdf
  - DocumentLabel: SuperFox Mode User Guide
    DocumentUrl: https://wsjt.sourceforge.io/SuperFox_User_Guide.pdf
  - DocumentLabel: WSJT-X and MAP65 Quick-Start Guide
    DocumentUrl: https://wsjt.sourceforge.io/WSJTX_2.5.0_MAP65_3.0_Quick_Start.pdf
  - DocumentLabel: FT8 DXpedition Mode User Guide
    DocumentUrl: https://wsjt.sourceforge.io/FT8_DXpedition_Mode.pdf
- Locale: en-US
  Key: Documentations
  Value:
  - DocumentLabel: 用户指南
    DocumentUrl: https://wsjt.sourceforge.io/wsjtx-doc/wsjtx-main-3.0.1.html
  - DocumentLabel: Q65 模式 快速入门
    DocumentUrl: https://wsjt.sourceforge.io/Q65_Quick_Start.pdf
  - DocumentLabel: SuperFox 模式 使用指南
    DocumentUrl: https://wsjt.sourceforge.io/SuperFox_User_Guide.pdf
  - DocumentLabel: WSJT-X 和 MAP65 快速入门
    DocumentUrl: https://wsjt.sourceforge.io/WSJTX_2.5.0_MAP65_3.0_Quick_Start.pdf
  - DocumentLabel: FT8 远征模式 使用指南
    DocumentUrl: https://wsjt.sourceforge.io/FT8_DXpedition_Mode_Chinese.pdf
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://raw.githubusercontent.com/WSJTX/wsjtx/HEAD/Release_Notes.txt
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    WSJT-X 3.0.1 is a bug-fix release; installation packages include QMAP
    but not MAP65. Code has the following changes since release 3.0.0:

     - In posts sent to PSKReporter, version 3.0.0 incorrectly identified
       itself as "WSJT-X v3.0.0 i+". Corrected.

     - Uploads to CloudLog are re-enabled.

     - UI Compatibility mode is enabled for better display on macOS Tahoe.

     - A bug sometimes affecting CW transmissions in Echo mode has been
       fixed.

     - A bug preventing callsign highlighting in some circumstances has
       been fixed.

     - Corrected band limits for the 2.5 mm and 2 mm bands.

     - Correct faulty repositioning of SWR label in status bar, after a
       mode switch.

     - Fix stale Band Activity decodes after enabling SuperFox while in
       Hound mode (reported by AF8C).
ReleaseTime: 2026-05-03T19:13:21.0000000Z
