Version: 149.0.7827.53
Installer:
- Architecture: x86
  InstallerUrl: https://dl.google.com/dl/chrome/install/beta/googlechromebetastandaloneenterprise.msi
- Architecture: x64
  InstallerUrl: https://dl.google.com/dl/chrome/install/beta/googlechromebetastandaloneenterprise64.msi
- Architecture: arm64
  InstallerUrl: https://dl.google.com/dl/chrome/install/beta/googlechromebetastandaloneenterprise_arm64.msi
Locale: []
ETagX86: '"5f91a64-6aa1e4d0"'
ETagX64: '"5f919f7-6aa1e4d0"'
ETagARM64: '"5f910a8-6aa1e4d0"'
