Version: 153.0.8010.5
Installer:
- Architecture: x86
  InstallerUrl: https://dl.google.com/dl/chrome/install/beta/googlechromebetastandaloneenterprise.msi
- Architecture: x64
  InstallerUrl: https://dl.google.com/dl/chrome/install/beta/googlechromebetastandaloneenterprise64.msi
- Architecture: arm64
  InstallerUrl: https://dl.google.com/dl/chrome/install/beta/googlechromebetastandaloneenterprise_arm64.msi
Locale: []
ETagX86: '"69eb016-6aa1e4d0"'
ETagX64: '"69eb228-6aa1e4d0"'
ETagARM64: '"69eb00d-6aa1e4d0"'
