Version: 6.7.0.0
Installer:
- Architecture: x64
  InstallerUrl: https://coderbag.com/assets/downloads/cpm/currentversion/QuickCpuSetup.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - Added color palettes for application charts.
    - Added support for Intel Wildcat Lake processors.
    - Refactored the data access layer.
    - Enhanced support for AMD Ryzen processors.
ReleaseTime: 2026-09-10
