Version: 2.3.13960
Installer:
- InstallerUrl: https://lf-cdn.trae.ai/obj/trae-ai-us/pkg/app/releases/stable/2.3.13960/win32/Trae-Setup-x64.exe
- InstallerLocale: zh-CN
  InstallerUrl: https://lf-cdn.trae.com.cn/obj/trae-com-cn/pkg/app/releases/stable/2.3.13960/win32/Trae-Setup-x64.exe
Locale: []
ReleaseTime: 2026-03-14T06:09:47.7410000Z
RealVersion: 3.5.38
