Version: 7.1.2.29
Installer:
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://github.com/ImageMagick/ImageMagick/releases/download/7.1.2-29/ImageMagick-7.1.2-29-Q8-x86-dll.exe
- Architecture: x64
  InstallerType: inno
  InstallerUrl: https://github.com/ImageMagick/ImageMagick/releases/download/7.1.2-29/ImageMagick-7.1.2-29-Q8-x64-dll.exe
- Architecture: arm64
  InstallerType: inno
  InstallerUrl: https://github.com/ImageMagick/ImageMagick/releases/download/7.1.2-29/ImageMagick-7.1.2-29-Q8-arm64-dll.exe
Locale:
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/ImageMagick/Website/blob/HEAD/docs/changelog/index.md
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Commits
    - beta release b8ae505
    - Updated the dependencies. 90f5b91
    - add WEBP compress case when writing f35294e
    - Removed unnecessary include. 1e2f64f
    - Removed checks for values from tif_config.h that are not included, libtiff will report errors itself now. 7cf1988
    - Only set the TIFFTAG_WEBP_LEVEL when the quality is not undefined. 02ac849
    - Make sure we read the bits_per_sample before using it. 0af4ede
    - Added missing typecast. b919b37
    - release 360eda5
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/ImageMagick/Website/blob/HEAD/docs/changelog/index.md#712-29---2026-07-27
ReleaseTime: 2026-07-27T19:00:27.0000000Z
