Version: 3.22.3
Installer:
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://github.com/nomacs/nomacs/releases/download/3.22.3/nomacs-setup-x64.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    This release contains security updates in libraries used by nomacs.
    Anti-malware scan:
    https://www.virustotal.com/gui/file/26b39f265461a12048e89a340926b4ace8d205c16551b0a3096d9988b04d5a6b
    https://www.virustotal.com/gui/file/c5af7d6b09538f27a449ccd5bb1a739afff2235427d77bcab1a192f53965ea4e
    https://www.virustotal.com/gui/file/68687cb09038ee256bc193ea0864c67727563a64b870a23c7538e751f407eec1
- Key: ReleaseNotesUrl
  Value: https://github.com/nomacs/nomacs/releases/tag/3.22.3
ReleaseTime: 2026-09-01T15:03:57.0000000Z
