Version: 4.0.11
Installer:
- InstallerUrl: https://fdfs.xmcdn.com/storages/d2b8-audiofreehighqps/5C/6D/GKwRIJIN3EXXACAAAASZYNpo.exe
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: '- 修复一些已知问题'
ReleaseTime: 2026-05-15T02:20:06.7280000Z
