Version: 6.35.0.7018
Installer:
- InstallerUrl: https://dn3.freedownloadmanager.org/6/latest/fdm_x64_setup.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - Components update.
    - "Download later" button.
    - Minor interface improvements.
    - Fixed: a few bugs.
    - macOS: Fixed: native dialogs were in English instead of system's language.
