Version: 3.45.3.407
Installer:
- Architecture: x86
  InstallerUrl: https://updatecdn.meeting.qq.com/cos/99260b2b02cc04cfe2cb1f57a703a9ca/TencentMeeting_0300000000_3.45.3.407.publish.exe
- Architecture: x64
  InstallerUrl: https://updatecdn.meeting.qq.com/cos/afab755779a869494440bc1d2a9da32a/TencentMeeting_0300000000_3.45.3.407_x86_64.publish.exe
Locale: []
ReleaseTime: 2026-08-27
