Version: 152.6.9.1
Installer:
- Architecture: x86
  InstallerUrl: https://b2.catsxp.com/catsxp_update/win_x86/catsxp_installer_152_6_9_1.exe
- Architecture: x64
  InstallerUrl: https://b2.catsxp.com/catsxp_update/win_x64/catsxp_installer_152_6_9_1.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    1. [*]Kernel upgrade:152.0.7977.67
    2. [!]Some problems correction and detail optimization
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    1. [*]内核升级：152.0.7977.67
    2. [!]若干问题修正与细节优化
ReleaseTime: 2026-08-27T12:08:18.0000000Z
