Version: 146.6.3.2
Installer:
- Architecture: x86
  InstallerUrl: https://b2.catsxp.com/catsxp_update/win_x86/catsxp_installer_146_6_3_2.exe
- Architecture: x64
  InstallerUrl: https://b2.catsxp.com/catsxp_update/win_x64/catsxp_installer_146_6_3_2.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    1. [*]Kernel upgrade:146.0.7680.143
    2. [!]Some problems correction and detail optimization
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    1. [*]内核升级：146.0.7680.143
    2. [!]若干问题修正与细节优化
ReleaseTime: 2026-03-12T13:11:29.0000000Z
