Version: 5.2.1.0
Installer:
- InstallerUrl: https://binaryfortressdownloads.com/Download/BFSFiles/114/TrayStatusSetup-5.2.1.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - Resolved an issue with icon colouring
    - Resolved a crashing issue that might affect certain machines
ReleaseTime: 2026-07-24
