Version: 18.0.83
Installer:
- InstallerType: inno
  InstallerUrl: https://www.phraseexpress.com/PhraseExpressSetup.exe
  InstallerSha256: 96D698BF2C552206C02385E98EA477D05994F3F564B4A3D9B0703779BDC29A6E
- InstallerType: msi
  InstallerUrl: https://www.phraseexpress.com/PhraseExpressSetup.msi
Locale: []
LastModified: Fri, 02 Oct 2026 14:50:16 GMT
