Version: 2.10.0.5681
Installer:
- InstallerUrl: https://download.mypikpak.net/desktop/official_PikPak.exe
  InstallerSha256: A906B9C48EF0CE23FC3839D03DD5757160DE8030D17995E1716A17572E922977
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: Added support for renaming files and folders in the Recently Added tab.
- Locale: zh-CN
  Key: ReleaseNotes
  Value: 在「最近添加」Tab 中新增了文件及文件夹重命名支持。
LastModified: Mon, 22 Jun 2026 08:08:46 GMT
RealVersion: 2.10.0
