Version: 2.62.0
Installer:
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://github.com/phrase/phrase-cli/releases/download/2.62.0/phrase_windows_setup_386.exe
- Architecture: x64
  InstallerType: inno
  InstallerUrl: https://github.com/phrase/phrase-cli/releases/download/2.62.0/phrase_windows_setup.exe
- Architecture: x86
  InstallerType: portable
  InstallerUrl: https://github.com/phrase/phrase-cli/releases/download/2.62.0/phrase_windows_386.exe
- Architecture: x64
  InstallerType: portable
  InstallerUrl: https://github.com/phrase/phrase-cli/releases/download/2.62.0/phrase_windows_amd64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/phrase/phrase-cli/blob/HEAD/CHANGELOG.md
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Features
    - repo_syncs: add API docs for create endpoint [SCD-933] (#1113) (3f65e16)
    - tags: Add q search param to tags list endpoint (#1122) (b1342c6)
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/phrase/phrase-cli/blob/HEAD/CHANGELOG.md#2620-2026-05-05
ReleaseTime: 2026-05-06T12:45:15.0000000Z
