Version: 1.18.2
Installer:
- Architecture: x64
  InstallerUrl: https://releases.aptakube.com/Aptakube_1.18.2_x64_en-US.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    😎 Improvements
    - Added an option to paste from clipboard into In-App Terminal using Mouse Right Click
    🐞 Bugs Fixed
    - Fixed an issue with theme not loading correctly
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/aptakube/aptakube/releases/tag/1.18.2
ReleaseTime: 2026-07-02T14:23:34.0000000Z
