Version: 1.16.0
Installer:
- Architecture: x64
  InstallerUrl: https://releases.aptakube.com/Aptakube_1.16.0_x64_en-US.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    ✨ What's new
    - Aptakube now has a custom human-friendly UI for Argo Applications, Argo Rollout, Cert-Manager and Gateway API, replacing the previous generic UI that only showed Spec and Status as YAML. Let me know if you have any suggestions on how to make this UI better, or if there's any other CRD you use frequently and would like to see a custom UI.
    - Workload and Cluster Overview now also include status for Argo Applications, Argo Rollout and Certificates, but only if CRD is installed.
    - Migrated events tab from "core/v1" to "events.k8s.io/v1"
    😎 Improvements
    - Improved how we display conditions for Deployments making it easier to understand when it's stuck on a rollout
    - Cmd/Ctrl+F will now auto-select existing filter text like browsers do #527
    - 
    🐞 Bugs Fixed
    - fixed how we parse “1G” on Resource Quota as it was previously being parsed as "1" instead of "1 Billion"
    - fix the "undefined" status on CRD Status Overview #526
    - fixed this navigation bug with Gateway resources #529
    - fixed a display issue with a large number of Pod status on Workload Overview Discord
    📸 Screenshots
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/aptakube/aptakube/releases/tag/1.16.0
ReleaseTime: 2026-04-13T08:25:51.0000000Z
