Version: 1.0.20
Installer:
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  InstallerUrl: https://github.com/larksuite/cli/releases/download/v1.0.20/lark-cli-1.0.20-windows-amd64.zip
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  InstallerUrl: https://github.com/larksuite/cli/releases/download/v1.0.20/lark-cli-1.0.20-windows-arm64.zip
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Changelog
    - f6f242ed57d230552720bc47e22d4ea3c8b78f1a chore(release): v1.0.20 (#682)
    - 20fba1e601fa4377c89c91d18f9ffe84ac4ce681 chore(whiteboard): Manual disable edge case for svg compatible (#661)
    - 8ec95a4e393c629d9cced98fe22e1ee64d990a4f docs(lark-drive): add missing import command examples (#669)
    - 1e2144ee08449c4cf7b0fa6a79da45ad36fe4557 docs(readme): add Project (Meegle) to Features table (#660)
    - 7124b18baa8c64cbc83b6043ec1c569e2361e632 docs(skills): clarify minutes routing semantics (#591)
    - aa48d70d7ac19b3db342f0955115dfa8a2519f18 feat(drive): add +search shortcut with flat filter flags (#658)
    - 97f817d0886fafbb282a7c504d38049f7c2f4e45 feat(im): add at-chatter-ids filter to +messages-search (#612)
    - 834a899e2b84e95e65fc04f818d135a82b0fe65e feat(lark-im): add chat.members.bots to skill docs (#616)
    - 2e7a11a8e8c6c0400c1d0371aed4dac2fd8315c0 feat(mail): support sharing emails to IM chats (#637)
    - ddf6f0cb7d08e398bfdaa02634039887ee4f2364 feat(pagination): preserve pagination state on truncation and natural… (#659)
    - 78d92de6afbbb7280761f98fe678be024f578998 feat: add calendar update shortcut (#678)
    - fe9dc4ce6a44f77b7f20f05ad330ff4198c39036 fix(strict-mode): reject explicit --as instead of silently overriding it (#673)
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/larksuite/cli/releases/tag/v1.0.20
ReleaseTime: 2026-04-27T12:28:09.0000000Z
