Version: 1.0.73
Installer:
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  InstallerUrl: https://github.com/larksuite/cli/releases/download/v1.0.73/lark-cli-1.0.73-windows-amd64.zip
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  InstallerUrl: https://github.com/larksuite/cli/releases/download/v1.0.73/lark-cli-1.0.73-windows-arm64.zip
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Changelog
    - b52677269eb1fa5dd4d3fada8a048535f946af50 [codex] support bot menu events (#1765)
    - 78390f8ea14fc68e41882b96061d6efbc1127065 chore(slides): update lark-slides skill to 0715 snapshot (#1933)
    - 7b989948c4aa99b1abafef172cbf2d771f0e3d37 docs(base): reduce filter and update retry loops (#1879)
    - 79adf89bebe262e5fd870262b3ba12232d0d9663 docs(vc): default transcript routing to smart notes over minutes (#1961)
    - 3c2cc273f72cad51261afdca6ca873cacfbfda1f feat(apps): design_html support, creative-design skill, unified TOS publish (#1901)
    - 4cdfa2fcda0ecf3b1d0b5f30e5e695e9a9f07e71 feat(whiteboard): enhance whiteboard svg parser (#1970)
    - fb57e179052f5ec607b1edebf29b487ede101215 feat: check room availability for calendar +update (#1965)
    - 44514ad1143817d0f407d4f1c0db8a537539ad29 fix(slides): detect visual elements outside canvas
    - 21cff2e2dd14b667d6c284bfd7d86050406fba8a fix: reduce public content credential fixture false positives
    - 6ff10229fdc94b2194be4b6c2504c63bb657d9f7 fix: standardize CLI shortcut text in English (#1942)
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/larksuite/cli/releases/tag/v1.0.73
ReleaseTime: 2026-07-20T13:46:36.0000000Z
