Version: 8.0.7.0
Installer:
- InstallerUrl: https://downloads.nordcdn.com/apps/windows/NordVPN/8.0.7.0/NordVPNInstall.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    All journeys start at Home. We're excited to bring a new design that reduces unnecessary distractions and helps you focus on what matters most.

    * Your go-to connection buttons now have the spotlight, ready to take you to your preferred locations with just a click.

    * The Search expanded to cover more ground, so you can find countries, servers, and even Meshnet devices all in one place.

    * The updated statistics section shows how long your connection stayed secure to give you a quick snapshot of your online habits.
