Version: 1.123.1
Installer:
- Architecture: x86
  InstallerUrl: https://desktop-release.canva.cn/Canva Setup 1.123.1-cn.exe
  InstallationMetadata:
    DefaultInstallLocation: '%LOCALAPPDATA%\Programs\Canva'
    Files:
    - RelativeFilePath: Canva.exe
      FileType: launch
      FileSha256: 6F20709166DE3C9BB1862CFC4F86AAD514141C10852529868143264534900539
- Architecture: x64
  InstallerUrl: https://desktop-release.canva.cn/Canva Setup 1.123.1-cn.exe
  InstallationMetadata:
    DefaultInstallLocation: '%LOCALAPPDATA%\Programs\Canva'
    Files:
    - RelativeFilePath: Canva.exe
      FileType: launch
      FileSha256: 022A4B1D48475256862D7B3E25B708E610F93DD833A04623D15FCCA7CC18AC0E
Locale: []
ReleaseTime: 2026-07-29T03:13:04.5680000Z
