Version: "20260630"
Installer:
- InstallerUrl: http://dl-t1.wmzhe.com/13/13163/PureCodec20260630.exe
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    + 更新 PotPlayer v260630(1.7.22977)
    + 更新 MPC-BE v1.9.0
    + 更新 MPC-HC v2.7.3
    + 更新 LAV Filters v0.82
    + 更新 MPC Video Renderer v0.10.5.2552
    + 更新 Icaros v3.3.6
ReleaseTime: 2026-06-30
