Version: 0.5.5
Installer:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/chaitanyagiri/munder-difflin/releases/download/v0.5.5/Munder-Difflin-0.5.5-win-x64-setup.exe
Locale:
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/chaitanyagiri/munder-difflin/releases/tag/v0.5.5
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/chaitanyagiri/munder-difflin/blob/HEAD/CHANGELOG.md
ReleaseTime: 2026-10-01T21:00:56.0000000Z
