Version: 262.8665.81
Installer:
- Architecture: x64
  InstallerUrl: https://download.jetbrains.com/idea/idea-262.8665.81.exe
  ProductCode: IntelliJ IDEA 262.8665.81
  InstallerSha256: FC52BF97461AB08183E66C816CDC7A6C13326EC05A36EA0B3412FD00D4B0B756
- Architecture: arm64
  InstallerUrl: https://download.jetbrains.com/idea/idea-262.8665.81-aarch64.exe
  ProductCode: IntelliJ IDEA 262.8665.81
  InstallerSha256: 8C8D7860BF55A2A9A2A14B078CE2F41D57D0A5338D04737E5936B933E894312F
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: IntelliJ IDEA 2026.2 Beta is out! For the list of changes included in this build, refer to the release notes.
- Key: ReleaseNotesUrl
  Value: https://youtrack.jetbrains.com/articles/IDEA-A-2100662704
ReleaseTime: 2026-07-02
