Version: 263.4732.28
Installer:
- Architecture: x64
  InstallerUrl: https://download.jetbrains.com/idea/idea-263.4732.28.exe
  ProductCode: IntelliJ IDEA 263.4732.28
  InstallerSha256: 2A7339B816FD48ED5ACEDFEBE36339FCA93E2A63B0A0AC7751E1B01F8541F722
- Architecture: arm64
  InstallerUrl: https://download.jetbrains.com/idea/idea-263.4732.28-aarch64.exe
  ProductCode: IntelliJ IDEA 263.4732.28
  InstallerSha256: FA0C8CBF60AD8D255DB8E0ABDF6D99496FE7D681D9C5F07F01DC94560532A996
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    IntelliJ IDEA 2026.3 EAP 2 is out!
    For the list of changes included in this build, refer to the release notes.
- Key: ReleaseNotesUrl
  Value: https://youtrack.jetbrains.com/articles/IDEA-A-2100662740
ReleaseTime: 2026-09-11
