Version: 1.1.19.1
Installer:
- InstallerUrl: https://www.eizoglobal.com/support/db/files/software/software/lcd/ScreenInStyle/1.1.19_client/SIS1119_Setup.exe
- InstallerLocale: ja-JP
  InstallerUrl: https://www.eizo.co.jp/support/db/files/software/public/lcd/ScreenInStyle/1.1.19_client/SIS1119_Setup.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - Added support for EV3451X and EV3851X
    - Updated End User License Agreement
