Version: 7.1.20
Installer:
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  InstallerUrl: https://github.com/router-for-me/CLIProxyAPI/releases/download/v7.1.20/CLIProxyAPI_7.1.20_windows_amd64.zip
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Changelog
    - cecd39317de70fd6ce108e8cfd9577f4b4855f8b Merge pull request #3498 from router-for-me/test
    - aaec9194d54946fc89a97a2c888e9400470c3d97 feat(models): add Grok Build 0.1 to registry
    - 3c62a9a9b0175c8bba5d49687d0608c9e60a274e fix(auth): update import paths to v7 for registry and executor
    - 33f4904b2524636ae2055f9f0c30d045bd790c32 fix(translator): handle system role as developer in Claude request conversion
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/router-for-me/CLIProxyAPI/releases/tag/v7.1.20
ReleaseTime: 2026-05-23T20:51:47.0000000Z
