Version: 6.9.21
Installer:
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  InstallerUrl: https://github.com/router-for-me/CLIProxyAPI/releases/download/v6.9.21/CLIProxyAPI_6.9.21_windows_amd64.zip
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Changelog
    - 2a97037d7b259e0a07de502e7d45c52b3f3881d6 Merge pull request #2670 from sususu98/feat/antigravity-prefer-prod-url
    - d8013938411a3bd9e7b7cf0940ca3f86148bd5c7 feat(antigravity): prefer prod URL as first priority
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/router-for-me/CLIProxyAPI/releases/tag/v6.9.21
ReleaseTime: 2026-04-10T12:02:52.0000000Z
