Version: 7.1.23
Installer:
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  InstallerUrl: https://github.com/router-for-me/CLIProxyAPI/releases/download/v7.1.23/CLIProxyAPI_7.1.23_windows_amd64.zip
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Changelog
    - b5959c313df73175644afff4cebbd4eedc8b04ad Merge pull request #3554 from sususu98/fix/gemini-cli-request-schema-cleanup
    - e399edd3cc9aaa5b42702f792df8a5aae9212206 feat(images): add support for configurable GPT Image 2 base model and improved SSE handling
    - 70a8cf026f0047c79424a190661a66f5ddc058ae fix: clean gemini cli request schemas
    - 4a85b6b97e19de77b0ffd57baa6af8dc8d20304d fix: log gemini cli schema cleanup errors
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/router-for-me/CLIProxyAPI/releases/tag/v7.1.23
ReleaseTime: 2026-05-26T16:54:40.0000000Z
