Version: 6.9.26215
Installer:
- InstallerUrl: https://support.broadcastradio.com/products/Myriad/v6/v6.9.26215/Service/BRMyriadManagementSvc6.msi
Locale:
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://support.broadcastradio.com/products/Myriad/v6/v6.9.26215/Service/MyriadManagementSvc6VersionHistory.html
- Locale: en-US
  Key: ReleaseNotes
  Value: No new features or significant changes.
ReleaseTime: 2026-09-03T11:30:31.0000000Z
