Version: 263.6259.39
Installer:
- Architecture: x64
  InstallerUrl: https://download.jetbrains.com/cpp/CLion-263.6259.39.exe
  ProductCode: CLion 263.6259.39
  InstallerSha256: CF2C971131BEB9D86A617E404E3232941ED58A254073ADA925E6D59218010125
- Architecture: arm64
  InstallerUrl: https://download.jetbrains.com/cpp/CLion-263.6259.39-aarch64.exe
  ProductCode: CLion 263.6259.39
  InstallerSha256: C3B14ABE45B41BDB6F433C949E3924840A7ECD6F3582C29A85BA62A298B20190
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    A new EAP build for CLion 2026.3 is now available. This update includes several important improvements and fixes.
    Give this build a try, share your feedback, and report any issues to our issue tracker.
    Thank you for using CLion!
- Key: ReleaseNotesUrl
  Value: https://youtrack.jetbrains.com/articles/CPP-A-230654562
ReleaseTime: 2026-10-02
