Version: 1.9.20
Installer:
- InstallerType: nullsoft
  InstallerUrl: https://github.com/gaoyangz77/rivonclaw/releases/download/v1.9.20/TK-Copilot.Setup.1.9.20.exe
Locale:
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/gaoyangz77/rivonclaw/releases/tag/v1.9.20
ReleaseTime: 2026-09-22T06:53:51.0000000Z
