Version: 1.8.78
Installer:
- InstallerType: nullsoft
  InstallerUrl: https://github.com/gaoyangz77/rivonclaw/releases/download/v1.8.78/RivonClaw.Setup.1.8.78.exe
Locale:
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/gaoyangz77/rivonclaw/releases/tag/v1.8.78
ReleaseTime: 2026-07-21T18:31:38.0000000Z
