Version: 1.8.53
Installer:
- InstallerType: nullsoft
  InstallerUrl: https://github.com/gaoyangz77/rivonclaw/releases/download/v1.8.53/RivonClaw.Setup.1.8.53.exe
Locale:
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/gaoyangz77/rivonclaw/releases/tag/v1.8.53
ReleaseTime: 2026-07-07T13:19:39.0000000Z
