Version: 1.8.69
Installer:
- InstallerType: nullsoft
  InstallerUrl: https://github.com/gaoyangz77/rivonclaw/releases/download/v1.8.69/RivonClaw.Setup.1.8.69.exe
Locale:
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/gaoyangz77/rivonclaw/releases/tag/v1.8.69
ReleaseTime: 2026-07-12T16:56:42.0000000Z
