Version: 0.91.3
Installer:
- Architecture: x64
  InstallerType: inno
  InstallerUrl: https://github.com/xiufengsun/TokenTracker/releases/download/v0.91.3/TokenTracker-Setup.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    What's Changed
    - feat(sync): 将 Grok Build 用量记入项目用量 by @Roomen in https://github.com/xiufengsun/TokenTracker/pull/490
    Full Changelog: https://github.com/xiufengsun/TokenTracker/compare/v0.91.2...v0.91.3
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/xiufengsun/TokenTracker/releases/tag/v0.91.3
ReleaseTime: 2026-08-21T10:24:51.0000000Z
