Version: 1.3.20
Installer:
- InstallerUrl: https://aibot-install-cdn.easyclaw.cn/public/package/easyclawcnsetup.exe
  InstallerSha256: 91624B7BAD6B5D699021E8E9F8517A28EFDBD13BAC6D740D6030E6EBC14B915C
Locale: []
ETag:
- '"af4a6ecad1f37d5cb3d17ad248aa8a80-27"'
