Version: 1.2.43
Installer:
- InstallerUrl: https://qn.cache.wpscdn.cn/lingxi-ai/win/1.2.43/lingxi-desktop-1.2.43-setup.exe
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    - 上线 plan 模式，自动拆解复杂任务
    - PPT 去 AI 味，视觉风格更贴近真人手工制做
    - 图片生成质量提升
    - 支持激活桌面宠物
    - 其他界面交互优化与问题修复
ReleaseTime: 2026-08-29T16:12:47.3690000Z
