Version: 2.4.6
Installer:
- Architecture: x64
  InstallerUrl: https://dl.koodoreader.com/v2.4.6/Koodo-Reader-2.4.6-x64.exe
- Architecture: arm64
  InstallerUrl: https://dl.koodoreader.com/v2.4.6/Koodo-Reader-2.4.6-arm64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    New Features
    - The table of content now displays the number of pages by default; there is no need to enable the “Total Pages” feature separately.
    - Software security has been optimized to address an arbitrary code execution vulnerability caused by metadata.
    - An additional confirmation step has been added when importing books via external links using the URL scheme to enhance security.
    - The “Ask AI” feature now supports the Ctrl + Enter shortcut for submitting questions.
    - Added an eraser tool to Doodle Mode
    - Added support for 7 languages on the official website
    - (Mobile) Added a feature to resync all book covers; go to Settings > Sync options
    - (Mobile) Optimized the smoothness of page-turning animations
    - (Mobile) Optimized the smoothness of certain app animations
    - (Mobile) Added an option to download images in CBZ comic mode
    Fixes
    - Fixed an issue where footnotes in some books did not appear in a pop-up window
    - Fixed an issue where reading progress could not be tracked for some books containing special styles
    - Fixed an issue where table of contents highlighting did not work after enabling “Total Pages”
    - Fixed an issue where page numbers were not displayed in the table of contents for some TXT books
    - (Mobile) Fixed an issue where authorization via the browser failed on older iOS versions, resulting in a blank page
    - (Mobile Version) Fixed abnormal slider behavior on iOS
    - (Mobile Version) Fixed an issue where swiping on an image triggered image preview in scroll mode
    - (Mobile Version) Fixed an issue where text could not be selected in the Android version after enabling recommended layout under certain conditions
    - (Mobile Version) Fixed stuttering issues when enabling TTS for some book
    - (Mobile) Fixed an issue on iOS where the horizontal bar in the bottom navigation bar did not automatically hide during reading
    - (Mobile) Fixed an issue where footnotes for some books did not appear in a pop-up window
    - (Mobile) Fixed an issue where reading progress could not be tracked for some books containing special styles
    - (Mobile) Fixed an issue where page numbers were not displayed on the table of contents for some TXT books
    Tip
    You can also download the installation package for this version from the our self-hosted mirror.
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    新增
    - 现在目录默认展示页数，不需要额外启用总页数功能
    - 优化软件安全性，解决由元数据导致的任意代码执行漏洞
    - 通过 url scheme 导入外部链接的图书时，增加额外的确认步骤以提升安全性
    - AI 问书增加 Ctrl + Enter 快捷键用于发送问题
    - 涂鸦模式新增橡皮擦功能
    - 官网增加对 7 门语言的支持
    -（移动版）新增重新同步全部图书封面的功能，请前往设置-同步选项
    -（移动版）优化平滑翻页动画流畅度
    -（移动版）优化部分应用动画的流畅度
    -（移动版）CBZ 漫画模式下新增下载图片的选项
    修复
    - 修复部分图书脚注不弹窗显示的问题
    - 修复部分包含特殊样式的图书无法记录阅读进度
    - 修复启用总页数之后，目录高亮失效的问题
    - 修复部分 TXT 图书目录页数不显示的问题
    -（移动版）修复在低版本 iOS 系统上无法通过浏览器完成授权，页面一片空白的问题
    -（移动版）修复 iOS 版滑块操作异常
    -（移动版）修复滚动模式下，在图片上滑动会触发预览图片的问题
    -（移动版）修复部分情况下，安卓版启用推荐排版之后，无法选择文字的问题
    -（移动版）修复部分图书听书时的卡顿问题
    -（移动版）修复 iOS 版阅读时底部导航栏横条不自动隐藏的问题
    -（移动版）修复部分图书脚注不弹窗显示的问题
    -（移动版）修复部分包含特殊样式的图书无法记录阅读进度
    -（移动版）修复部分 TXT 图书目录页数不显示的问题
    Tip
    我们还提供了高速下载镜像，您也可以从 自托管镜像 下载此版本的安装包
- Key: ReleaseNotesUrl
  Value: https://github.com/koodo-reader/koodo-reader/releases/tag/v2.4.6
ReleaseTime: 2026-10-07T00:29:56.0000000Z
