Version: "2026.2"
Installer:
- InstallerUrl: https://github.com/TranslucentTB/TranslucentTB/releases/download/2026.2/bundle.msixbundle
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    New features
    - Add CTRL+ALT+SHIFT+F1 shortcut to reset dynamic state (thanks to @Wahid7852)
    Bug fixes
    - Make the app more resilient against re-entrency, reducing crashes.
    - Fix bugs where the app would not be able to update the taskbar on certain monitors.
    - Watch for package updates in the TAP
    - Avoid ExplorerHooks in modern XAML taskbar
    - Fix a few resource leaks in the TAP
    - Fix the application not closing if you had a window previously interrupt shutdown
- Key: ReleaseNotesUrl
  Value: https://github.com/TranslucentTB/TranslucentTB/releases/tag/2026.2
ReleaseTime: 2026-08-31T21:01:53.0000000Z
RealVersion: 2026.2.0.0
