Version: 7.8.0
Installer:
- Architecture: x86
  InstallerUrl: https://open.u-tools.cn/download/uTools-7.8.0-ia32.exe
  AppsAndFeaturesEntries:
  - DisplayVersion: 7.8.0-ia32
- Architecture: x64
  InstallerUrl: https://open.u-tools.cn/download/uTools-7.8.0.exe
  AppsAndFeaturesEntries:
  - DisplayVersion: 7.8.0
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    【新增】重构团队空间，增加插件应用是否共享给成员使用或仅限自己使用
    【优化】其他已知 bug 修复及优化
ReleaseTime: 2026-04-14
