Version: 1.2.99.317.g9bd8c54d
Installer:
- Architecture: x64
  InstallerUrl: https://download.scdn.co/SpotifyFullSetupX64.exe
  InstallerSha256: 29BF2FACC6C0061DBD9B517E922B4131E494A7C4117C7D9017EC54A6ADCF3844
- Architecture: arm64
  InstallerUrl: https://download.scdn.co/SpotifyFullSetupARM64.exe
Locale: []
ETag:
- '"eb8fde04badd0f740d1b075c3ec924ff"'
ETagARM64:
- '"cedb4664ee8c8fea7ddb3af241671f7b"'
