Version: 18.2.2.10
Installer:
- Architecture: x86
  InstallerUrl: https://dl.bitsum.com/files/processlassosetup32.exe
  InstallerSha256: A08DC5D292284EDADBE72F149E8934C2D37349F756383B502B531ED5740D6E3A
- Architecture: x64
  InstallerUrl: https://dl.bitsum.com/files/processlassosetup64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - Minor fixes and enhancements
    (1) GUI: Add additional GPU enumeration data to diagnostics report
    (1) GUI: Fix an issue where a phantom iGPU adapter could appear on some multi-GPU systems
    (3) Core: Fix an issue when Foreground Boosting was enabled but the promoted priority class was set to “none”
    (9) GUI: Assorted optimizations to per-process GPU utilization collection
ReleaseTime: 2026-06-05
ETag:
- '"42029-279250-6537e7cb7f217"'
ETagX64:
- '"4202a-2b7a88-6537e7cee19dd"'
