Version: 3.8.1
Installer:
- InstallerUrl: https://downloads.nordlayer.com/win/latest/NordLayerSetup.exe
  ProductCode: '{C12DAC2F-44F9-436F-89F1-32CB69B4F897}'
  AppsAndFeaturesEntries:
  - ProductCode: '{C12DAC2F-44F9-436F-89F1-32CB69B4F897}'
    UpgradeCode: '{FD46564A-C63E-4E8D-854D-B5B1DDAAFCE4}'
    InstallerType: msi
Locale: []
RealVersion: 3.8.0.0
