Version: 1.2.3
Installer:
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  InstallerUrl: https://github.com/3899/ncmm/releases/download/v1.2.3/ncmm_Windows_x86_64.zip
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  InstallerUrl: https://github.com/3899/ncmm/releases/download/v1.2.3/ncmm_Windows_arm64.zip
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    版本信息
    - 版本：v1.2.3
    - 构建时间：2026-09-22 14:23:14 (北京时间)
    - 发布类型：最新正式版（latest release）
    更新记录
    💫 体验优化
    - update:changelog.md
    - ci: remove commit hash from release notes template
    - ci: update workflows to build in ncmm-code and publish to public ncmm
    🐞 bug 修复
    - fix:乐迷图加速任务[评论 ta 的笔记]
    - fix(core): 同步插件参数解析、配置级联探测与提现脚本优化
    - fix(scripts): ncmm-withdraw-run.py 智能合并命令行参数与默认秒杀配置
- Locale: zh-CN
  Key: ReleaseNotesUrl
  Value: https://github.com/3899/ncmm/releases/tag/v1.2.3
ReleaseTime: 2026-09-22T06:26:26.0000000Z
