Version: 3.1.2
Installer:
- Architecture: x64
  InstallerType: inno
  InstallerUrl: https://github.com/RyanYuuki/AnymeX/releases/download/v3.1.2/AnymeX-x86_64-3.1.2-Installer.exe
Locale:
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/RyanYuuki/AnymeX/releases/tag/v3.1.2
ReleaseTime: 2026-08-02T16:13:19.0000000Z
