Version: 3.2.5
Installer:
- InstallerUrl: https://app.123957.com/pc-pro/windows/325/123pan_3.2.5.exe
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    【优化】会员中心交互，"会员中心"升级为"商品中心"
    【优化】搜索结果分词匹配优先级，查找更方便
    【修复】常见问题中视频转码抵扣比例表格不展示的问题
    【修复】公告弹窗跳转错误、登录状态丢失等若干已知问题
ReleaseTime: 2026-09-18T02:47:21.0000000Z
RealVersion: 3.2.5.0
