Version: 7.0.0.7486
Installer:
- InstallerType: exe
  InstallerUrl: https://cdn.zoom.us/prod/7.0.0.7486/x64/zoomrooms-7.0.0.7486-x64.exe
- InstallerType: msi
  InstallerUrl: https://cdn.zoom.us/prod/7.0.0.7486/x64/zoomrooms-7.0.0.7486-x64.msi
Locale: []
RealVersion: 7.0.0
