Version: 0.8.1
Installer:
- Architecture: x64
  InstallerUrl: https://github.com/SuperGness/codey/releases/download/v0.8.1/Codey-0.8.1-windows-x64-setup.exe
Locale:
- Locale: zh-CN
  Key: ReleaseNotesUrl
  Value: https://github.com/SuperGness/codey/releases/tag/v0.8.1
- Locale: zh-CN
  Key: ReleaseNotes
  Value: 'Full Changelog: https://github.com/SuperGness/codey/compare/v0.8.0...v0.8.1'
ReleaseTime: 2026-08-19T09:15:59.0000000Z
