Version: 0.9.0
Installer:
- Architecture: x64
  InstallerUrl: https://github.com/SuperGness/codey/releases/download/v0.9.0/Codey-0.9.0-windows-x64-setup.exe
Locale:
- Locale: zh-CN
  Key: ReleaseNotesUrl
  Value: https://github.com/SuperGness/codey/releases/tag/v0.9.0
- Locale: zh-CN
  Key: ReleaseNotes
  Value: 'Full Changelog: https://github.com/SuperGness/codey/compare/v0.8.10...v0.9.0'
ReleaseTime: 2026-08-26T11:51:07.0000000Z
