Version: 8.1.2.0
Installer:
- Architecture: x86
  InstallerUrl: https://download.ticktick.app/download/win/tick_win_setup_release_x86_8120.exe
- Architecture: x64
  InstallerUrl: https://download.ticktick.app/download/win64/tick_win_setup_release_x64_8120.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Group & Sort Improvements
    - Added Created Time Grouping to quickly find recently added tasks.
    - Added Created Time and Modified Time Sorting to quickly find recently created and updated tasks.
    - Added Sort Order to view the newest items first with Newest First.
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    分组&排序体验优化
    - 新增创建时间分组，快速查看近期新增内容。
    - 新增创建时间、修改时间排序，方便回顾新增任务和近期更新内容。
    - 新增排序方向，可以选择“从新到旧”查看最新内容。
ReleaseTime: 2026-07-10
