Version: 26.04-7455
Installer:
- Architecture: x64
  InstallerType: appx
  InstallerUrl: https://cdn.kde.org/ci-builds/graphics/okular/release-26.04/windows/okular-release_26.04-7455-windows-cl-msvc2022-x86_64-sideload.appx
Locale: []
RealVersion: 26.402.7455.0
