Version: 0.0.62
Installer:
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  InstallerUrl: https://github.com/browseros-ai/BrowserOS/releases/download/claw-server/v0.0.62/browseros-claw-server-rust-resources-windows-x64.zip
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - fix(neo): activate staged extension updates through CDP (#2809) (89b3b1eee)
    - fix(claw): replace cockpit replay previews with bounded screenshots (be9b1194f)
    - chore: bump Claw server version to 0.0.61 (#2808) (6e4fe0a73)
    - chore(release): snapshot browserclaw server alpha v0.0.61 (cce871575)
    - chore: bump browserclaw extension version to 0.2.28.0 (#2804) (79040b269)
    - chore(release): update extension alpha feeds to 0.2.28.0 (70667d584)
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/browseros-ai/BrowserOS/releases/tag/claw-server/v0.0.62
ReleaseTime: 2026-10-02T20:58:07.0000000Z
