Version: 0.13.1
Installer:
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://github.com/nearai/ironclaw/releases/download/v0.13.1/ironclaw-x86_64-pc-windows-msvc.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Release Notes
    Added
    - add Brave Web Search WASM tool (#474)
    Fixed
    - (web) auto-scroll and Enter key completion for slash command autocomplete (#475)
    - correct download URLs for telegram-mtproto and slack-tool extensions (#470)
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/nearai/ironclaw/releases/tag/v0.13.1
ReleaseTime: 2026-03-02T22:23:24.0000000Z
