Version: 0.1.252
Installer:
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  InstallerUrl: https://github.com/posit-dev/ark/releases/download/0.1.252/ark-0.1.252-windows-x64.zip
Locale:
- Key: ReleaseNotesUrl
  Value: https://github.com/posit-dev/ark/releases/tag/0.1.252
ReleaseTime: 2026-06-19T14:56:08.0000000Z
