Version: 156.0.8063.3
Installer:
- Architecture: x86
  InstallerUrl: https://dl.google.com/release2/chrome/docgfgbg3feqxwsgbfr5xhgige_156.0.8063.3/156.0.8063.3_chrome_installer_uncompressed.exe
- Architecture: x64
  InstallerUrl: https://dl.google.com/release2/chrome/ac3glx6fr7eq65lubns25l2saeoq_156.0.8063.3/156.0.8063.3_chrome_installer_uncompressed.exe
- Architecture: arm64
  InstallerUrl: https://dl.google.com/release2/chrome/lztd2gwd4bz6bmpdaeixlojlbm_156.0.8063.3/156.0.8063.3_chrome_installer_uncompressed.exe
Locale: []
