Version: 3.0.1.0
Installer:
- InstallerLocale: en-US
  InstallerUrl: https://download.cpuid.com/cpu-z/cpu-z_3.01-en.exe
- InstallerLocale: zh-CN
  InstallerUrl: https://download.cpuid.com/cpu-z/cpu-z_3.01-cn.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: '- CPU-Z Validator V3 (more information *at that address*).'
RealVersion: "3.01"
ReleaseTime: 2026-08-20
