Version: 2.2.1.0
Installer:
- InstallerLocale: en-US
  InstallerUrl: https://download.cpuid.com/cpu-z/cpu-z_2.21-en.exe
- InstallerLocale: zh-CN
  InstallerUrl: https://download.cpuid.com/cpu-z/cpu-z_2.21-cn.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - AMD EXPO-ULL SPD memory profiles.
    - AMD Radeon RX 9050 (Navi 44).
    - Preliminary support of Lisuan 7G100 GPU.
RealVersion: "2.21"
ReleaseTime: 2026-08-17
