Version: 1.0.47
Installer:
- Architecture: x64
  InstallerType: portable
  InstallerUrl: https://github.com/iOfficeAI/OfficeCLI/releases/download/v1.0.47/officecli-win-x64.exe
- Architecture: arm64
  InstallerType: portable
  InstallerUrl: https://github.com/iOfficeAI/OfficeCLI/releases/download/v1.0.47/officecli-win-arm64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: 'Full Changelog: https://github.com/iOfficeAI/OfficeCLI/compare/v1.0.46...v1.0.47'
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/iOfficeAI/OfficeCLI/releases/tag/v1.0.47
ReleaseTime: 2026-04-14T17:20:14.0000000Z
