Version: 0.32.12
Installer:
- InstallerType: inno
  InstallerUrl: https://github.com/ollama/ollama/releases/download/v0.32.12/OllamaSetup.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Qwen 3.8 - 27B model support
    This release adds the support of Qwen 3.8 27B.
    For Apple Silicon devices, Ollama has in particular optimized for maximum performance and output quality suitable for repeated tasks and coding agents.
    Qwen 3.8 model page:
    https://ollama.com/library/qwen3.8
    Qwen3.8 delivers substantial gains across coding, professional work, research, and long-horizon agentic tasks.
- Key: ReleaseNotesUrl
  Value: https://github.com/ollama/ollama/releases/tag/v0.32.12
ReleaseTime: 2026-08-14T16:37:00.0000000Z
