Version: 6.0.1.0410
Installer:
- InstallerUrl: https://download.qnap.com/Storage/Utility/QNAPQsyncClientWindows-6.0.1.0410.exe
- InstallerLocale: zh-CN
  InstallerUrl: https://download.qnap.com.cn/Storage/Utility/QNAPQsyncClientWindows-6.0.1.0410.exe
Locale: []
ReleaseTime: 2026-04-23T06:58:00.0000000Z
