Version: 0.0.3.1276
Installer:
- InstallerUrl: https://cstore-pub-cos-seewo-report-tx.seewo.com/seewo-report_uwiwypvihhulnhlwhxiqlxozxyphihhh?sign=q-sign-algorithm%3Dsha1%26q-ak%3DAKIDJUXMxJRLzPaeMp20jDSTFl23pLcdPwDF%26q-sign-time%3D1778492186%3B2093852186%26q-key-time%3D1778492186%3B2093852186%26q-header-list%3Dhost%26q-url-param-list%3Dresponse-content-disposition%26q-signature%3D774ed5dca5a89930b361360dd0388b5096c76154&response-content-disposition=attachment%3Bfilename%3D%22SeewoIwbAssistant_0.0.3.1276.exe%22%3Bfilename%2A%3Dutf-8%27%27SeewoIwbAssistant_0.0.3.1276.exe
Locale: []
