Version: 5.0.0.2008
Installer:
- Architecture: x86
  InstallerUrl: https://software.sonicwall.com/GlobalVPNClient/GVCSetup-Win32_5.0.0.2008.exe
  InstallerSha256: A5CA2B31C5B56D7DC616DFC7B1D3D3AB557363FEC4E207EEB6067AC4C34AFE14
- Architecture: x64
  InstallerUrl: https://software.sonicwall.com/GlobalVPNClient/GVCSetup-x64_5.0.0.2008.exe
Locale: []
ETag:
- '"b0169ed88212dd1:0"'
ETagX64:
- '"ef4e18fd8212dd1:0"'
