Version: 20.1.0
Installer:
- InstallerUrl: https://github.com/Cosebdd/ShareNot/releases/download/v20.1.0/ShareNot-20.1.0-setup-x64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: 'The official changelog: https://getsharex.com/changelog#v20.1.0'
- Key: ReleaseNotesUrl
  Value: https://github.com/Cosebdd/ShareNot/releases/tag/v20.1.0
ReleaseTime: 2026-05-11T07:17:42.0000000Z
