Version: 4.9.13.30241433
Installer:
- Architecture: x64
  Scope: user
  InstallerUrl: https://codebuddy-1328495429.cos.accelerate.myqcloud.com/aiide/win32-x64-user/CodeBuddy-win32-x64-user-4.9.13.30241433-0acccacc.exe
- Architecture: x64
  Scope: machine
  InstallerUrl: https://codebuddy-1328495429.cos.accelerate.myqcloud.com/aiide/win32-x64-system/CodeBuddy-win32-x64-system-4.9.13.30241433-0acccacc.exe
Locale: []
ReleaseTime: 2026-06-09T00:23:53.0000000Z
RealVersion: 1.100.0
