Version: 2026.1.0.1
Installer:
- Architecture: x64
  InstallerUrl: https://download.jetbrains.com/rider/JetBrains.Rider-2026.1.0.1.exe
  ProductCode: JetBrains Rider 2026.1.0.1
  AppsAndFeaturesEntries:
  - DisplayVersion: 261.22158.394
  InstallerSha256: B1B6DA0B351B116B919037E96093C34BBB4DBD394EE6964DC76BF1F0EF569B4C
- Architecture: arm64
  InstallerUrl: https://download.jetbrains.com/rider/JetBrains.Rider-2026.1.0.1-aarch64.exe
  ProductCode: JetBrains Rider 2026.1.0.1
  AppsAndFeaturesEntries:
  - DisplayVersion: 261.22158.394
  InstallerSha256: D7E7BAF8C3738F3EEA30F1B95C32BD46554E81BCC4F768DD31C953265BF6C674
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Rider 2026.1.0.1 comes with the following fixes:
    In the recent 2026.1 release, native Wayland support in Rider was prematurely enabled by default on Linux. This caused compatibility issues that prevented several key UI elements such as the Monitoring and dotMemory tool windows from rendering correctly.
    We are now temporarily disabling Wayland support to restore your full access to all monitoring and profiling tools while we continue to finalize our native Wayland support.
- Key: ReleaseNotesUrl
  Value: https://youtrack.jetbrains.com/articles/DOTNET-A-261/Rider-2026.1-release-notes
ReleaseTime: 2026-04-09
