Version: 0.1.1
Installer:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/czm15053/tongbu/releases/download/v0.1.1/tongbu_0.1.1_x64-setup.exe
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: 'Full Changelog: https://github.com/czm15053/tongbu/compare/v0.1.0...v0.1.1'
- Locale: zh-CN
  Key: ReleaseNotesUrl
  Value: https://github.com/czm15053/tongbu/releases/tag/v0.1.1
ReleaseTime: 2026-09-03T06:45:03.0000000Z
