Version: 11.1.0.0
Installer:
- Architecture: x86
  InstallerType: wix
  InstallerUrl: https://downloads.pdf-xchange.com/11.1.0.0/EditorV11.x86.msi
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://downloads.pdf-xchange.com/11.1.0.0/EditorV11.x64.msi
- Architecture: arm64
  InstallerType: wix
  InstallerUrl: https://downloads.pdf-xchange.com/11.1.0.0/EditorV11.ARM64.msi
Locale:
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://www.pdf-xchange.com/product/pdf-xchange-editor/history
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    New features
    1. AI Assistant: added an option for users to add custom prompts.
    2. AI Assistant: added an option to specify the language in which the AI   should answer questions.
    3. New Open/Save File dialog box: added support for multiple OneDrive-folders and Network Locations, and added a 'Quick Access' folder.
    4. Added a 'Use system title and frame' option (Preferences > General > Tabs & Windows) to turn on/off the use of the system's title and border for the main window. This option can also help solve a possible problem under WINE where the system title may sometimes overlap the application's custom title.
    5. Added a 'Relationship' column to the attachments pane. (T# 7748) (48980)
    6. Added Brotli compression as an option when recompressing images, and for performing some other operations.
    7. Implemented handling of the fill_tab property in JS dialogs. (50011)
    Bug fixes and other updates/enhancements:
    1. Fixed the "Error [AFSLib]: File cache for specified file already exists" error that may sometimes appear when a user opens a file from a cloud-based "Place" using the new Open File dialog box.
    2. Fixed an issue with saving a document when the destination file is located on a special cloud-based document management system such as CenterDevice.
    3. Fixed rare issue with crashes on some documents during rendering. (T# 7845)
    4. Fixed "Convert Text Files to PDF" for specific encodings. (49334)
    5. Improved the accuracy of the stroke colour description for link annotations when this property is not specified in the structure. (T# 7896) (49815)
    6. Fixed an issue with layers not merging correctly. (T# 7888)
    7. Fixed an issue with applying the thickness value to Text Markup comments during import, and added support for exporting and importing rounded-corner radius values for Rectangle comments. (T# 7853) (49661)
    8. Fixed an issue where JavaScript related to AcroForms in stamps was not updated after saving. (T# 7844) (49609)
    9. Fixed an issue with dimming and overlapping in the Highlight Destination function. (T# 7903) (49991)
    10. Fixed an issue with excluding UI-commands from the 'Quick Launch' dropdown and 'Customize Toolbars > Commands' dialog box when they are disabled by Group Policy.
    11. Fixed an issue with missing thousands separators for file sizes in the "details" view of the new Open/Save dialog box. (49791)
    12. Fixed an infrequent 'not enough permissions' issue when saving documents after previewing them in the new Open/Save File dialog box if opened from cloud-based places.
    13. Fixed crashes on File Open under Wine (Linux). (49752)
    14. Fixed issues with using the MS Office Click-to-Run products (including Microsoft 365 and Office 2019/2021) inside the Office-to-PDF features. On some systems such features may not work.
    15. Fixed an issue with setting labels for measurement comments by applying corresponding comment styles that already contain custom labels.
    16. Find/Search: fixed an issue with the 'Clear' item in the dropdown list. Now it is not selectable by keyboard/auto-complete/mouse-wheel, but only by mouse. Also, the auto-complete feature there is now case-sensitive.
    17. Fixed some issues with the system's Narrator screen reader app, including it being unable to read text labels on dialog boxes.
    18. Fixed an issue with the creation date in PDF/A files.
    19. Fixed issues with the incorrect filtering of annotations. (43529)
    20. Fixed issues with rendering text in text annotations with white text.
    21. Fixed an issue where PDF documents converted from MS Word could have black areas.
    22. Fixed an issue with handling the percent character in macro strings. (49748)
    23. Fixed issues with text rendering in some specific cases. (T# 4061, 4957, 7871)
    24. Fixed a rare case of a possible crash during color conversion in some documents. (T# 7885)
    25. Fixed the incorrect appearance of "down" push button form fields that have icons. (50006)
    26. Fixed potential issues when signing documents with certificates that use the ECDSA-SHA384 algorithm.
    27. Fixed an issue where some selected page content was not copied to the clipboard.
    28. DocuSign: signatures saved in the user's DocuSign account are now available when signing documents in PDF-XChange Editor. (50063)
    29. Improved handling of align_fill in JS dialogs. (T# 7897) (49847)
    30. Changed text encoding detection for text files. (49328)
    31. Added Recents and Favorites groups to the Stamps pane. (T# 4335)
    32. Added the ability to recolour stamps. (T# 7764) (49059)
    33. Added support for letters in the auto-incrementing interactive field of the “Create Custom Stamp” feature. (T# 7904)
    34. Added the ability to search for layers by name. (T# 6644) (40856)
    35. Added the “Open new files within the active virtual desktop” option (enabled by default) and made other improvements to virtual desktop handling. (T# 7872)
    36. Added support for selecting pages related to Watermark/Background/Header & Footer/Bates Numbering settings. (T# 7858) (49729)
    37. Added an option to prevent the text in a comment pop-up from scrolling to the end when the pop-up is opened. (T# 7488)
    38. Added the ability to focus the selected page number range when opening the Page Numbering dialog box. (T# 7753) (49017)
    39. Added a highlight indicator to the currently active profile in the "Set scale" dropdown menu. (T# 7719)
    40. Fixed an issue with the 'Text Correction' tool. Closing the insert/replace comment popup by pressing Esc now returns the text cursor to the InsertText-annotation position.
    41. Improved the 'Identify Forms' tool.
    42. Improved document loading time, especially for documents that contain a dictionary object with many entries.
    43. Upgraded the Markdown plugin to use a new engine, providing full CSS support and support for LaTeX formulas.
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://www.pdf-xchange.com/product/pdf-xchange-editor/history?build=11.1.0.0
ReleaseTime: 2026-09-29T07:00:00.0000000Z
