Version: 0.0.160
Installer:
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  InstallerUrl: https://github.com/microclaw/microclaw/releases/download/v0.0.160/microclaw-0.0.160-x86_64-windows-msvc.zip
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    What's Changed
    - Fix scheduler timezone drift for recurring tasks by @everettjf in https://github.com/microclaw/microclaw/pull/199
    - feat(setup): support qwen-code provider preset by @everettjf in https://github.com/microclaw/microclaw/pull/204
    - feat(feishu): 支持表情 reaction 回复（点赞等） by @everettjf in https://github.com/microclaw/microclaw/pull/200
    - fix(telegram): skip message edits during streaming in separate_message mode by @mszzukowski in https://github.com/microclaw/microclaw/pull/202
    - fix(gateway): improve macOS install/status behavior by @everettjf in https://github.com/microclaw/microclaw/pull/206
    - fix(windows): avoid MCP startup black console flash by @everettjf in https://github.com/microclaw/microclaw/pull/207
    New Contributors
    - @mszzukowski made their first contribution in https://github.com/microclaw/microclaw/pull/202
    Full Changelog: https://github.com/microclaw/microclaw/compare/v0.0.159...v0.0.160
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/microclaw/microclaw/releases/tag/v0.0.160
ReleaseTime: 2026-03-07T04:10:51.0000000Z
