Version: 5.0.20261.4301
Installer:
- InstallerUrl: https://downloads.getfiddler.com/fiddler-classic/FiddlerSetup.5.0.20261.4301-latest.exe
Locale:
- Key: ReleaseNotesUrl
  Value: https://www.telerik.com/support/whats-new/fiddler/release-history/fiddler-v5.0.20261
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    features:
     Update application EULA
     Enable TLS 1.3 in supported HTTPS protocols
    fixes:
     Error while opening the CertMaker add-on configuration
ReleaseTime: 2026-04-30
