Version: 2.9.0.20
Installer:
- InstallerType: msix
  InstallerUrl: https://github.com/microsoft/XmlNotepad/releases/download/2.9.0.20/XmlNotepadPackage_2.9.0.20_AnyCPU.msixbundle
- InstallerType: zip
  InstallerUrl: https://github.com/microsoft/XmlNotepad/releases/download/2.9.0.20/XmlNotepadSetup.zip
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: Fix issue security advisory on DTD processing. Make default Ignore DTD option True, which is more secure.
- Key: ReleaseNotesUrl
  Value: https://github.com/microsoft/XmlNotepad/releases/tag/2.9.0.20
ReleaseTime: 2026-03-27T20:59:47.0000000Z
