Version: 2.0.6
Installer:
- Architecture: x64
  InstallerUrl: https://storage.googleapis.com/antigravity-public/antigravity-hub/2.0.6-5413878570549248/windows-x64/Antigravity-x64.exe
- Architecture: arm64
  InstallerUrl: https://storage.googleapis.com/antigravity-public/antigravity-hub/2.0.6-5413878570549248/windows-arm/Antigravity-arm64.exe
Locale: []
ReleaseTime: 2026-05-22T07:00:23.9890000Z
