Version: 3.8.0
Installer:
- Architecture: x86
  InstallerUrl: https://github.com/getsentry/sentry-cli/releases/download/3.8.0/sentry-cli-Windows-i686.exe
- Architecture: x64
  InstallerUrl: https://github.com/getsentry/sentry-cli/releases/download/3.8.0/sentry-cli-Windows-x86_64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Improvements
    - (snapshots) Upload snapshot images to the objectstore usecase chosen by the server instead of a hardcoded one (#3408)
- Key: ReleaseNotesUrl
  Value: https://github.com/getsentry/sentry-cli/releases/tag/3.8.0
ReleaseTime: 2026-09-16T14:40:17.0000000Z
