Version: 3.3.5
Installer:
- Architecture: x86
  InstallerUrl: https://github.com/getsentry/sentry-cli/releases/download/3.3.5/sentry-cli-Windows-i686.exe
- Architecture: x64
  InstallerUrl: https://github.com/getsentry/sentry-cli/releases/download/3.3.5/sentry-cli-Windows-x86_64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Performance
    - (snapshots) Parallelize image hashing with rayon (#3250)
    Fixes
    - (sourcemaps) Skip non-base64 embedded sourcemaps during injection (#3243)
- Key: ReleaseNotesUrl
  Value: https://github.com/getsentry/sentry-cli/releases/tag/3.3.5
ReleaseTime: 2026-03-30T11:19:39.0000000Z
