Version: 129.0.5823.26
Installer:
- Architecture: x86
  InstallerUrl: https://get.geo.opera.com/pub/opera_gx/129.0.5823.26/win/Opera_GX_129.0.5823.26_Setup.exe
- Architecture: x64
  InstallerUrl: https://get.geo.opera.com/pub/opera_gx/129.0.5823.26/win/Opera_GX_129.0.5823.26_Setup_x64.exe
Locale: []
