Version: 135.0.5973.85
Installer:
- Architecture: x86
  InstallerUrl: https://get.geo.opera.com/pub/opera_gx/135.0.5973.85/win/Opera_GX_135.0.5973.85_Setup.exe
- Architecture: x64
  InstallerUrl: https://get.geo.opera.com/pub/opera_gx/135.0.5973.85/win/Opera_GX_135.0.5973.85_Setup_x64.exe
Locale: []
