Version: 20.3.3
Installer:
- InstallerUrl: https://epicgames-download1.akamaized.net/Builds/UnrealEngineLauncher/Installers/Windows/EpicInstaller-20.3.3.msi?launcherfilename=EpicInstaller-20.3.3.msi
Locale: []
RealVersion: 1.3.210.0
