Version: 2026.5.18
Installer:
- InstallerUrl: https://github.com/cebby2420/via-desktop/releases/download/v2026.5.18/via-desktop-2026.5.18.Setup.exe
Locale:
- Key: ReleaseNotesUrl
  Value: https://github.com/cebby2420/via-desktop/releases/tag/v2026.5.18
ReleaseTime: 2026-05-18T15:17:12.0000000Z
