Version: 2.0.26
Installer:
- InstallerUrl: https://github.com/AutoHotkey/AutoHotkey/releases/download/v2.0.26/AutoHotkey_2.0.26_setup.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Fixed ControlGetItems/ControlGetChoice not throwing for Tab controls.
    Fixed error reporting for ComObjArray().__Enum(), if it ever fails.
    Fixed TraySetIcon("HBITMAP:" handle) without *.
- Key: ReleaseNotesUrl
  Value: https://github.com/AutoHotkey/AutoHotkey/releases/tag/v2.0.26
ReleaseTime: 2026-05-04T02:09:38.0000000Z
