Version: 1.2.2
Installer:
- Architecture: x64
  Scope: user
  InstallerUrl: https://qoder-ide.oss-accelerate.aliyuncs.com/release/1.2.2/QoderUserSetup-x64.exe
Locale: []
ReleaseTime: 2026-05-21T11:09:32.8170000Z
RealVersion: 1.106.3
