Version: 0.9.14
Installer:
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  InstallerUrl: https://github.com/looplj/axonhub/releases/download/v0.9.14/axonhub_0.9.14_windows_amd64.zip
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  InstallerUrl: https://github.com/looplj/axonhub/releases/download/v0.9.14/axonhub_0.9.14_windows_arm64.zip
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    What's Changed
    - feat: allow type editing for third-party codex/claudecode channels and make channel name clickable by @raikyou in https://github.com/looplj/axonhub/pull/992
    - fix(gemini): response json schema compatible, close #991 by @looplj in https://github.com/looplj/axonhub/pull/1000
    - feat(system): add manual log cleanup trigger UI by @cikichen in https://github.com/looplj/axonhub/pull/1001
    - opt: auto reorder channels, close #822 by @looplj in https://github.com/looplj/axonhub/pull/1005
    - feat: add gpt-5.4 to codex, close #999 by @looplj in https://github.com/looplj/axonhub/pull/1006
    - feat: filter requests by model id, close #994 by @looplj in https://github.com/looplj/axonhub/pull/1007
    New Contributors
    - @cikichen made their first contribution in https://github.com/looplj/axonhub/pull/1001
    Full Changelog: https://github.com/looplj/axonhub/compare/v0.9.13...v0.9.14
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/looplj/axonhub/releases/tag/v0.9.14
ReleaseTime: 2026-03-09T15:53:41.0000000Z
