Version: 0.9.30
Installer:
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  InstallerUrl: https://github.com/looplj/axonhub/releases/download/v0.9.30/axonhub_0.9.30_windows_amd64.zip
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  InstallerUrl: https://github.com/looplj/axonhub/releases/download/v0.9.30/axonhub_0.9.30_windows_arm64.zip
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    What's Changed
    - docs: add Japanese README by @eltociear in https://github.com/looplj/axonhub/pull/1299
    - feat: add project profiles for channel filtering close #1233 by @looplj in https://github.com/looplj/axonhub/pull/1303
    - feat: search api key by key, close #1301 by @looplj in https://github.com/looplj/axonhub/pull/1305
    - chore: clenup unnesessary project id for oauth channels by @looplj in https://github.com/looplj/axonhub/pull/1306
    - opt: add timeout for fx startup, close #1304 by @looplj in https://github.com/looplj/axonhub/pull/1307
    - opt: quota bdage float window, close #1300 by @looplj in https://github.com/looplj/axonhub/pull/1308
    - feat: add NVIDIA as model provider by @djdembeck in https://github.com/looplj/axonhub/pull/1309
    - chore(deps-dev): bump vite from 7.3.1 to 7.3.2 in /frontend by @dependabot[bot] in https://github.com/looplj/axonhub/pull/1310
    - opt(responses): fix function parameters missing properties, close #1032 by @looplj in https://github.com/looplj/axonhub/pull/1311
    - fix: project cache cause auth faield, close #1298 by @looplj in https://github.com/looplj/axonhub/pull/1312
    - chore: cleanup agent rules by @looplj in https://github.com/looplj/axonhub/pull/1314
    New Contributors
    - @eltociear made their first contribution in https://github.com/looplj/axonhub/pull/1299
    Full Changelog: https://github.com/looplj/axonhub/compare/v0.9.29...v0.9.30
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/looplj/axonhub/releases/tag/v0.9.30
ReleaseTime: 2026-04-07T04:25:25.0000000Z
