Version: "3.13"
Installer:
- InstallerUrl: https://sourceforge.net/projects/nsis/files/NSIS 3/3.13/nsis-3.13-setup.exe/download
Locale:
- Key: ReleaseNotesUrl
  Value: https://nsis.sourceforge.io/Docs/AppendixF.html
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    F.1.1 Changelog

    F.1.1.1 Minor Changes
    - Fixed nsExec::ExecToLog crash (bug #1323)

    F.1.1.2 Translations
    - Updated Italian and Korean

    F.1.1.3 Build System
    - TARGET_ARCH is used as the default makensis target (patch #314, bug #1294)
- Key: ReleaseNotesUrl
  Value: https://nsis.sourceforge.io/Docs/AppendixF.html#v3.13
ReleaseTime: 2026-09-27
