Version: 150.0.4078.99
Installer:
- Architecture: x86
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/3d48f602-9d56-4f56-9739-ecb196c82b9c/MicrosoftEdgeWebView2RuntimeInstallerX86.exe
  InstallerSha256: 9B4CDA63294D3FF4217E54C8923D57FD3697ED64E5B9CBE5D3999FB305E2C7B5
- Architecture: x64
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/d06c217f-cef1-471d-a639-fad978ef4a40/MicrosoftEdgeWebView2RuntimeInstallerX64.exe
- Architecture: arm64
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/07d0a15d-0e51-4e2b-944b-b3b7b10ea37c/MicrosoftEdgeWebView2RuntimeInstallerARM64.exe
Locale: []
ETag:
- '"tWYtwzw2qWeXhAZM2GprJmc+40Q="'
ETagX64:
- '"7u9ahs2+448yySkII5V73tQhGvo="'
ETagARM64:
- '"S8HKlqymxwnMHvoNFdX1WeVGwUQ="'
