Version: 2.2.1
Installer:
- InstallerUrl: https://releases.shuitunapp.com/v2.2.1/shuitunapp.exe
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    新增功能
    1. 修复画笔在部分情况下无法右键清屏问题
    2. 修复拖动悬浮球画笔内容消失问题
    3. 修复部分图形画笔无法选择问题
    4. 修复部分情况下 cpu 占用过高问题
ReleaseTime: 2026-05-25T09:46:18.0000000Z
