Version: 17.0.20.12.1
Installer:
- Architecture: x64
  InstallerUrl: https://corretto.aws/downloads/resources/17.0.20.12.1/amazon-corretto-17.0.20.12.1-windows-x64.msi
Locale: []
RealVersion: 17.0.20.12
ReleaseTime: 2026-09-26T00:02:19.0000000Z
