Version: 2.1.0
Installer:
- InstallerUrl: https://github.com/nexmoe/VidBee/releases/download/v2.1.0/vidbee-2.1.0-setup.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    View the full changelog at vidbee.org/changelog.
    Full Changelog: https://github.com/nexmoe/VidBee/compare/v2.0.2...v2.1.0
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/nexmoe/VidBee/releases/tag/v2.1.0
ReleaseTime: 2026-08-30T11:43:40.0000000Z
