Version: 4.9.0.195
Installer:
- InstallerType: inno
  InstallerUrl: https://dashboard.barn.owllabs.com/products/DESKTOPAPP/download/latest/exe
- InstallerType: zip
  NestedInstallerType: msix
  InstallerUrl: https://dashboard.barn.owllabs.com/products/DESKTOPAPP/download/latest/msix
Locale: []
