Version: 18.3.0.5
Installer:
- Architecture: x86
  InstallerUrl: https://dl.bitsum.com/files/beta/processlassosetup32.exe
  InstallerSha256: 3F681DB8BFD32A421813FEB34C7A6A1FEF60C61B83BB83F8344A3BB4BB6B8C9C
- Architecture: x64
  InstallerUrl: https://dl.bitsum.com/files/beta/processlassosetup64.exe
Locale: []
LastModified: Tue, 11 Aug 2026 19:45:48 GMT
LastModifiedX64: Tue, 11 Aug 2026 19:45:51 GMT
