Version: 18.2.0.13
Installer:
- Architecture: x86
  InstallerUrl: https://dl.bitsum.com/files/beta/processlassosetup32.exe
  InstallerSha256: 83D033ADEEF00A515A2382DB6A8C75BA7A3E967C79C7D3C2D27A705E4EF6DEE7
- Architecture: x64
  InstallerUrl: https://dl.bitsum.com/files/beta/processlassosetup64.exe
Locale: []
LastModified: Fri, 08 May 2026 10:33:32 GMT
LastModifiedX64: Fri, 08 May 2026 10:33:35 GMT
