Version: 18.0.1.17
Installer:
- Architecture: x86
  InstallerUrl: https://dl.bitsum.com/files/beta/processlassosetup32.exe
  InstallerSha256: D2A07B4EFA8647EF289789726B43056E127D83DDC9E9C546585FB137B843A98D
- Architecture: x64
  InstallerUrl: https://dl.bitsum.com/files/beta/processlassosetup64.exe
Locale: []
LastModified: Fri, 10 Apr 2026 18:17:34 GMT
LastModifiedX64: Fri, 10 Apr 2026 18:17:37 GMT
