Version: 18.0.0.23
Installer:
- Architecture: x86
  InstallerUrl: https://dl.bitsum.com/files/beta/processlassosetup32.exe
  InstallerSha256: 5DFB05631F5F935AA4EF7C23B0EA87F303CF90061496072A9E99431564264607
- Architecture: x64
  InstallerUrl: https://dl.bitsum.com/files/beta/processlassosetup64.exe
Locale: []
LastModified: Tue, 17 Mar 2026 21:02:13 GMT
LastModifiedX64: Tue, 17 Mar 2026 21:02:17 GMT
