Version: 18.2.0.15
Installer:
- Architecture: x86
  InstallerUrl: https://dl.bitsum.com/files/beta/processlassosetup32.exe
  InstallerSha256: 2977100A7EAA526E173E3E936D48795CAB3CF914AF17ED5A16A30CC7FC7C60B5
- Architecture: x64
  InstallerUrl: https://dl.bitsum.com/files/beta/processlassosetup64.exe
Locale: []
LastModified: Mon, 11 May 2026 12:46:52 GMT
LastModifiedX64: Mon, 11 May 2026 12:46:55 GMT
