Version: 17.2.0.13
Installer:
- Architecture: x86
  InstallerUrl: https://dl.bitsum.com/files/beta/processlassosetup32.exe
  InstallerSha256: E44ABD4B2CA68668CB44987A7BB1EDD8F0E7F84EB42258811048CC9C0F85A924
- Architecture: x64
  InstallerUrl: https://dl.bitsum.com/files/beta/processlassosetup64.exe
Locale: []
LastModified: Mon, 09 Mar 2026 15:58:45 GMT
LastModifiedX64: Mon, 09 Mar 2026 15:58:49 GMT
