Version: 2.15.0-beta.3
Installer:
- Architecture: x64
  InstallerUrl: https://github.com/PCL-Community/PCL-CE/releases/download/v2.15.0-beta.3/PCL2_CE_Beta_x64.exe
- Architecture: arm64
  InstallerUrl: https://github.com/PCL-Community/PCL-CE/releases/download/v2.15.0-beta.3/PCL2_CE_Beta_ARM64.exe
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    本更新修复了一些已知问题，建议所有 Beta 版用户安装。
    2.15.0-beta.3 更新一览(2026-06-13)
    🚀 功能追加
    - i18n: “你知道吗？”本地化 (#2996)
    - i18n: 工具、联机与辅助页面迁移 (#2999)
    - download: 折叠前置资源列表 (#2986)
    - 新的存档信息读取器 (#2978)
    - 提示条右置 & 对应设置项 (#3006)
    - 增加文件哈希计算缓存功能 (#2973)
    - svg-icon: 引入 SvgIcon 以支持加载 .svg 文件并将所有图标替换为 Lucide (#3018)
    - 重新实现 Toast 通知（第一部分：基础通知） (#2983)
    - download: 搜索框支持识别资源链接 (#2989)
    - i18n: 非中国大陆地区禁用地区特供功能 (#3074)
    - Collapse-Bar: 添加折叠/展开动画 (#3081)
    🐛 问题修复
    - profile: Ms login (#2994)
    - i18n: 修复环境警告弹窗显示原始语言键 (#2958)
    - network-service: 修复 NetworkService 启动时序 (#3002)
    - setup-feedback: 修复反馈列表加载时 body 为空的空引用异常 (#2946)
    - json: 兼容 ISO 8601 当日终点时间 24:00 (#3004)
    - net: 由于未正确处理 HttpContent 导致的请求失败 (#3016)
    - 修正 ArgConfig 索引器参数以使用 PathInstance 而非 Instance 对象 (#3019)
    - instance-over-all: 使用 Path.Combine 修复重命名实例时路径拼接错误 (#3022)
    - instance-export: 修复整合包导出缺少二级目录 (#3026)
    - mod-main: 修复弹出提示靠右显示时收回动画的方向不正确 (#3056)
    - mod-main: 修复连续触发 Hint 导致位置发生偏移 (#3055)
    - 进程优先级选项显示与配置写入不一致 (#3027)
    - Resolve the request changes in #3031 (#3059)
    - instance-setup: 修复部分配置未正常保存 (#3057)
    - mod-launch: .ToString → .ToString() (#3065)
    - i18n: “自动下载模组前置”缺少国际化 (#3083)
    - file: 缺少默认打开程序时使用记事本兜底 (#3087)
    - i18n: 将 zh-CN 中的 Mod 统一翻译为模组 (#3092)
    - speed-left: 修复任务管理页面卡片右上角取消按钮消失 (#3095)
    - setup-ui: 修复自定义主页 URL 无法保存 (#3104)
    - request: 为 CurseForge 下载 CDN 应用 API Key (#3108)
    - 修复未自动删除下载失败/取消的实例 (#3110)
    - download: Prevent OptiFine cache path traversal (#3041)
    - homepage: Validate news links before opening (#3043)
    - Sanitize component download filenames (#3044)
    - Validate datapack update filenames and enforce path containment (#3046)
    - setup-launch: 修复自定义尺寸输入框不显示 (#3126)
    - setup-game-manage: 修复自动安装前置功能无法关闭 (#3124)
    🚜 重构
    - 使用 field 语法 (#3008)
    - instance-save-info: 重构 PageInstanceSavesInfo (#3017)
    - identity: Clarify IdentityModel exceptions (#3025)
    - 重构 ModMinecraft (#3031)
    - help: 移除帮助功能 (#3093)
    - Remove origin issue (#3099)
    - Migrate Newtonsoft.Json to System.Text.Json again (#3128)
    🎨 样式调整
    - 去除 Core 多余的 using (#2982)
    - 修复 Core 命名规范问题 (#2981)
    🤖 工作流配置
    - help: Remove help packaging workflow (#3096)
    - Upgrade checkout (#3114)
    ⚙️ 其他改动
    - hints: Remove PCL2-Language (#3028)
    - Remove ModWorld.cs (#3032)
    - Remove PageHomePageMarket (#3045)
    - Remove FodyWeavers.xml (#3060)
    - 移除内存优化功能 (#3067)
    - mod-launch: 简化 Java 信息日志并移除冗余 null 判断 (#3071)
    - 不打包 accountsx 模组配置 (#3078)
    - 移除远古版本配置迁移相关代码 (#3097)
    - i18n: 修复并优化 #3074 “非中国大陆地区禁用地区特供功能” 中的问题 (#3091)
    - mod-setup: 修改主页投稿链接为 CE 的 discussions 网页 (#3105)
    - 移除 Custom.xml (#3106)
    - 移除未使用的 NuGet 库 (#3129)

    如果你有 Mirror 酱 CDK 可以直接使用此高速下载源
    你也可以直接在下方的 Assets 中下载

    GPG 签名公钥
    公钥指纹 81D9430A309B84272D518584EDF4453F0BBB862E
- Locale: zh-CN
  Key: ReleaseNotesUrl
  Value: https://github.com/PCL-Community/PCL-CE/releases/tag/v2.15.0-beta.3
ReleaseTime: 2026-06-13T10:04:34.0000000Z
