Version: 2026.02.00
Installer:
- InstallerLocale: en
  Architecture: x86
  InstallerUrl: https://cdn.sw.altova.com/v2026r2/en/DatabaseSpyEnt2026rel2.exe
  ProductCode: '{D1AB114C-802D-4502-A5B0-2549E57ECB7C}'
- InstallerLocale: en
  Architecture: x64
  InstallerUrl: https://cdn.sw.altova.com/v2026r2/en/DatabaseSpyEnt2026rel2_x64.exe
  ProductCode: '{5AF6617F-948D-49D8-A494-EF2DF9726BDD}'
- InstallerLocale: de
  Architecture: x86
  InstallerUrl: https://cdn.sw.altova.com/v2026r2/de/DatabaseSpyEnt2026rel2_DE.exe
  ProductCode: '{D1AB114C-802D-4502-A5B0-2549E57ECB7C}'
- InstallerLocale: de
  Architecture: x64
  InstallerUrl: https://cdn.sw.altova.com/v2026r2/de/DatabaseSpyEnt2026rel2_x64_DE.exe
  ProductCode: '{5AF6617F-948D-49D8-A494-EF2DF9726BDD}'
- InstallerLocale: es
  Architecture: x86
  InstallerUrl: https://cdn.sw.altova.com/v2026r2/es/DatabaseSpyEnt2026rel2_ES.exe
  ProductCode: '{D1AB114C-802D-4502-A5B0-2549E57ECB7C}'
- InstallerLocale: es
  Architecture: x64
  InstallerUrl: https://cdn.sw.altova.com/v2026r2/es/DatabaseSpyEnt2026rel2_x64_ES.exe
  ProductCode: '{5AF6617F-948D-49D8-A494-EF2DF9726BDD}'
- InstallerLocale: fr
  Architecture: x86
  InstallerUrl: https://cdn.sw.altova.com/v2026r2/fr/DatabaseSpyEnt2026rel2_FR.exe
  ProductCode: '{D1AB114C-802D-4502-A5B0-2549E57ECB7C}'
- InstallerLocale: fr
  Architecture: x64
  InstallerUrl: https://cdn.sw.altova.com/v2026r2/fr/DatabaseSpyEnt2026rel2_x64_FR.exe
  ProductCode: '{5AF6617F-948D-49D8-A494-EF2DF9726BDD}'
- InstallerLocale: ja
  Architecture: x86
  InstallerUrl: https://cdn.sw.altova.com/v2026r2/jp/DatabaseSpyEnt2026rel2_JP.exe
  ProductCode: '{D1AB114C-802D-4502-A5B0-2549E57ECB7C}'
- InstallerLocale: ja
  Architecture: x64
  InstallerUrl: https://cdn.sw.altova.com/v2026r2/jp/DatabaseSpyEnt2026rel2_x64_JP.exe
  ProductCode: '{5AF6617F-948D-49D8-A494-EF2DF9726BDD}'
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: ""
Hash: ad5df51583dcfd4b7c821f745d842ff747b5204a30a289bc537d54ac80da73fc
