Version: 3.0.26
Installer:
- InstallerUrl: https://sos-ch-dk-2.exo.io/seafile-downloads/seadrive-3.0.26-en.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - [win] Set read-only local permissions for files in read-only folders
    - [mac] Fix a bug when renaming a file in a kept-offline folder
    - [win] Don't display username and server name in virtual drive entry point when there is only one account
    - Fix handling of URLs ending with multiple slashes
    - Properly handles libraries with names only differ in cases
ReleaseTime: 2026-09-22
