Version: 3.0.22
Installer:
- InstallerLocale: en-US
  InstallerUrl: https://sos-ch-dk-2.exo.io/seafile-downloads/seadrive-3.0.22-en.msi
- InstallerLocale: zh-CN
  InstallerUrl: https://seafile-downloads.oss-cn-shanghai.aliyuncs.com/seadrive-3.0.22.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - [win] Fix filename encoding handling when open file from web browser
    - Record network errors when server is offline, instead of server error. Such errors can now auto-recover when server is online.
    - [win] Avoid misleading index error when writing to a large file
    - [mac] Support moving downloaded files to system trash
    - [win] Improve download speed for 10Gb networks
    - [linux] Disallow updating file attributes in read-only folder
    - [win] Avoid unintended file deletions when syncing fast "remove then create" operation sequence from the server
    - [mac] Don't display files in the root folder if root folder is set to invisible
    - [win/mac] Don't upload new folders when they're created in read-only folders
ReleaseTime: 2026-05-15
