Version: 9.17.5
Installer:
- InstallerUrl: https://download.getupnote.com/app/UpNote Setup.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - Fixed an issue where YouTube videos were not displayed properly.
    - Improved heading formatting to be more reliable.
ReleaseTime: 2026-03-11T13:21:01.5830000Z
