Version: 3.27.1
Installer:
- Architecture: x64
  InstallerUrl: https://github.com/ProtonMail/proton-bridge/releases/download/v3.27.1/Bridge-Installer.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Fixed
    - BRIDGE-644: Recover from corrupted sync state file; force file sync during write.
- Key: ReleaseNotesUrl
  Value: https://github.com/ProtonMail/proton-bridge/releases/tag/v3.27.1
ReleaseTime: 2026-09-29T13:55:21.0000000Z
