Version: 147.0.7727.15
Installer:
- Architecture: x86
  InstallerUrl: https://dl.google.com/release2/chrome/o4noaeaa2u7l6gmucizy2xfp7q_147.0.7727.15/147.0.7727.15_chrome_installer_uncompressed.exe
- Architecture: x64
  InstallerUrl: https://dl.google.com/release2/chrome/acxdkgy6jrxp2sg3r7nxtlwecjfq_147.0.7727.15/147.0.7727.15_chrome_installer_uncompressed.exe
- Architecture: arm64
  InstallerUrl: https://dl.google.com/release2/chrome/adltguylyzfnxnz7u4wprhtdvhna_147.0.7727.15/147.0.7727.15_chrome_installer_uncompressed.exe
Locale: []
