Version: 152.0.7977.30
Installer:
- Architecture: x86
  InstallerUrl: https://dl.google.com/release2/chrome/ad5pdqx7aizmkggr2lb2tjjv33ha_152.0.7977.30/152.0.7977.30_chrome_installer_uncompressed.exe
- Architecture: x64
  InstallerUrl: https://dl.google.com/release2/chrome/adpcyfpww3yys6rekh6oar2lzjxq_152.0.7977.30/152.0.7977.30_chrome_installer_uncompressed.exe
- Architecture: arm64
  InstallerUrl: https://dl.google.com/release2/chrome/e3fsvm2zfbxl6z4n2iddw5d46u_152.0.7977.30/152.0.7977.30_chrome_installer_uncompressed.exe
Locale: []
