Version: 153.0.8010.12
Installer:
- Architecture: x86
  InstallerUrl: https://dl.google.com/release2/chrome/djdngllgxjf55mlyqwuycczkni_153.0.8010.12/153.0.8010.12_chrome_installer_uncompressed.exe
- Architecture: x64
  InstallerUrl: https://dl.google.com/release2/chrome/adkp36pewa2ozlpk34dcz4bsckma_153.0.8010.12/153.0.8010.12_chrome_installer_uncompressed.exe
- Architecture: arm64
  InstallerUrl: https://dl.google.com/release2/chrome/acj3rdet4s5llit77kzeb3bw3qta_153.0.8010.12/153.0.8010.12_chrome_installer_uncompressed.exe
Locale: []
