Version: 2026.1.02650
Installer:
- Architecture: x64
  InstallerUrl: https://github.com/datalust/seqcli/releases/download/v2026.1.02650/seqcli-2026.1.02650-win-x64.zip
  NestedInstallerFiles:
  - RelativeFilePath: seqcli-2026.1.02650-win-x64\seqcli.exe
    PortableCommandAlias: seqcli
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    What's Changed
    - Update .NET SDK and packages by @nblumhardt-ro in https://github.com/datalust/seqcli/pull/502
    Full Changelog: https://github.com/datalust/seqcli/compare/v2026.1.02645...v2026.1.02650
- Key: ReleaseNotesUrl
  Value: https://github.com/datalust/seqcli/releases/tag/v2026.1.02650
ReleaseTime: 2026-09-24T06:27:01.0000000Z
