Version: 11.1.0.0
Installer:
- Architecture: x86
  InstallerType: wix
  InstallerUrl: https://downloads.pdf-xchange.com/11.1.0.0/ToolsV11.x86.msi
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://downloads.pdf-xchange.com/11.1.0.0/ToolsV11.x64.msi
- Architecture: arm64
  InstallerType: wix
  InstallerUrl: https://downloads.pdf-xchange.com/11.1.0.0/ToolsV11.ARM64.msi
Locale:
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://www.pdf-xchange.com/product/pdf-tools/history
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    New features
    1. Added an option to control the behavior of the on-screen keyboard on touch devices (Preferences > General > Show the Touch Keyboard).
    2. Added an option to the 'Export Form Data' action that adds a filename column to the output CSV file.
    Bug fixes and other updates/enhancements:
    1. Fixed an issue where the Sign Document action showed a stub document preview instead of the document being processed during a tool run.
    2. Fixed an issue that allowed Application Variables with duplicate names to be created. (49857)
    3. Fixed the behavior of methods in the 'Apply Metadata Template' functionality of the 'Change Document Properties' action. (49782)
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://www.pdf-xchange.com/product/pdf-tools/history?build=11.1.0.0
ReleaseTime: 2026-09-29T07:00:00.0000000Z
