Version: 1.21.4
Installer:
- Architecture: x64
  InstallerUrl: https://sfc-repo.snowflakecomputing.com/coco-desktop/downloads/1.21.4/Cortex-Code-win32-x64-user-setup.exe
- Architecture: arm64
  InstallerUrl: https://sfc-repo.snowflakecomputing.com/coco-desktop/downloads/1.21.4/Cortex-Code-win32-arm64-user-setup.exe
Locale: []
ReleaseTime: 2026-09-11T22:31:36.0000000Z
