Version: 1.15.1
Installer:
- Architecture: x64
  InstallerUrl: https://sfc-repo.snowflakecomputing.com/coco-desktop/downloads/1.15.1/Cortex-Code-win32-x64-user-setup.exe
- Architecture: arm64
  InstallerUrl: https://sfc-repo.snowflakecomputing.com/coco-desktop/downloads/1.15.1/Cortex-Code-win32-arm64-user-setup.exe
Locale: []
ReleaseTime: 2026-05-30T01:43:06.0000000Z
