Version: 1.0.46
Installer:
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  InstallerUrl: https://github.com/DingTalk-Real-AI/dingtalk-workspace-cli/releases/download/v1.0.46/dws-windows-amd64.zip
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  InstallerUrl: https://github.com/DingTalk-Real-AI/dingtalk-workspace-cli/releases/download/v1.0.46/dws-windows-arm64.zip
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Changelog
    - bba94c0092acd59d6ecd72026640d8821a51e1eb docs(changelog): cut 1.0.46 (#542)
    - fe4a79283c5ce18ebe6a16356b4a6cbb95289a67 fix(pat): keep agent code grants aligned (#536)
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/DingTalk-Real-AI/dingtalk-workspace-cli/releases/tag/v1.0.46
ReleaseTime: 2026-07-01T08:51:14.0000000Z
