Version: 0.3.1
Installer:
- Architecture: x64
  InstallerUrl: https://github.com/JohanChane/clashtui/releases/download/v0.3.1/clashtui-windows-amd64-v0.3.1.zip
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: Please see CHANGELOG-v0.3.1
- Key: ReleaseNotesUrl
  Value: https://github.com/JohanChane/clashtui/releases/tag/v0.3.1
ReleaseTime: 2026-05-26T16:45:16.0000000Z
