Version: 3.36.1
Installer:
- Architecture: x64
  InstallerUrl: https://download.mp3tag.de/mp3tag-v3.36.1-x64-setup.exe
- Architecture: x86
  InstallerUrl: https://download.mp3tag.de/mp3tag-v3.36.1-setup.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: 'FIX: regression where a deadlock occurs when adding cover art to files with varying existing covers (since v3.36-beta.5).'
ReleaseTime: 2026-08-29T12:30:00.0000000Z
