Version: 0.4.20
Installer:
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  InstallerUrl: https://github.com/wanshuiyin/Auto-claude-code-research-in-sleep/releases/download/v0.4.20/aris-code-windows-x64.zip
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: 'Full Changelog: https://github.com/wanshuiyin/Auto-claude-code-research-in-sleep/compare/v0.4.19...v0.4.20'
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/wanshuiyin/Auto-claude-code-research-in-sleep/releases/tag/v0.4.20
ReleaseTime: 2026-06-19T10:42:39.0000000Z
