Version: 1.3.10
Installer:
- Architecture: x64
  InstallerType: portable
  InstallerUrl: https://github.com/alibaba/open-code-review/releases/download/v1.3.10/opencodereview-windows-amd64.exe
- Architecture: arm64
  InstallerType: portable
  InstallerUrl: https://github.com/alibaba/open-code-review/releases/download/v1.3.10/opencodereview-windows-arm64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    What's Changed
    - Fix workspace symlink diff containment by @MuoDoo in https://github.com/alibaba/open-code-review/pull/125
    - fix: update mimo provider endpoint and add mimo flash model by @guqihao-7 in https://github.com/alibaba/open-code-review/pull/132
    - feat: add minimax provider by @guqihao-7 in https://github.com/alibaba/open-code-review/pull/131
    - feat: add Kimi provider by @guqihao-7 in https://github.com/alibaba/open-code-review/pull/130
    Full Changelog: https://github.com/alibaba/open-code-review/compare/v1.3.8...v1.3.10
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/alibaba/open-code-review/releases/tag/v1.3.10
ReleaseTime: 2026-06-15T04:04:51.0000000Z
