Version: 2026.02.00
Installer:
- Architecture: x86
  InstallerUrl: https://cdn.sw.altova.com/v2026r2/multi-lingual/StyleVisionServer2026rel2.exe
  ProductCode: '{B7C33456-6580-4B14-99DE-49BA3C2FEDE4}'
- Architecture: x64
  InstallerUrl: https://cdn.sw.altova.com/v2026r2/multi-lingual/StyleVisionServer2026rel2_x64.exe
  ProductCode: '{E6141974-2447-4F62-8162-B33C8C7B25A1}'
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: '[General Application] Error message returned for generate command failure has malformed path'
Hash: 554ddbfd9e5e2877862b37d38b7c34608a593fc0f2c6b2bb3bc693e7ea2db53a
