Version: 0.4.56
Installer:
- InstallerUrl: https://updates.alma.now/alma-0.4.56-win-x64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    0.4.56
    Features
    - Reply to a specific passage in a team message.
    - Share an existing thread with the team.
ReleaseTime: 2026-09-18T09:15:00.1530000Z
