Version: 0.0.987
Installer:
- InstallerUrl: https://updates.alma.now/alma-0.0.987-win-x64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    0.0.987
    Features
    - Added references for turn snippets, alchemy furnace, and crafting recipe tables.
ReleaseTime: 2026-08-21T07:40:00.4410000Z
