Version: "21.0"
Installer:
- InstallerUrl: https://cdn.investintech.com/download/InstallAble2ExtractPro.exe
  InstallerSha256: EDCFC6556A72AE13CEDA66F5E454CEE25FD694FC17585AF03984FD28BEB26C3B
Locale: []
LastModified: Sat, 07 Mar 2026 20:23:19 GMT
