Version: 9.0.8.8311
Installer:
- InstallerUrl: https://smartdl.lenovo.com.cn/slbupdate/2026/x64/9.0.8.8311/RootPath/SLBInstall/9.0.8.8311/SLBInstall.exe.zip
  NestedInstallerFiles:
  - RelativeFilePath: SLBInstall.exe
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    1. 网页翻译功能升级，识别更精准
    2. 修复一些已知问题
