Version: 3.4.14
Installer:
- Architecture: x64
  InstallerUrl: https://download.todesktop.com/2003096gmmnl0g1/Sunsama Setup 3.4.14 - Build 2610024fcalyyd7-x64.exe
- Architecture: arm64
  InstallerUrl: https://download.todesktop.com/2003096gmmnl0g1/Sunsama Setup 3.4.14 - Build 2610024fcalyyd7-arm64.exe
Locale: []
ReleaseTime: 2026-10-02T02:24:03.0000000Z
