Version: 3.4.3
Installer:
- Architecture: x64
  InstallerUrl: https://download.todesktop.com/2003096gmmnl0g1/Sunsama Setup 3.4.3 - Build 2604304fe1dofts-x64.exe
- Architecture: arm64
  InstallerUrl: https://download.todesktop.com/2003096gmmnl0g1/Sunsama Setup 3.4.3 - Build 2604304fe1dofts-arm64.exe
Locale: []
ReleaseTime: 2026-04-30T18:13:41.0000000Z
