Version: 4.1.0
Installer:
- InstallerUrl: https://production-archimedes-secure-browser-artifacts.s3.amazonaws.com/latest/windows/guardian-browser-x64.exe
Locale: []
ReleaseTime: 2026-08-11T03:19:17.0200000Z
