Version: 7.67.10
Installer:
- Architecture: x86
  InstallerUrl: https://lf16-larkversion.larksuitecdn.com/obj/lark-version-sg/2ae3d3b3/Lark-win32_ia32-7.67.10-signed.exe
- Architecture: x64
  InstallerUrl: https://lf16-larkversion.larksuitecdn.com/obj/lark-version-sg/e467b759/Lark-win32_x64-7.67.10-signed.exe
Locale:
- Key: ReleaseNotesUrl
  Value: https://www.larksuite.com/hc/en-US/articles/360046836333
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Base
    - Quickly add records to a base by simply pasting text or images. The AI will automatically identify and intelligently match and populate the fields.
    Lark Forms
    - Users can now use voice to answer form questions and the AI will automatically populate the right fields, speeding up completion and simplifying data collection.
    - The phone number question type can be used to collect respondents' mobile or landline numbers, which is great for customer registrations, follow-up visits, contact lists, and more.
- Key: ReleaseNotesUrl
  Value: https://www.larksuite.com/hc/en-US/articles/957611367407
- Locale: zh-CN
  Key: ReleaseNotesUrl
  Value: https://www.larksuite.com/hc/zh-CN/articles/360046836333
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    多维表格
    - 在多维表格的数据表中，你可以通过 AI 粘贴文本或图片的方式新增记录。粘贴时，系统会自动识别粘贴的文本或图片内容，并借助 AI 能力智能匹配填充为数据表记录。导入更高效，协作更便捷。
    Lark Forms
    - Lark Forms 新增 AI 语音录入功能。填写问卷时，如果开启语音录入，AI 可自动识别语音里的业务指令，并把语音内容实时转化为结构化的表单数据。问卷填写更高效，信息收集更便捷。
    - 你可以在 Lark Forms 中增加电话号码题型，用于收集填写者的手机号码或固定电话，适用于客户信息登记、后续回访与联系等场景。覆盖更广泛，填写更方便。
- Locale: zh-CN
  Key: ReleaseNotesUrl
  Value: https://www.larksuite.com/hc/zh-CN/articles/957611367407
ReleaseTime: 2026-05-06T11:00:17.0000000Z
