Version: 1.6.5
Installer:
- Architecture: x64
  InstallerUrl: https://fresh.superwhisper.com/download?asset=541658201&filename=superwhisper_1.6.5_x64-setup.exe
- Architecture: arm64
  InstallerUrl: https://fresh.superwhisper.com/download?asset=541658200&filename=superwhisper_1.6.5_arm64-setup.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Improvements
    - Cohere is now the default local model on non ARM machines
    - Download progress UI for model dependencies in the Models library
    - Press Enter to save when editing a speaker names
    Fixes
    - Reprocessing a recording with a different mode no longer changes your active mode
ReleaseTime: 2026-09-02
