Version: 0.6.0-alpha
Installer:
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://github.com/BuilderIO/native-app-distribution/releases/download/v0.6.0-alpha/Builder.io-0.6.0-x64.msi
- Architecture: arm64
  InstallerType: wix
  InstallerUrl: https://github.com/BuilderIO/native-app-distribution/releases/download/v0.6.0-alpha/Builder.io-0.6.0-arm64.msi
Locale:
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/BuilderIO/native-app-distribution/releases/tag/v0.6.0-alpha
ReleaseTime: 2026-09-02T08:19:41.0000000Z
RealVersion: 0.6.0.0
