Version: MPS-261.24374.603
Installer:
- Architecture: x64
  InstallerUrl: https://download.jetbrains.com/mps/2026.1/MPS-2026.1-RC1.exe
  ProductCode: JetBrains MPS 2026.1
  InstallerSha256: BE3EACCC0C4B697173CABCB05DBCEFE25ED6716BF3A2EE27987CA67D17C82EAA
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: If you want to learn more, please check our issue tracker.
- Key: ReleaseNotesUrl
  Value: https://youtrack.jetbrains.com/releaseNotes/MPS?q=Fix%20versions:{2026.1%20RC}%20State:Fixed&title=MPS%202026.1-RC1%20Release%20Notes
ReleaseTime: 2026-06-11
