Version: 0.3.5
Installer:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/jerrywu001/cc-sessions-viewer/releases/download/v0.3.5/Sessions.Viewer_0.3.5_x64-setup.exe
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://github.com/jerrywu001/cc-sessions-viewer/releases/download/v0.3.5/Sessions.Viewer_0.3.5_x64_en-US.msi
Locale:
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/jerrywu001/cc-sessions-viewer/releases/tag/v0.3.5
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/jerrywu001/cc-sessions-viewer/blob/HEAD/CHANGELOG.md
ReleaseTime: 2026-07-23T13:25:13.0000000Z
