Version: 0.2.7
Installer:
- InstallerUrl: https://package-cdn.qclaw.qq.com/qclaw/win/0.2.7-5001-397/QClaw-Setup-0.2.7-5001-397.exe
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    🎉 v0.2.7版本更新内容:
    1、对话主流程交互优化
    2、性能优化与 bugfix
