Version: 2.0.1129.0
Installer:
- Architecture: x86
  InstallerUrl: https://res.cdn.office.net/remote-desktop-windows-client/25425a80-babd-4cbe-8764-d2715555c8a8/WindowsApp_x86_Release_2.0.1129.0.msix
- Architecture: x64
  InstallerUrl: https://res.cdn.office.net/remote-desktop-windows-client/0a11b53f-95d7-4ea7-a283-00f8162fabdf/WindowsApp_x64_Release_2.0.1129.0.msix
- Architecture: arm64
  InstallerUrl: https://res.cdn.office.net/remote-desktop-windows-client/581f2c9d-0acb-46f6-8346-28614bbf5e83/WindowsApp_arm64_Release_2.0.1129.0.msix
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - Stability and performance improvements for Windows 365 Boot.
    - Improved handling of networks requiring captive portal in Windows 365 Boot.
    - Improved handling of auto-reconnect to remote sessions when undocking from a docking station and changing display configurations and network for Windows 365 Boot.
    - Improved client logging, diagnostics, and error classification to help admins troubleshoot connection and feed issues.
ReleaseTime: 2026-04-29
