Version: 1.2.7279.0
Installer:
- Architecture: x86
  InstallerUrl: https://res.cdn.office.net/remote-desktop-windows-client/c0843686-6494-4b83-a194-ec333759631e/RemoteDesktop_1.2.7279.0_x86.msi
- Architecture: x64
  InstallerUrl: https://res.cdn.office.net/remote-desktop-windows-client/04dda26b-a19a-4085-956a-f87d81bb03ec/RemoteDesktop_1.2.7279.0_x64.msi
- Architecture: arm64
  InstallerUrl: https://res.cdn.office.net/remote-desktop-windows-client/929d2837-645d-4b75-83d6-57e4d71dd196/RemoteDesktop_1.2.7279.0_ARM64.msi
Locale: []
