Version: 1.2.7391.0
Installer:
- Architecture: x86
  InstallerUrl: https://res.cdn.office.net/remote-desktop-windows-client/fe14bee0-2c3c-4ead-91ff-0c9f623cc132/RemoteDesktop_1.2.7391.0_x86.msi
- Architecture: x64
  InstallerUrl: https://res.cdn.office.net/remote-desktop-windows-client/b441efed-bddd-4bdc-a3da-c3481cb65896/RemoteDesktop_1.2.7391.0_x64.msi
- Architecture: arm64
  InstallerUrl: https://res.cdn.office.net/remote-desktop-windows-client/3a950274-9234-4141-a86e-dd2939a3f5bf/RemoteDesktop_1.2.7391.0_ARM64.msi
Locale: []
