Version: 2.30.90
Installer:
- InstallerType: nullsoft
  InstallerUrl: https://cp.intermedia.net/voice/pbx/softphonereleases/default/latest-win/intermedia-unite.exe
  InstallerSha256: E677CCB5816B4B4F851AA97107F347A56BFAEEACDAE815CF0B4C7E0FB91B77DE
- Architecture: x86
  InstallerType: wix
  InstallerUrl: https://cp.intermedia.net/voice/pbx/softphonereleases/default/latest-win/intermedia-unite-ia32.msi
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://cp.intermedia.net/voice/pbx/softphonereleases/default/latest-win/intermedia-unite-x64.msi
Locale: []
ETag:
- '"072c92beff2dc1:0"'
ETagMSIx86:
- '"0294a1ceff2dc1:0"'
ETagMSIx64:
- '"083ac1eeff2dc1:0"'
