Version: 48.0.1
Installer:
- Architecture: x64
  InstallerUrl: https://github.com/bytecodealliance/wasmtime/releases/download/v48.0.1/wasmtime-v48.0.1-x86_64-windows.msi
Locale:
- Key: ReleaseNotesUrl
  Value: https://github.com/bytecodealliance/wasmtime/blob/HEAD/RELEASES.md
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Fixed
    - Context slots in component compositions are now correctly managed. #14139
    - The Host header is now set by default for HTTP requests sent with WASIp2. #14167
- Key: ReleaseNotesUrl
  Value: https://github.com/bytecodealliance/wasmtime/blob/release-48.0.0/RELEASES.md#4801
ReleaseTime: 2026-08-24T20:03:55.0000000Z
