Version: 2026.6.113
Installer:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/kwaroran/Risuai/releases/download/v2026.6.113/RisuAI_2026.6.113_x64-setup.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: '- fix: partly revert params due to reverse proxy conflict'
- Key: ReleaseNotesUrl
  Value: https://github.com/kwaroran/Risuai/releases/tag/v2026.6.113
ReleaseTime: 2026-06-11T18:41:00.0000000Z
