Version: 2026.6.103
Installer:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/kwaroran/Risuai/releases/download/v2026.6.103/RisuAI_2026.6.103_x64-setup.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: '- fix: converting character to module changes lorebooks in character'
- Key: ReleaseNotesUrl
  Value: https://github.com/kwaroran/Risuai/releases/tag/v2026.6.103
ReleaseTime: 2026-06-10T19:03:33.0000000Z
