Version: 0.7.6
Installer:
- Architecture: x64
  InstallerUrl: https://github.com/CrazyFigure/MyTerminal/releases/download/v0.7.6/MyTerminal_0.7.6_windows_x64-setup.exe
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: |-
    新增：
    - 为终端和编辑器补充剪贴板快捷键（ctrl + shift + c 和 ctrl + shift + v）
    - 内置字体
    修复：
    - 本次暂无修复项。
    优化：
    - update star history
    - update star history
    - update star history
    - update star history
    - update star history
    - update star history
    - update star history
- Locale: zh-CN
  Key: ReleaseNotesUrl
  Value: https://github.com/CrazyFigure/MyTerminal/releases/tag/v0.7.6
ReleaseTime: 2026-08-19T08:32:26.0000000Z
